Lundalogik/lime-elements

src/components/date-picker/date-picker.mdx, src/components/date-picker/date-picker.tsx, src/examples/date-picker/date-picker-programmatic-change.tsx
=> fix(datepicker): update datepicker when value is updated by the consumer

src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/components/picker/picker.mdx, src/components/picker/picker.scss, src/components/picker/picker.tsx, src/examples/picker/picker-icons.tsx
=> Improvements limel-picker

src/components/picker/picker.mdx, src/components/picker/picker.scss, src/components/picker/picker.tsx, src/examples/picker/picker-empty-suggestions.tsx
=> feat(picker): add optional message for empty search result

src/components/slider/slider.scss
Add a background color to the slider pin when the slider is disabled.
fix #304
=> fix(slider): fix background color for disabled slider

package-lock.json
Windows:
Linux:
macOS:
Mobile:
=> chore(package): updates by `npm audit fix`

src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/examples/chip-set/chip-set-choice.tsx, src/examples/chip-set/chip-set-filter.tsx, src/examples/chip-set/chip-set-input.tsx, src/examples/chip-set/chip-set.tsx, src/examples/picker/picker-multiple.tsx, src/examples/picker/picker.tsx
Required by Lundalogik/lime-webclient#1107
Windows:
Linux:
macOS:
Mobile:
=> Chipset required marker

package-lock.json, package.json, src/components/dialog/dialog.tsx, src/util/dispatch-resize-event.ts
Windows:
Linux:
macOS:
Mobile:
=> Greenkeeper/@stencil/core 1.5.3

Jenkinsfile, Makefile, publish-docs.js
Windows:
Linux:
macOS:
Mobile:
=> Update semantic release gh user

src/components/button/button.e2e.ts, src/components/chip-set/chip-set.e2e.ts, src/components/menu/menu.e2e.ts, src/components/select/select.e2e.ts, src/components/snackbar/snackbar.e2e.ts, src/components/switch/switch.e2e.ts
Windows:
Linux:
macOS:
Mobile:
=> test: unskip a bunch of e2e-tests

src/components/chip-set/chip-set.e2e.ts, src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/components/picker/picker.tsx
Based on #453. I would suggest reviewing and merging that one first, and then pointing this PR to master, before reviewing this. /Ads
fix #455 
Windows:
Linux:
macOS:
Mobile:
=> Fix hiding of input

src/components/chip-set/chip-set.e2e.ts, src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/components/picker/picker.tsx, src/examples/chip-set/chip-set-choice.tsx, src/examples/chip-set/chip-set-filter.tsx, src/examples/chip-set/chip-set-input.tsx, src/examples/picker/picker-empty-suggestions.tsx, src/examples/picker/picker-icons.tsx, src/examples/picker/picker-multiple.tsx, src/examples/picker/picker.tsx
fix #429
Windows:
Linux:
macOS:
Mobile:
=> fix(chip-set): fix incorrect look and behavior when input chip-set is disabled

src/components/snackbar/snackbar.e2e.ts
Windows:
Linux:
macOS:
Mobile:
=> test(snackbar): fix and unskip some tests

src/examples/chip-set/chip-set-input.tsx
Windows:
Linux:
macOS:
Mobile:
=> docs(chip-set): remove extraneous console.log statements

package-lock.json, package.json, src/components/icon/icon.mdx, src/examples/icon/icon-finder.tsx, tsconfig.dev.json, tsconfig.json
Windows:
Linux:
macOS:
Mobile:
=> docs(limel-icon): provide search for available icons

src/components/picker/picker.tsx
Windows:
Linux:
macOS:
Mobile:
=> feat(picker): no scroll in list when five or less items

publish-docs.js, release.config.js
=> Enable docs publish

src/components/grid/grid.scss
Some breaking changes, but I think it's fairly unlikely that anyone is actually affected by them. Still, please see the individual commit messages for more info.
Windows:
Linux:
macOS:
Mobile:
=> Update grid config

Dockerfile
Windows:
Linux:
macOS:
Mobile:
=> chore(dockerfile): print out node and npm version

src/components/banner/banner.tsx, src/components/collapsible-section/collapsible-section.tsx, src/components/dialog/dialog.tsx, src/components/flex-container/flex-container.tsx, src/components/grid/grid.tsx, src/components/menu-surface/menu-surface.tsx, src/components/menu/menu.tsx, src/components/portal/portal.tsx
Windows:
Linux:
macOS:
Mobile:
=> docs: add slot documentation

src/components/dialog/dialog.scss, src/components/dialog/dialog.tsx, src/examples/dialog/dialog-size.tsx
fix #312
Windows:
Linux:
macOS:
Mobile:
=> feat(dialog): indicate scrollable content via a shadow

src/examples/select/select.tsx
Windows:
Linux:
macOS:
Mobile:
=> docs(limel-select): include a disabled option

src/components/list/list-renderer.tsx, src/components/list/list.e2e.ts
Connected to #538 
Windows:
Linux:
macOS:
Mobile:
=> fix(list): update template for single line list items

.github/workflows/pr-checks.yml
Windows:
Linux:
macOS:
Mobile:
=> chore(github actions): switch from forked workflows to parents

package-lock.json, package.json, src/components/form/form.mdx, src/components/form/form.tsx, src/components/form/templates/array-field.ts, src/components/form/templates/field.ts, src/components/form/templates/index.ts, src/components/form/templates/object-field.ts, src/components/form/widgets/index.ts, src/examples/form/dynamic-form.scss, src/examples/form/dynamic-form.tsx, src/examples/form/form.tsx, stencil.config.dist.ts, stencil.config.docs.ts, stencil.config.ts
Connected to Lundalogik/crm-feature#947
Windows:
Linux:
macOS:
Mobile:
=> feat(form): first basic version of form component (unreleased)

src/components/select/select.e2e.ts, src/components/select/select.scss, src/components/select/select.template.tsx, src/components/select/select.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(select): make select work on mobile devices again

src/components/date-picker/date-picker.tsx, src/components/form/widgets/date-picker.ts, src/components/form/widgets/index.ts, src/examples/form/form.tsx
Connected to Lundalogik/crm-feature#947
Windows:
Linux:
macOS:
Mobile:
=> limel-date-picker for limel-form

src/components/date-picker/date-picker.tsx, src/components/form/widgets/date-picker.ts, src/components/form/widgets/index.ts, src/components/form/widgets/select.ts, src/components/select/select.scss, src/components/select/select.template.tsx, src/components/select/select.tsx, src/examples/form/form.tsx, src/examples/select/select.tsx, tslint.js
Connected to Lundalogik/crm-feature#947
Windows:
Linux:
macOS:
Mobile:
=> limel-select for limel-form

src/components/checkbox/checkbox.scss, src/components/checkbox/checkbox.template.tsx, src/components/checkbox/checkbox.tsx, src/components/date-picker/date-picker.tsx, src/components/form/widgets/checkbox.ts, src/components/form/widgets/date-picker.ts, src/components/form/widgets/index.ts, src/components/form/widgets/select.ts, src/components/select/select.scss, src/components/select/select.template.tsx, src/components/select/select.tsx, src/examples/checkbox/checkbox.tsx, src/examples/form/form.tsx, src/examples/select/select.tsx, tslint.js
Connected to Lundalogik/crm-feature#947 
Windows:
Linux:
macOS:
Mobile:
=> limel-checkbox for limel-form

src/components/checkbox/checkbox.scss, src/components/checkbox/checkbox.template.tsx, src/components/checkbox/checkbox.tsx, src/components/date-picker/date-picker.tsx, src/components/form/widgets/checkbox.ts, src/components/form/widgets/date-picker.ts, src/components/form/widgets/index.ts, src/components/form/widgets/input-field.ts, src/components/form/widgets/select.ts, src/components/input-field/input-field.tsx, src/components/input-field/input-field.types.ts, src/components/select/select.scss, src/components/select/select.template.tsx, src/components/select/select.tsx, src/examples/checkbox/checkbox.tsx, src/examples/form/form.tsx, src/examples/input-field/input-field-text.tsx, src/examples/select/select.tsx, src/interface.d.ts, tslint.js
Connected to Lundalogik/crm-feature#947
Windows:
Linux:
macOS:
Mobile:
=> limel-input-field for limel-form

package-lock.json, package.json, tslint.js
Windows:
Linux:
macOS:
Mobile:
=> update jsx-dom and tslint

src/components/form/form.tsx, src/components/form/form.types.ts, src/components/form/templates/field.ts, src/components/form/widgets/date-picker.ts, src/components/select/select.scss, src/examples/form/form.tsx, src/interface.d.ts
Windows:
Linux:
macOS:
Mobile:
=> Limel form validation

src/components/collapsible-section/action.ts, src/components/collapsible-section/collapsible-section.mdx, src/components/collapsible-section/collapsible-section.scss, src/components/collapsible-section/collapsible-section.tsx, src/components/form/form.mdx, src/components/form/form.scss, src/components/form/form.tsx, src/components/form/schema.ts, src/components/form/templates/array-field-collapsible-item.ts, src/components/form/templates/array-field-simple-item.ts, src/components/form/templates/array-field.ts, src/components/form/templates/common.spec.ts, src/components/form/templates/common.ts, src/components/form/templates/object-field.ts, src/components/form/templates/types.ts, src/components/form/widgets/input-field.ts, src/components/select/select.scss, src/examples/collapsible-section/collapsible-section-actions.tsx, src/examples/form/list-form.tsx, src/interface.d.ts, src/style/variables.scss, stencil.config.ts
fix Lundalogik/crm-feature#962
Windows:
Linux:
macOS:
Mobile:
=> feat(form): add component for array items

src/components/collapsible-section/collapsible-section.mdx, src/components/collapsible-section/collapsible-section.scss, src/examples/collapsible-section/collapsible-section-css-props.tsx, src/examples/collapsible-section/collapsible-section-external-control.tsx, src/examples/collapsible-section/collapsible-section-with-slider.tsx, src/examples/collapsible-section/collapsible-section.scss, src/examples/collapsible-section/collapsible-section.tsx
re Lundalogik/crm-feature#968
Windows:
Linux:
macOS:
Mobile:
=> feat(collapsible-section): background-color and padding can now be set using CSS variables

src/components/select/select.scss, src/components/select/select.template.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(select): show arrow in the dropdown

src/components/form/form.mdx, src/components/form/form.tsx, src/components/form/widgets/select.ts, src/examples/form/dynamic-form.tsx, stencil.config.dist.ts, stencil.config.docs.ts
Windows:
Linux:
macOS:
Mobile:
=> fix(form): set unique id in schema

src/components/form/widgets/adapter.ts, src/components/form/widgets/input-field.ts
Windows:
Linux:
macOS:
Mobile:
=> Limel form improve validation

src/components/input-field/input-field.mdx, src/components/input-field/input-field.tsx, src/examples/input-field/input-field-error-icon.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(text-field): show error icon

src/components/input-field/input-field.mdx, src/components/input-field/input-field.scss, src/components/input-field/input-field.tsx, src/components/input-field/input-field.types.ts, src/examples/input-field/input-field-textarea.tsx, src/examples/input-field/input-field.scss
Windows:
Linux:
macOS:
Mobile:
=> feat(input-field): add support for textarea

src/components/input-field/input-field.tsx, src/examples/dialog/dialog-form.tsx
fix Lundalogik/crm-feature#974
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field-number): blurred onWheel event on input field

src/components/menu-surface/menu-surface.scss, src/components/menu-surface/menu-surface.tsx, src/components/picker/picker.scss, src/components/picker/picker.tsx, src/components/spinner/spinner.scss
fix Lundalogik/crm-feature#971
Windows:
Linux:
macOS:
Mobile:
=> fix(limel-picker): render picker dropdown in document.body

publish-docs.js, release.config.js
=> ci(docz): remove publishing of docs to aws, we now use a separate github action

src/components/config/config.tsx, src/global/config.ts
Connected to Lundalogik/crm-feature#983
Windows:
Linux:
macOS:
Mobile:
=> feat(config): add feature switches to config object

src/components/checkbox/checkbox.template.tsx
fix #564
Windows:
Linux:
macOS:
Mobile:
=> fix(checkbox): add ripple for indication of element focus

package-lock.json, package.json, src/examples/example.scss, src/examples/example.tsx, src/examples/props.tsx
Windows:
Linux:
macOS:
Mobile:
=> Code only examples

src/components/tab-bar/tab-bar.tsx
If new tabs are added after the tab-bar has been created, it was not possible to select any of the
new tabs. This fix re-creates the mdc-instance if new tabs are added to the list
Windows:
Linux:
macOS:
Mobile:
=> switched(tab-bar): re-create mdc-instance when new tabs are added

src/components/tab-panel/tab-panel.tsx
Windows:
Linux:
macOS:
Mobile:
=> switched(tab-panel): make sure element exists before setting a style on it

package.json
This reverts commit 8a3e4fb39a8a48c4a1da8325cc5fd3590646a1d9 from #633.
=> Remove obsolete fix for dev-build

src/components/tab-bar/tab-bar.scss
fix Lundalogik/lime-elements#659
Windows:
Linux:
macOS:
Mobile:
=> fix(tab-bar): style icon in tab bar

src/components/list/examples/list-action.tsx, src/components/list/list-item.types.ts, src/components/list/list-renderer.tsx, src/components/list/list.e2e.ts, src/components/list/list.mdx, src/components/list/list.scss, src/components/list/list.tsx, src/components/list/list.types.ts, src/components/menu-surface/menu-surface.scss, src/components/menu-surface/menu-surface.tsx, src/components/menu/examples/menu.tsx, src/components/menu/menu.e2e.ts, src/components/menu/menu.scss, src/components/menu/menu.tsx, src/components/menu/menu.types.ts, src/components/picker/picker.tsx, src/components/portal/portal.tsx, src/components/select/select.template.tsx, src/interface.d.ts
fix Lundalogik/crm-feature#989
Windows:
Linux:
macOS:
Mobile:
=> Action menu on list items

src/components/input-field/input-field.tsx
fix Lundalogik/lime-elements#276
Windows:
Linux:
macOS:
Mobile:
=> add keyboard support for autocomplete on input-field

src/components/list/list.scss, src/style/mixins.scss
Now list items are more distinct on white backgrounds of the new tabs; also they are more interactive and have animations and effects on hover.
=> Adapt lists to new tabs

package.json, tslint.config.js
=> chore(lint): apply rules in tslint.config.js only to files in project root

package-lock.json, package.json
=> chore(package): update tslint to v6.1.1

src/components/form/templates/array-field-collapsible-item.ts
re Lundalogik/crm-feature#1057
Windows:
Linux:
macOS:
Mobile:
=> fix: prevent argument mismatching in case of value being an array

src/components/list/examples/list-action.tsx, src/components/list/list-item.types.ts, src/components/list/list-renderer.tsx, src/components/list/list.e2e.ts, src/components/list/list.mdx, src/components/list/list.scss, src/components/list/list.tsx, src/components/list/list.types.ts, src/components/menu/examples/menu.tsx, src/components/menu/menu.e2e.ts, src/components/menu/menu.scss, src/components/menu/menu.tsx, src/components/menu/menu.types.ts, src/components/portal/portal.tsx, src/interface.d.ts
Connected to: Lundalogik/crm-feature#989
Windows:
Linux:
macOS:
Mobile:
=> Action menu on list items (again)

CONTRIBUTING.md
Windows:
Linux:
macOS:
Mobile:
=> docs(contributing.md): improve the description for commit type `refactor`

package-lock.json, package.json, src/components/menu-surface/menu-surface.tsx, src/components/menu/examples/menu.tsx, src/components/portal/portal.tsx, src/index.html
resolves https://github.com/Lundalogik/crm-feature/issues/1069
Things to do before merge:
Windows:
Linux:
macOS:
Mobile:
=> Use popperjs in limel-portal for positioning

src/components/picker/picker.tsx
Fix Lundalogik/crm-feature#1019
Windows:
Linux:
macOS:
Mobile:
=> Fix focus chipset

src/components/menu/examples/menu.tsx, src/components/menu/menu.scss, src/components/menu/menu.tsx, src/components/portal/portal.tsx
connected to Lundalogik/crm-feature#1094
Windows:
Linux:
macOS:
Mobile:
=> Fixed menu position

src/components/icon-button/examples/icon-button-elevated.tsx, src/components/icon-button/icon-button.mdx, src/components/icon-button/icon-button.scss, src/components/icon-button/icon-button.tsx, src/components/icon/icon.scss, src/components/tab-bar/tab-bar.scss, src/components/tab-bar/tab-bar.tsx
fix Lundalogik/crm-feature#1022
Windows:
Linux:
macOS:
Mobile:
=> feat(tab-bar): add buttons when bar can be scrolled 

src/components/input-field/examples/input-field-search.tsx, src/components/input-field/input-field.mdx, src/components/input-field/input-field.tsx, src/components/tab-bar/tab-bar.tsx
fix: Lundalogik/crm-feature#1109
Windows:
Linux:
macOS:
Mobile:
=> Search input field

src/components/chip-set/chip-set.scss, src/components/input-field/input-field.scss, src/components/select/select.scss, src/style/internal/shared_input-select-picker.scss, src/style/internal/variables.scss
fix: https://github.com/Lundalogik/lime-elements/issues/754
fix: https://github.com/Lundalogik/lime-elements/issues/728
Windows:
Linux:
macOS:
Mobile:
=> Unify input field layouts

src/components/table/table.tsx
Windows:
Linux:
macOS:
Mobile:
=> chore(table): change name of feature switch

src/components/table/partial-styles/tabulator-arrow.scss, src/components/table/table.scss
fix: https://github.com/Lundalogik/lime-elements/issues/806
Windows:
Linux:
macOS:
Mobile:
=> Style table

src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/style/mixins.scss, src/style/shadows.scss
Windows:
Linux:
macOS:
Mobile:
=> Chips with icons-only or text-only

src/components/tab-bar/tab-bar.scss, src/components/tab-panel/examples/tab-panel.scss, src/components/tab-panel/tab-panel.scss, src/components/tab-panel/tab-panel.tsx
fix Lundalogik/crm-feature#1141
Windows:
Linux:
macOS:
Mobile:
=> feat(tab-panel): make it possible to scroll inside the content of a tab

package-lock.json, package.json, src/components/date-picker/date-picker.scss, src/components/date-picker/pickers/DatePicker.ts, src/components/date-picker/pickers/DatetimePicker.ts, src/components/date-picker/pickers/MonthPicker.tsx, src/components/date-picker/pickers/Picker.ts, src/components/date-picker/pickers/QuarterPicker.tsx, src/components/date-picker/pickers/TimePicker.ts, src/components/date-picker/pickers/WeekPicker.ts, src/components/date-picker/pickers/YearPicker.tsx
Windows:
Linux:
macOS:
Mobile:
=> chore(date-picker): use official flatpickr package instead of fork

src/components/table/examples/table-local.tsx, src/components/table/examples/table-remote.tsx, src/components/table/table.mdx, src/components/table/table.tsx, src/components/table/table.types.ts
fix Lundalogik/crm-feature#1145
Windows:
Linux:
macOS:
Mobile:
=> feat(table): add local and remote pagination support

src/components/table/columns.ts, src/components/table/examples/table-local.tsx, src/components/table/examples/table-remote.tsx, src/components/table/examples/table.scss, src/components/table/table.types.ts
requires #830
Windows:
Linux:
macOS:
Mobile:
=> switched(table): add support for aggregations

src/components/table/examples/table-low-density.tsx, src/components/table/examples/table.tsx, src/components/table/partial-styles/tabulator-custom-styles.scss, src/components/table/table.mdx, src/components/table/table.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1149
Windows:
Linux:
macOS:
Mobile:
=> Feat low density table

src/components/table/table.mdx
Windows:
Linux:
macOS:
Mobile:
=> docs(table): add examples removed by mistake

src/components/button-group/button-group.e2e.ts, src/components/button-group/button-group.mdx, src/components/button-group/button-group.scss, src/components/button-group/button-group.tsx, src/components/button-group/examples/button-group-icons.tsx, src/components/button-group/examples/button-group-mix.tsx, src/components/button-group/examples/button-group.tsx, src/components/button/button.types.ts, src/interface.d.ts, src/style/shadows.scss
fix #795 
PR for using the button in crm-components: Lundalogik/lime-crm-components#99
Windows:
Linux:
macOS:
Mobile:
=> feat(button-group): add component

src/components/table/partial-styles/tabulator-paginator.scss, src/components/table/table.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1197
Windows:
Linux:
macOS:
Mobile:
=> fix(tablulator-paginator): style paginators

src/components/table/table.tsx
Windows:
Linux:
macOS:
Mobile:
=> feat(table): set default layout to fitColumns

.github/workflows/pr-checks.yml
=> ci(pr-checks): build docz-app in CI build

src/components/table/table.scss, src/components/table/table.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/1200
Windows:
Linux:
macOS:
Mobile:
=> fix(table): cells won't grow over specified max-width

src/components/slider/slider.scss
fix: https://github.com/Lundalogik/lime-elements/issues/626
More aligned with other fields, More interactive, more compact, more user friendly, and more beautiful ;)
Windows:
Linux:
macOS:
Mobile:
=> fix(slider): redesign the slider

src/components/input-field/input-field.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1210
Windows:
Linux:
macOS:
Mobile:
=> fix(input): style the inbuilt clear search button

src/components/table/table.mdx, src/components/table/table.tsx
resolves #844
Windows:
Linux:
macOS:
Mobile:
=> fix(table): remove feature-switch for table component

src/style/shadows.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1192
Windows:
Linux:
macOS:
Mobile:
=> feat(shadows): add shadow variable for bottom bars

src/components/portal/portal.tsx
Windows:
Linux:
macOS:
Mobile:
=> Portal fixes

src/components/input-field/input-field.tsx, src/components/picker/picker.tsx, src/components/switch/switch.tsx
Stencil has been throwing warnings in the console for a while. This should fix some of them :slightly_smiling_face: 
Windows:
Linux:
macOS:
Mobile:
=> Fix Stencil warnings

src/components/date-picker/date-picker.tsx
Windows:
Linux:
macOS:
Mobile:
=> improve handling of click on datepicker input field

src/components/slider/slider.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1223
Windows:
Linux:
macOS:
Mobile:
=> fix(slider): properly style disabled slider's thumb

src/components/tab-bar/examples/tab-bar-with-dynamic-tab-width.tsx, src/components/tab-bar/examples/tab-bar-with-equal-tab-width.tsx, src/components/tab-bar/tab-bar.mdx, src/components/tab-bar/tab-bar.scss
fix: https://github.com/Lundalogik/lime-elements/issues/827
Windows:
Linux:
macOS:
Mobile:
=> Feat tabs width

tsconfig.dev.json, tsconfig.docs.json, tsconfig.lint.json
Windows:
Linux:
macOS:
Mobile:
=> refactor(tsconfig): extend from base config

src/components/table/table.tsx
re Lundalogik/crm-feature#1292
Windows:
Linux:
macOS:
Mobile:
=> perf(table): don't set data on Tabulator unless it has changed

src/global/core-styles.scss
Windows:
Linux:
macOS:
Mobile:
=> feat(core-styles): let color palette be exported & accessible in client

src/components/checkbox/checkbox.tsx, src/components/form/form.tsx, src/components/icon-button/icon-button.tsx, src/components/menu-surface/menu-surface.tsx, src/components/portal/portal.tsx
Windows:
Linux:
macOS:
Mobile:
=> Fix error messages

src/components/switch/switch.tsx
Fix Lundalogik/crm-feature#1289
Windows:
Linux:
macOS:
Mobile:
=> fix(switch): make sure MDC component exist

src/components/chip-set/chip-set.e2e.ts, src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx
fix Lundalogik/crm-feature#1329
Windows:
Linux:
macOS:
Mobile:
=> feat(chip-set): add delete all chips button

src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx
Windows:
Linux:
macOS:
Mobile:
=> refactor(chip-set): change name of css class `chips-exists` to `has-chips`

src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/components/chip-set/examples/chip-set-input.tsx, src/components/input-field/input-field.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1341
fix: https://github.com/Lundalogik/crm-feature/issues/1302
Windows:
Linux:
macOS:
Mobile:
=> Add leading search icon to chips input

.github/workflows/pr-checks.yml
Windows:
Linux:
macOS:
Mobile:
=> ci(pr-checks): use wagoid/commitlint-github-action@v2

src/components/chip-set/chip-set.e2e.ts, src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/components/input-field/input-field.scss, src/style/mixins.scss
fix #936 
Windows:
Linux:
macOS:
Mobile:
=> Fix usability of clear all chips button

src/components/tab-panel/tab-panel.tsx, src/components/table/table.scss, src/components/table/table.tsx
Windows:
Linux:
macOS:
Mobile:
=> Tab table bugfixes

src/components/input-field/examples/input-field-textarea.tsx, src/components/input-field/input-field.tsx
fix #952 
Windows:
Linux:
macOS:
Mobile:
=> Textarea bug

src/components/file/examples/file.tsx, src/components/file/file.mdx, src/components/file/file.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/1064
This will improve the component for now, but this component should be totally re-designed!
Windows:
Linux:
macOS:
Mobile:
=> Fix improve usability of file picker

package-lock.json, package.json, src/components/form/fields/schema-field.ts, src/components/table/table.types.ts
Windows:
Linux:
macOS:
Mobile:
=> Update node modules

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> chore(kompendium): update to new version

src/components/form/examples/form-layout.tsx, src/components/form/examples/schema-layout.ts, src/components/form/form.scss, src/components/form/form.tsx, src/components/form/form.types.ts, src/components/form/templates/field.ts, src/components/form/templates/object-field.ts
fix Lundalogik/crm-feature#1479
Windows:
Linux:
macOS:
Mobile:
=> Form layout

src/components/form/form.tsx, src/components/form/widgets/input-field.ts
fix Lundalogik/crm-feature#1528
Windows:
Linux:
macOS:
Mobile:
=> Form input field custom props

src/components/table/table.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/1450
Tabulator requires that the html element it's rendered inside
has a size before it's created, otherwise it doesn't consider
it self renderedy completely. (the callback "renderComplete"
is never run).
Windows:
Linux:
macOS:
Mobile:
=> fix(table): ensure component is completely rendered when loaded

src/components/form/examples/schema.ts, src/components/form/widgets/index.ts, src/components/form/widgets/input-field.ts, src/components/form/widgets/slider.ts, src/components/slider/slider.scss, src/components/slider/slider.tsx
fix Lundalogik/crm-feature#1570
Windows:
Linux:
macOS:
Mobile:
=> Form slider

src/components/slider/slider.tsx
fix Lundalogik/crm-feature#1532
Windows:
Linux:
macOS:
Mobile:
=> fix(slider): ensure no error log is thrown in the console

src/components/input-field/input-field.tsx, src/components/linear-progress/linear-progress.tsx, src/components/list/list.tsx, src/components/table/table.tsx
Windows:
Linux:
macOS:
Mobile:
=> Fix watchers

src/components/slider/slider.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1578
Windows:
Linux:
macOS:
Mobile:
=> Keep sliders content inside boundaries of its container

src/components/button/button.scss, src/components/button/examples/button.scss, src/components/button/examples/button.tsx
=> Allow set limel-button size

src/components/input-field/examples/input-field-icon-both.tsx, src/components/input-field/examples/input-field-icon-leading.tsx, src/components/input-field/examples/input-field-icon-trailing.tsx, src/components/input-field/input-field.tsx
The commit `fix(input-field): do not trigger action from leadingIcon` could be considered breaking. It could also be considered to just be a bugfix that's only breaking if someone has exploited that bug to do something we never intended. But I'm not entirely sure that's fair, because I'm not entirely sure we never intended the leading icon to trigger actions… Opinions welcome!
Windows:
Linux:
macOS:
Mobile:
=> Input field refactor and bugfixes

src/components/form/widgets/date-picker.ts
fix Lundalogik/crm-feature#1584
Windows:
Linux:
macOS:
Mobile:
=> feat(form): add support for different types of date-pickers

src/components/tab-bar/tab-bar.tsx
fix Lundalogik/crm-feature#1504
Windows:
Linux:
macOS:
Mobile:
=> fix(tab-bar): update scroll-buttons when window is resized

src/components/icon/examples/icon-finder.tsx
fix: Lundalogik/crm-feature#1439
Windows:
Linux:
macOS:
Mobile:
=> docs(limel-icon): add leading icon for search available icons

src/components/banner/banner.tsx, src/components/button/button.tsx, src/components/button/examples/button.tsx, src/components/checkbox/checkbox.tsx, src/components/collapsible-section/collapsible-section.tsx, src/components/date-picker/date-picker.tsx, src/components/date-picker/flatpickr-adapter/flatpickr-adapter.tsx, src/components/dialog/dialog.tsx, src/components/file/file.tsx, src/components/icon-button/icon-button.tsx, src/components/input-field/input-field.tsx, src/components/menu/menu.tsx, src/components/portal/portal.tsx, src/components/select/select.tsx
Windows:
Linux:
macOS:
Mobile:
=> Docs cleanup + some tiny other cleanups

src/components/icon/examples/icon-finder.tsx, src/components/icon/icon.tsx
Windows:
Linux:
macOS:
Mobile:
=> Move icon finder in docs

src/components/table/examples/table-low-density.tsx
Windows:
Linux:
macOS:
Mobile:
=> docs(table):  fix a typo

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> chore: update Kompendium

src/components/collapsible-section/collapsible-section.scss, src/components/collapsible-section/collapsible-section.tsx, src/components/collapsible-section/examples/collapsible-section-actions.tsx, src/components/collapsible-section/examples/collapsible-section-with-slider.tsx, src/components/collapsible-section/examples/collapsible-section.scss, src/components/collapsible-section/partial-styles/expand-icon.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1447
Windows:
Linux:
macOS:
Mobile:
=> Improve collapsible sections design

src/components/chip-set/examples/chip-set-input.scss, src/components/icon/examples/icon-finder.tsx, src/components/linear-progress/examples/linear-progress-color.tsx, src/components/tab-panel/examples/tab-panel.tsx, src/components/tab-panel/tab-panel.tsx, src/components/table/examples/table-default-sorted.tsx
Windows:
Linux:
macOS:
Mobile:
=> Five simple improvements to the docs

src/components/form/examples/dynamic-form.scss, src/components/input-field/examples/input-field-textarea.tsx, src/components/input-field/input-field.scss, src/components/input-field/input-field.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/1614
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): hide character counter when not needed & more

src/components/form/examples/form.tsx, src/components/form/form.tsx
Windows:
Linux:
macOS:
Mobile:
=> docs for limel-form: fix typo and add a "name" to the first example so the console output is easier to understand

src/components/form/widgets/date-picker.ts
fix Lundalogik/crm-feature#1643
Windows:
Linux:
macOS:
Mobile:
=> fix(form): emit undefined from date-picker when cleared

src/components/select/select.tsx
fix Lundalogik/crm-feature#1691
Windows:
Linux:
macOS:
Mobile:
=> fix(select): remove unused line ripple

src/components/form/widgets/date-picker.ts
fix Lundalogik/crm-feature#1690
Windows:
Linux:
macOS:
Mobile:
=> fix(date-picker): add timezone to date-time format type

src/decluttering.md
Windows:
Linux:
macOS:
Mobile:
=> docs(decluttering): improve information

src/components/chip-set/chip-set.tsx, src/components/chip-set/chip.types.ts, src/components/file/examples/file-custom-icon.tsx, src/components/file/examples/file.tsx, src/components/file/file.scss, src/components/file/file.tsx, src/components/file/file.types.ts
Windows:
Linux:
macOS:
Mobile:
closing #1059
=> feat(limel-file): support custom icon and icon-color

package-lock.json, package.json
close: #1087
close: #1042
Windows:
Linux:
macOS:
Mobile:
=> chore(package): update semantic-release to v17.3.1

src/components/table/columns.spec.ts, src/components/table/columns.ts, src/components/table/examples/header-menu.tsx, src/components/table/examples/table-header-menu.tsx, src/components/table/partial-styles/header-component.scss, src/components/table/table.scss, src/components/table/table.tsx, src/components/table/table.types.ts, src/style/mixins.scss
fix: Lundalogik/crm-feature#1749
Windows:
Linux:
macOS:
Mobile:
=> add a support for having action buttons inside the column header

src/components/popover-surface/popover-surface.scss, src/components/popover-surface/popover-surface.tsx, src/components/popover/examples/popover.scss, src/components/popover/examples/popover.tsx, src/components/popover/popover.scss, src/components/popover/popover.spec.ts, src/components/popover/popover.tsx, src/components/portal/portal.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/1748
Windows:
Linux:
macOS:
Mobile:
=> Popover component

src/components/popover-surface/popover-surface.scss, src/components/popover-surface/popover-surface.tsx, src/components/popover/examples/popover.tsx, src/components/popover/popover.scss, src/components/popover/popover.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/1791
Windows:
Linux:
macOS:
Mobile:
=> fix(popover): remove unnecessary slots

src/components/header/examples/header-narrow.scss, src/components/header/examples/header-narrow.tsx, src/components/header/examples/header-responsive.scss, src/components/header/examples/header-responsive.tsx, src/components/header/examples/header.scss, src/components/header/examples/header.tsx, src/components/header/header.scss, src/components/header/header.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/1761
Windows:
Linux:
macOS:
Mobile:
=> feat(header): add header component

src/components/file/file.tsx
fix Lundalogik/crm-feature#1777
Windows:
Linux:
macOS:
Mobile:
=> feat(file): dispatch interact event when clicking on a chip

src/components/button/button.tsx, src/components/button/examples/button-colors.scss, src/components/button/examples/button-colors.tsx
Windows:
Linux:
macOS:
Mobile:
=> docs(button): describe how to color buttons and their labels

package-lock.json
Windows:
Linux:
macOS:
Mobile:
=> chore(package-lock.json): update after `npm install` with npm v7.5

.github/workflows/pr-checks.yml
Windows:
Linux:
macOS:
Mobile:
=> update pr-checks.yml workflow to use node 14 and latest npm

src/components/checkbox/checkbox.scss, src/components/form/form.scss, src/components/switch/examples/switch.scss, src/components/switch/examples/switch.tsx, src/components/switch/switch.scss, src/style/internal/shared_input-select-picker.scss
fix Lundalogik/crm-feature#1629
Windows:
Linux:
macOS:
Mobile:
=> fix(form): vertically align switches and checkboxes

publish-docs.js
fix: #1098 
Windows:
Linux:
macOS:
Mobile:
=> chore(docs): publish docs on GitHub Pages instead of AWS

src/components/form/widgets/slider.ts, src/components/slider/examples/slider-multiplier-percentage-colors.tsx, src/components/slider/getPercentageClass.ts, src/components/slider/partial-styles/percentage-color.scss, src/components/slider/slider.scss, src/components/slider/slider.tsx
fix Lundalogik/crm-feature#1636
Windows:
Linux:
macOS:
Mobile:
=> feat(slider): color slider to visualize percentage value

package-lock.json, package.json
Update `tabulator-tables` from v4.8.2 to v4.9.3
See release notes here: http://tabulator.info/docs/4.9/release
Windows:
Linux:
macOS:
Mobile:
=> fix(table): the underlying library has been updated with many bugfixes and performance improvements

src/components/popover-surface/popover-surface.scss, src/components/popover-surface/popover-surface.tsx, src/components/popover/examples/popover.tsx, src/components/popover/popover.scss, src/components/popover/popover.spec.ts, src/components/popover/popover.tsx
fix: Lundalogik/crm-feature#1849
Windows:
Linux:
macOS:
Mobile:
=> Add trigger slot to popover

package-lock.json, package.json, src/components/icon/icon.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/1789
Windows:
Linux:
macOS:
Mobile:
=> docs(icon): explain how lime icons colors work

.github/workflows/cleanup.yml, .github/workflows/pr-checks.yml, .github/workflows/pr-comment.js, publish-docs.js
Windows:
Linux:
macOS:
Mobile:
=> Publish PR docs

src/components/date-picker/date.types.ts, src/global/translations.ts, src/translations/nl.ts
Adds lang nl.
(this was cherry picked from https://github.com/Lundalogik/lime-elements/pull/1153)
A review of these translations has been posted to the Translation help Teams channel.
=> Add Dutch language

.github/workflows/pr-checks.yml, publish-docs.js, release.config.js
Windows:
Linux:
macOS:
Mobile:
=> Publish docs for PRs again!

src/components/picker/picker.tsx
fix Lundalogik/lime-elements#865
Windows:
Linux:
macOS:
Mobile:
=> fix(picker): listen to dismiss events from the menu to know when to close it

src/components/table/examples/table-movable-columns.tsx, src/components/table/partial-styles/movable-columns.scss, src/components/table/partial-styles/tabulator-arrow.scss, src/components/table/table.scss, src/components/table/table.tsx
fix Lundalogik/crm-feature#1863
Windows:
Linux:
macOS:
Mobile:
=> feat(table): enable movable columns

src/components/input-field/input-field.scss, src/components/input-field/input-field.tsx, src/components/portal/portal.tsx
fix Lundalogik/lime-elements#1115
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): when using autocompletions, make it possible to close the dropdown

package-lock.json, package.json
fix Lundalogik/crm-feature#1889
Windows:
Linux:
macOS:
Mobile:
=> feat(package): update @lundalogik/lime-icons8 to V2.4.0

src/components/input-field/examples/input-field.scss, src/components/input-field/partial-styles/trailing-icon.scss
by giving their trailing icons which is clickable, a subtle visual effect
https://user-images.githubusercontent.com/35954987/110784689-43c41400-826a-11eb-979d-e760a47b80fa.mp4
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): fix add more meaning and delight to input type `tel` & `url`

src/components/button-group/button-group.scss, src/style/internal/z-index-variables.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1963
Windows:
Linux:
macOS:
Mobile:
=> (re)enable keyboard navigation for button groups

src/components/picker/picker.tsx
fix Lundalogik/crm-feature#1974
Windows:
Linux:
macOS:
Mobile:
=> fix(picker): focus chipset when emptying multiple picker as well

package-lock.json, package.json, src/components/button/button.tsx, src/components/button/examples/button-basic.tsx, src/components/button/examples/button-composite.scss, src/components/button/examples/button-composite.tsx, src/components/button/examples/button-disabled.tsx, src/components/button/examples/button-icon.tsx, src/components/button/examples/button-loading.tsx, src/components/button/examples/button-outlined.tsx, src/components/button/examples/button-primary.tsx, src/components/icon-button/examples/icon-button-disabled.tsx, src/components/icon-button/icon-button.tsx, src/examples/example-event-printer.scss, src/examples/example-event-printer.tsx, src/examples/example-value.tsx
See the commit messages.
Windows:
Linux:
macOS:
Mobile:
=> Make some improvements to the docs 😁

src/components/list/examples/list-badge-icons-with-multiple-lines.tsx, src/components/list/examples/list-striped.tsx, src/components/list/list.scss, src/components/list/list.tsx, src/components/list/partial-styles/custom-styles.scss, src/components/list/partial-styles/enable-multiline-text.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1212
Windows:
Linux:
macOS:
Mobile:
=> chore(list): move custom styles in a separate file

src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/components/chip-set/chip.types.ts, src/components/chip-set/examples/chip-set-filter-badge.tsx
fix Lundalogik/crm-feature#2002
Windows:
Linux:
macOS:
Mobile:
=> feat(chip-set): add badge to filter chip-set

.github/workflows/release.yml, publish-docs.js
Windows:
Linux:
macOS:
Mobile:
=> ci(release.yml): hopefully fix publishing of docs for new release

src/components/checkbox/checkbox.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(checkbox): better visualize keyboard navigation

src/components/status-flow/examples/status-flow-basic.tsx, src/components/status-flow/examples/status-flow-colors.tsx, src/components/status-flow/examples/status-flow-deal.tsx, src/components/status-flow/examples/status-flow-end-steps.tsx, src/components/status-flow/status-flow-item/status-flow-item.e2e.tsx, src/components/status-flow/status-flow-item/status-flow-item.scss, src/components/status-flow/status-flow-item/status-flow-item.tsx, src/components/status-flow/status-flow.e2e.ts, src/components/status-flow/status-flow.scss, src/components/status-flow/status-flow.tsx, src/components/status-flow/status-flow.types.ts
Windows:
Linux:
macOS:
Mobile:
=> feat: Status Flow component

src/components/switch/examples/switch.tsx, src/components/switch/partial-styles/_readonly.scss, src/components/switch/switch.scss, src/components/switch/switch.tsx
Windows:
Linux:
macOS:
Mobile:
=> feat(switch): make readonly & disabled visually distinct

src/components/table/table.scss, src/components/table/table.tsx
This PR attempts to fix issues with the load event being dispatched but new data is never set resulting in an infinite loader. Each commit solves the problem a little bit more. The end result works quite well imo. 
**Problems:**
- Tabulator is far to liberal with dispatching requests
- Some load events are not handled, resulting in infinite loaders while tabulator waits for new data
- The mixture of reactive and imperative programming causes a lot of hard handle nicely edge cases.
**Solution:**
Move functionality away from Tabulator. Treat tabulator and limel-table like a dumb component. Because tabluator is a smart component and saves state, we cant reallllllly make limel-table a dumb component, but by moving loading state outside of tabulator and into limel-table as a prop, we can …
=> fix(table): dont update columns if they match the existing table columns

src/components/select/examples/select.tsx, src/components/select/select.scss, src/components/select/select.template.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/2166
Windows:
Linux:
macOS:
Mobile:
=>  fix(select): better visualize invalid state

package-lock.json, package.json, src/components/color-system/examples/colors-in-components.scss, src/components/color-system/examples/lime-color-palette.scss, src/components/color-system/examples/shared-styles.scss, src/components/input-field/examples/input-field-text-decluttering-guidelines.scss, src/components/input-field/examples/input-field-text-decluttering-guidelines.tsx, src/components/shadows/examples/shadow-examples.scss, src/components/shadows/examples/surface-shadows-bad-usage.scss, src/components/size/examples/size-edge-case.scss, src/components/size/examples/size.scss, src/decluttering.md, src/examples/example-value.scss
Windows:
Linux:
macOS:
Mobile:
=> package(feat): upgrade Kompendium from v0.7.3 to v0.8.7

package-lock.json
Windows:
Linux:
macOS:
Mobile:
=> chore(package): updates made by `npm audit fix`

publish-docs.js, src/favicon.svg, src/index.html, stencil.config.docs.ts, stencil.config.ts
@adrianschmidt I was trying to add a favicon for lime elements, 
but don't know:
- how to link it properly, currently I don't see any favicon and tried different paths, but no success in seeing it in the browser 
- what to call the commit 
It'd be nice if you get a chance to look at this some day
Windows:
Linux:
macOS:
Mobile:
=> docs: add favicon

package-lock.json, package.json
fix Lundalogik/crm-feature#2248
Windows:
Linux:
macOS:
Mobile:
=> docs: make sure example code is updated

src/components/switch/partial-styles/_readonly.scss, src/components/switch/switch.scss, src/components/switch/switch.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(switch): make the structure more like the latest MDC & make disabled look disabled

src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/components/chip-set/partial-styles/_file-picker.scss, src/components/chip-set/partial-styles/_readonly.scss, src/components/file/examples/file-composite.tsx, src/components/file/examples/file-custom-icon.tsx, src/components/file/examples/file.tsx, src/components/file/file.tsx, src/translations/da.ts, src/translations/en.ts, src/translations/fi.ts, src/translations/nl.ts, src/translations/no.ts, src/translations/sv.ts
fix: https://github.com/Lundalogik/crm-feature/issues/1800
Windows:
Linux:
macOS:
Mobile:
=> feat(file): add a visual dropzone

guides.ts, src/components/dialog/dialog.tsx, src/components/dialog/examples/dialog-action-buttons.scss, src/components/dialog/examples/dialog-action-buttons.tsx, src/design-guidelines/_generic-example-styles/_do-dont.scss, src/design-guidelines/action-buttons/action-buttons.md, src/design-guidelines/action-buttons/examples/action-buttons.scss, src/design-guidelines/action-buttons/examples/colors-do-dont.tsx, src/design-guidelines/action-buttons/examples/icon-color.tsx, src/design-guidelines/action-buttons/examples/labels-explicit.tsx, src/design-guidelines/action-buttons/examples/labels.tsx, src/design-guidelines/action-buttons/examples/placement.tsx, src/design-guidelines/action-buttons/examples/primary-secondary-reversed-colors.tsx, src/design-guidelines/action-buttons/examples/primary-secondary-reversed.tsx, src/design-guidelines/action-buttons/examples/primary-secondary.tsx, src/design-guidelines/action-buttons/examples/third-alternative.tsx, src/design-guidelines/shadows/examples/surface-shadows-bad-usage.scss, src/design-guidelines/shadows/examples/surface-shadows-bad-usage.tsx
fix https://github.com/Lundalogik/crm-feature/issues/2243
Windows:
Linux:
macOS:
Mobile:
=> docs(action-buttons): add guidelines regarding action button design conventions

package-lock.json, package.json, src/components/list/list.tsx
Windows:
Linux:
macOS:
Mobile:
=> chore(package): update eslint from v7.28.0 to v7.31.0

src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/components/picker/picker.tsx
fix https://github.com/Lundalogik/crm-feature/issues/2267
Windows:
Linux:
macOS:
Mobile:
=> feat(chip-set): allow "clear all" button to be optionally hidden

src/components/chip-set/chip-set.tsx, src/components/input-field/input-field.e2e.ts, src/components/input-field/input-field.tsx, src/components/picker/picker.tsx
fix Lundalogik/crm-feature#2268
Windows:
Linux:
macOS:
Mobile:
=> Tabbing in pickers

src/components/list/list-item.types.ts, src/components/list/list-renderer.tsx
fix Lundalogik/crm-feature#2271
Windows:
Linux:
macOS:
Mobile:
=> feat(list-item): adds list separator to list item actions types

src/components/table/columns.ts, src/components/table/examples/table-activate-row.tsx, src/components/table/examples/table-custom-components.tsx, src/components/table/examples/table-default-sorted.tsx, src/components/table/examples/table-header-menu.tsx, src/components/table/examples/table-local.tsx, src/components/table/examples/table-low-density.tsx, src/components/table/examples/table-movable-columns.tsx, src/components/table/examples/table-remote.tsx, src/components/table/examples/table.tsx, src/components/table/table.types.ts
fix: Lundalogik/crm-feature#2123
Windows:
Linux:
macOS:
Mobile:
=> Align numerical data

src/components/popover/popover.spec.ts, src/components/popover/popover.tsx
fix Lundalogik/crm-feature#2205
Windows:
Linux:
macOS:
Mobile:
=> fix(popover): emit close event when ESC is pressed

.github/workflows/pre-release.yml, .github/workflows/release.yml
Windows:
Linux:
macOS:
Mobile:
=> Update release workflow

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> feat(package): update @lundalogik/lime-icons8 from v2.4.0 to v2.5.0

publish-docs.js
fix: Lundalogik/crm-feature#1915
Windows:
Linux:
macOS:
Mobile:
=> ci(docs): fix new icons not being published when publishing docs

package-lock.json, package.json, src/components/chip-set/chip-set.scss, src/components/input-field/input-field.scss, src/components/list/list.scss, src/components/slider/slider.scss, src/components/snackbar/snackbar.scss, src/style/internal/lime-theme.scss, src/style/internal/lime-typography.scss
Windows:
Linux:
macOS:
Mobile:
=> Update lint-related node modules

.github/workflows/cleanup.yml, .github/workflows/pr-checks.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml
Windows:
Linux:
macOS:
Mobile:
=> ci: update npm version used in workflows from 7.6.0 to 7.23.0

src/components/chip-set/chip-set.scss
fix https://github.com/Lundalogik/crm-feature/issues/2270 
Windows:
Linux:
macOS:
Mobile:
=> fix(chip-set): improve visual feedback when selecting a chip with keyboard for deletion

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> update @lundalogik/lime-icons8 and some linting modules

src/components/circular-progress/circular-progress.scss, src/components/circular-progress/circular-progress.tsx, src/components/circular-progress/circular-progress.types.ts, src/components/circular-progress/examples/circular-progress-css-variables.scss, src/components/circular-progress/examples/circular-progress-css-variables.tsx, src/components/circular-progress/examples/circular-progress-percentage-colors.tsx, src/components/circular-progress/examples/circular-progress-props.tsx, src/components/circular-progress/examples/circular-progress-sizes.tsx, src/components/circular-progress/examples/circular-progress.scss, src/components/circular-progress/examples/circular-progress.tsx, src/components/circular-progress/partial-styles/_percentage-colors.scss, src/style/internal/z-index.scss
fix https://github.com/Lundalogik/crm-feature/issues/2338
Windows:
Linux:
macOS:
Mobile:
=> feat(circular-progress): add new `limel-circular-progress` component

src/components/popover/popover.tsx
fix Lundalogik/crm-feature#2102
Windows:
Linux:
macOS:
Mobile:
=> feat(popover): make popover public

src/components/header/header.tsx, src/components/popover/popover.tsx
fix Lundalogik/crm-feature#2026
Windows:
Linux:
macOS:
Mobile:
=> feat(header): make header component public

src/components/list/list-renderer.tsx, src/components/list/list.tsx, src/components/menu-surface/menu-surface.tsx
Windows:
Linux:
macOS:
Mobile:
=> refactor menu-surface and list: use arrow functions instead of bind

src/components/tooltip/tooltip-content.scss, src/components/tooltip/tooltip-content.tsx, src/components/tooltip/tooltip.scss
fix: https://github.com/Lundalogik/lime-elements/issues/1408
Windows:
Linux:
macOS:
Mobile:
=> fix(tooltip): fix position of a tooltip

package-lock.json, package.json, stencil.config.ts
Windows:
Linux:
macOS:
Mobile:
=> Stencil sourcemaps

CONTRIBUTING.md
Windows:
Linux:
macOS:
Mobile:
=> docs(contributing.md): remove extraneous backticks

publish-docs.js, src/components/config/config.tsx, src/index.html, stencil.config.docs.ts
Windows:
Linux:
macOS:
Mobile:
=> docs: load icons from external source

src/components/menu/examples/menu-badge-icons.tsx, src/components/menu/examples/menu-basic.tsx, src/components/menu/examples/menu-disabled.tsx, src/components/menu/examples/menu-grid.tsx, src/components/menu/examples/menu-hotkeys.tsx, src/components/menu/examples/menu-icons.tsx, src/components/menu/examples/menu-open-left.tsx
Windows:
Linux:
macOS:
Mobile:
=> docs(menu): replace instances of `ListItem` with `MenuItem`

src/components/form/form.scss, src/components/form/templates/array-field.ts
Windows:
Linux:
macOS:
Mobile:
=> Improve form for admin

src/components/table/partial-styles/tabulator-custom-styles.scss
fix: https://github.com/Lundalogik/lime-webclient/issues/1919
Windows:
Linux:
macOS:
Mobile:
=> 1919 no change in footer for low density tables

src/components/form/form.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(form): fix alignment issues of checkbox & switch in forms

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> Update lime icons8 + lint modules

src/components/form/form.scss, src/components/select/select.scss
fix Lundalogik/crm-feature#2273
Windows:
Linux:
macOS:
Mobile:
=> Add padding option field

src/components/form/form.scss, src/components/form/templates/array-field-collapsible-item.ts
fix: https://github.com/Lundalogik/crm-feature/issues/2494
(only for using in Form - lime Admin)
=> fix(array-field-collapsible-item): add margin-bottom to the collapsible section 

src/components/progress-flow/progress-flow-item/partial-styles/_selected-indicator.scss, src/components/progress-flow/progress-flow-item/progress-flow-item.scss, src/components/progress-flow/progress-flow.scss
fix https://github.com/Lundalogik/lime-elements/issues/1463
Windows:
Linux:
macOS:
Mobile:
=> 1463 prevent unnecessary scroll in progress flow

src/components/form/form.tsx
Windows:
Linux:
macOS:
Mobile:
=> feat(form): make it possible to disable whole form

src/components/slider/slider.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/2419
Windows:
Linux:
macOS:
Mobile:
=> fix(slider): ensure that the component doesn't crash when value % step !== 0

src/components/input-field/input-field.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2504
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): fix the "clear all" button in input type="search"

src/components/code-editor/code-editor.scss, src/components/code-editor/examples/code-editor.scss, src/components/code-editor/examples/code-editor.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/2540
fix: https://github.com/Lundalogik/crm-feature/issues/2539
Windows:
Linux:
macOS:
Mobile:
=> 2540 code editor height

src/components/form/templates/array-field-collapsible-item.ts
fix: https://github.com/Lundalogik/crm-feature/issues/2549
Windows:
Linux:
macOS:
Mobile:
=> fix(array-field-collapsible): change the order of the icons

src/components/color-picker/partial-styles/_lime-admin-hack.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2566
Windows:
Linux:
macOS:
Mobile:
=> fix(color-picker): add "lime-magenta" color

src/components/list/radio-button/radio-button.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2571
Windows:
Linux:
macOS:
Mobile:
=> fix(list): add missing styling for radio buttons

src/components/list/list.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2572
Windows:
Linux:
macOS:
Mobile:
=> fix(list): reduce distance between radio buttons & checkboxes and list text

src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/components/chip-set/examples/chip-set-input.scss, src/components/chip-set/examples/chip-set-input.tsx, src/components/chip-set/partial-styles/_helper-text.scss
fix https://github.com/Lundalogik/crm-feature/issues/2579
Windows:
Linux:
macOS:
Mobile:
=> 2579 add helpertext support for chipset

src/components/picker/picker.tsx
fix https://github.com/Lundalogik/crm-feature/issues/2576
Windows:
Linux:
macOS:
Mobile:
=> 2576 add helpertext support for picker

src/components/checkbox/partial-styles/_helper-text.scss, src/components/select/partial-styles/_helper-text.scss, src/components/select/select.scss, src/components/select/select.template.tsx, src/style/internal/shared_input-select-picker.scss
fix https://github.com/Lundalogik/crm-feature/issues/2586
Windows:
Linux:
macOS:
Mobile:
=> 2586 helper text of select

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> chore(packages): upgrade Kompendium from v.0.10.2 to 0.10.3

src/components/checkbox/checkbox.template.tsx, src/components/checkbox/checkbox.tsx, src/components/checkbox/examples/checkbox.tsx
https://user-images.githubusercontent.com/435885/149546729-b2edc3c7-8b0d-4cda-a547-dea43a0028e5.mov
Windows:
Linux:
macOS:
Mobile:
=> feat(checkbox): indeterminate state support

src/components/checkbox/checkbox.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2612
Windows:
Linux:
macOS:
Mobile:
=> fix(checkbox): make a solid background color

src/components/tooltip/examples/tooltip-composite.tsx, src/components/tooltip/examples/tooltip-max-character.scss, src/components/tooltip/examples/tooltip-max-character.tsx, src/components/tooltip/tooltip-content.scss, src/components/tooltip/tooltip-content.tsx, src/components/tooltip/tooltip.spec.tsx, src/components/tooltip/tooltip.tsx
fix https://github.com/Lundalogik/crm-feature/issues/2596
Windows:
Linux:
macOS:
Mobile:
=> limel-tooltip: add maxLength and allow text line-wrapping

src/components/list/list.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2629
Windows:
Linux:
macOS:
Mobile:
=> fix(list): add margin to the "limel-list" for proper keyboard visualization

src/components/table/table.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(table): check if tableSelection is exists

.github/workflows/pr-checks.yml
Longest job before: 8:14
After: 3:47
Windows:
Linux:
macOS:
Mobile:
=> Update pr workflow

src/components/checkbox/checkbox.scss, src/components/checkbox/checkbox.template.tsx, src/components/checkbox/partial-styles/_helper-text.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2648
Windows:
Linux:
macOS:
Mobile:
=> fix(table): avoid cropping the checkbox column

src/components/picker/picker.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/2669
Windows:
Linux:
macOS:
Mobile:
=> fix(picker): make dropdown list full-width

src/components/form/form.scss
fix https://github.com/Lundalogik/crm-feature/issues/2667
Windows:
Linux:
macOS:
Mobile:
=> fix(form): vertically align switches correctly

src/components/checkbox/checkbox.scss, src/components/checkbox/checkbox.template.tsx, src/components/checkbox/checkbox.tsx, src/components/checkbox/examples/checkbox.tsx, src/components/checkbox/partial-styles/_readonly.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2672
Windows:
Linux:
macOS:
Mobile:
=> feat(checkbox): add support for readonly state

src/components/input-field/input-field.tsx
fix Lundalogik/crm-feature#2658
Windows:
Linux:
macOS:
Mobile:
=> remove indentation when having required error in textarea

publish-docs.js
Windows:
Linux:
macOS:
Mobile:
=> docs: only keep the latest next-version

package-lock.json
Windows:
Linux:
macOS:
Mobile:
=> chore(package): update sub-dependency `ansi-regex`

src/components/dialog/dialog.tsx, src/components/dialog/dialog.types.ts
fix Lundalogik/crm-feature#1122
Windows:
Linux:
macOS:
Mobile:
=> fix(dialog): make it possible to update closing actions

src/components/header/header.scss, src/components/header/header.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/2796 
Windows:
Linux:
macOS:
Mobile:
=> 2796 make narrow headers narrower

src/components/input-field/examples/input-field-number-prefix.tsx, src/components/input-field/examples/input-field-text-suffix.tsx, src/components/input-field/input-field.scss, src/components/input-field/input-field.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/1767
https://user-images.githubusercontent.com/50618208/171202251-096cf76d-5ee5-4ee1-b280-ee901ec8f1e5.mov
https://user-images.githubusercontent.com/50618208/171202637-e25a66bd-ecf2-4510-b397-7db9735efc8e.mov
Windows:
Linux:
macOS:
Mobile:
=> feat(input-field): add support for displaying prefix and suffix

src/components/date-picker/date-picker.scss, src/components/date-picker/date-picker.tsx
fix https://github.com/Lundalogik/crm-feature/issues/2789
Windows:
Linux:
macOS:
Mobile:
=> 2789 disabled date pickers

src/components/list/list.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2895
Windows:
Linux:
macOS:
Mobile:
=> fix(list): make hover circle centred

.eslintrc.js, package-lock.json, package.json, src/components/chip-set/chip-set.tsx, src/components/date-picker/pickers/MonthPicker.tsx, src/components/date-picker/pickers/QuarterPicker.tsx, src/components/date-picker/pickers/YearPicker.tsx, src/components/menu/menu.tsx
Windows:
Linux:
macOS:
Mobile:
=> chore: remove unmaintained plugin `@stencil/eslint-plugin`

src/components/button/button.e2e.ts, src/components/button/button.scss, src/components/button/button.tsx, src/components/button/examples/button-click-fail.tsx, src/components/button/examples/button-click-success.tsx, src/components/button/examples/button-reduce-presence.tsx
fix: Lundalogik/crm-feature#2733
Windows:
Linux:
macOS:
Mobile:
=> feat(button): add loadingFailed property

src/components/dock/dock.tsx
Windows:
Linux:
macOS:
Mobile:
=> feat(dock): emit event when dock is expanded or collapsed

src/components/dock/dock-button/dock-button.tsx, src/components/dock/dock.tsx
Windows:
Linux:
macOS:
Mobile:
=> Fix dock events and docs

src/components/date-picker/date-picker.tsx, src/components/input-field/examples/input-field-placeholder.tsx, src/components/input-field/input-field.tsx
Windows:
Linux:
macOS:
Mobile:
=> feat: enable adding placeholder text for input-field & date-picker

src/components/select/select.scss, src/components/select/select.template.tsx
fix https://github.com/Lundalogik/crm-feature/issues/2909
Windows:
Linux:
macOS:
Mobile:
=> 2909 select rotate caret

src/components/table/examples/invoices.ts, src/components/table/examples/table-layout-default.tsx, src/components/table/examples/table-layout-lowDensity.tsx, src/components/table/examples/table-layout-stretchColumns.tsx, src/components/table/examples/table-layout-stretchLastColumn.tsx, src/components/table/examples/table-low-clickable-rows.tsx, src/components/table/layout.ts, src/components/table/table.scss, src/components/table/table.tsx
fix https://github.com/Lundalogik/crm-feature/issues/2941
Windows:
Linux:
macOS:
Mobile:
=> 2941 table layouts

src/components/table/partial-styles/_row-selection.scss, src/components/table/partial-styles/header-component.scss, src/components/table/partial-styles/tabulator-arrow.scss, src/components/table/partial-styles/tabulator-custom-styles.scss, src/components/table/table.scss
fix https://github.com/Lundalogik/lime-elements/issues/1830
Windows:
Linux:
macOS:
Mobile:
=> 1830 hide table columns

src/components/dock/dock-button/dock-button.spec.tsx, src/components/dock/dock-button/dock-button.tsx, src/components/dock/examples/my-custom-menu.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/2944#issuecomment-1231614412
Windows:
Linux:
macOS:
Mobile:
=> 2944 keyboard navigation

src/components/table/table.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(table): enable select all checkbox without totalRows, only data

.github/workflows/pr-checks.yml
fix: Lundalogik/crm-feature#3014
Windows:
Linux:
macOS:
Mobile:
=> Only publish docs for PRs originating from a repo owned by Lime

.github/workflows/pr-checks.yml
See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
Windows:
Linux:
macOS:
Mobile:
=> Update workflows to limit access to unnecessary privileges

src/components/input-field/input-field.e2e.ts
Windows:
Linux:
macOS:
Mobile:
=> test(input-field): hopefully fix blinking test

src/components/input-field/input-field.tsx, src/components/picker/picker.tsx
Windows:
Linux:
macOS:
Mobile:
=> Fix broken build

src/components/button/button.scss, src/components/split-button/examples/split-button-basic.tsx, src/components/split-button/examples/split-button-repeat-default-command.tsx, src/components/split-button/split-button.e2e.ts, src/components/split-button/split-button.scss, src/components/split-button/split-button.spec.tsx, src/components/split-button/split-button.tsx
fix https://github.com/Lundalogik/crm-feature/issues/2953
close https://github.com/Lundalogik/hack-tuesday/issues/265
Windows:
Linux:
macOS:
Mobile:
=> Split button

src/components/circular-progress/circular-progress.scss, src/components/circular-progress/examples/circular-progress-css-variables.scss, src/components/circular-progress/examples/circular-progress-css-variables.tsx
Windows:
Linux:
macOS:
Mobile:
=> feat(circular-progress): add CSS props for coloring text & background

.github/workflows/pre-release.yml, .github/workflows/release.yml, release.config.js
Windows:
Linux:
macOS:
Mobile:
=> Fix docs not being published for new releases

src/components/select/select.template.tsx
fix https://github.com/Lundalogik/crm-feature/issues/1839 
Windows:
Linux:
macOS:
Mobile:
=> 1839 empty select

src/components/list/list.scss, src/components/list/list.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/799
fix: https://github.com/Lundalogik/lime-elements/issues/1535
fix: https://github.com/Lundalogik/crm-feature/issues/2710
Windows:
Linux:
macOS:
Mobile:
=> 1535 list remove ripple

src/components/select/select.scss
Windows:
Linux:
macOS:
Mobile:
=> Select UI improvements

src/global/core-styles.scss, src/style/color-palette-extended.css, src/style/mixins.scss, src/style/shadows.scss
Windows:
Linux:
macOS:
Mobile:
=> Dark mode shadows

src/components/list/list.scss, src/components/list/partial-styles/custom-styles.scss
Windows:
Linux:
macOS:
Mobile:
=> Fix list darkmode

src/components/button/button.e2e.ts, src/components/button/button.scss, src/components/button/button.tsx, src/components/button/examples/button-outlined.tsx, src/components/button/examples/button-primary.tsx
fix https://github.com/Lundalogik/lime-elements/issues/2003
Windows:
Linux:
macOS:
Mobile:
=> 2003 unelevated buttons

src/components/select/select.template.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(select): do not cover a value by label if multiple selections are possible

src/components/form/examples/row-layout-schema.ts, src/components/form/examples/row-layout.tsx, src/components/form/form.scss, src/components/form/form.tsx, src/components/form/form.types.ts, src/components/form/row/row.scss, src/components/form/row/row.tsx, src/components/form/templates/object-field.ts, src/components/form/templates/row-layout.ts, src/components/form/templates/types.ts
fix https://github.com/Lundalogik/crm-feature/issues/3178
Windows:
Linux:
macOS:
Mobile:
=> feat(form): add new layout type for rendering form fields in rows

src/examples/example-event-printer.scss, src/examples/example-event-printer.tsx
fix https://github.com/Lundalogik/lime-elements/issues/2111
Windows:
Linux:
macOS:
Mobile:
=> chore(example-event-printer): improve UI and accessibility

.github/workflows/pr-checks.yml
Windows:
Linux:
macOS:
Mobile:
=> ci(pr-checks.yml): run on `merge_group` events too

.eslintrc.js
Windows:
Linux:
macOS:
Mobile:
=> refactor(.eslintrc.js): merge duplicate override for test files

src/components/badge/badge.scss, src/components/badge/badge.tsx, src/components/badge/examples/badge.tsx
fix https://github.com/Lundalogik/crm-feature/issues/3227
Windows:
Linux:
macOS:
Mobile:
=> fix(badge): render it smaller, when there is no label

src/components/badge/badge.scss, src/components/badge/badge.tsx, src/components/badge/examples/badge-string.tsx, src/components/menu/menu.scss, src/components/menu/menu.tsx
fix https://github.com/Lundalogik/crm-feature/issues/3235
Windows:
Linux:
macOS:
Mobile:
=> Center align badge

src/components/dialog/dialog.scss, src/components/dock/dock.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1534
⚠️ to see the full effect and how these are used, you need to check other connected PRs
Windows:
Linux:
macOS:
Mobile:
=> feat(dock): add CSS variables for paddings around the dock

src/components/info-tile/info-tile.scss, src/components/shortcut/shortcut.scss
fix https://github.com/Lundalogik/crm-feature/issues/3301
Windows:
Linux:
macOS:
Mobile:
=> Badges on infotile and shortcut

src/components/collapsible-section/collapsible-section.e2e.ts, src/components/collapsible-section/collapsible-section.scss, src/components/collapsible-section/collapsible-section.tsx, src/components/collapsible-section/partial-styles/expand-icon.scss
fix https://github.com/Lundalogik/lime-elements/issues/2052
Windows:
Linux:
macOS:
Mobile:
=> Collapsible section interactivity

src/components/form/form.scss
fix: https://github.com/Lundalogik/crm-feature/issues/3316
Windows:
Linux:
macOS:
Mobile:
=> fix(form): decrease min-height of rows

src/components/snackbar/examples/snackbar-changing-message.tsx, src/components/snackbar/examples/snackbar-with-action.tsx, src/components/snackbar/examples/snackbar.scss, src/components/snackbar/examples/snackbar.tsx, src/components/snackbar/snackbar.tsx
Windows:
Linux:
macOS:
Mobile:
=> Snackbar: Add some good documentations and usage guides

src/components/snackbar/snackbar.scss, src/components/snackbar/snackbar.tsx
Windows:
Linux:
macOS:
Mobile:
=> Snackbar: design improvements

src/components/callout/examples/callout-composite.tsx
Windows:
Linux:
macOS:
Mobile:
=> docs(callout): add styles to composite component

src/components/action-bar/action-bar-item/action-bar-item.scss, src/components/action-bar/action-bar-item/action-bar-item.tsx, src/components/action-bar/action-bar-item/action-bar-overflow-menu.tsx, src/components/action-bar/action-bar.e2e.ts, src/components/action-bar/action-bar.scss, src/components/action-bar/action-bar.tsx, src/components/action-bar/action-bar.types.ts, src/components/action-bar/examples/_application.scss, src/components/action-bar/examples/action-bar-as-list-component.tsx, src/components/action-bar/examples/action-bar-colors.tsx, src/components/action-bar/examples/action-bar-floating.scss, src/components/action-bar/examples/action-bar-floating.tsx, src/components/action-bar/examples/action-bar-in-list.scss, src/components/action-bar/examples/action-bar-in-list.tsx, src/components/action-bar/examples/action-bar-overflow-menu.scss, src/components/action-bar/examples/action-bar-overflow-menu.tsx, src/components/action-bar/examples/action-bar-styling.scss, src/components/action-bar/examples/action-bar-styling.tsx, src/components/action-bar/examples/action-bar.scss, src/components/action-bar/examples/action-bar.tsx, src/components/action-bar/isItem.spec.ts, src/components/action-bar/isItem.ts, src/interface.d.ts
fix: https://github.com/Lundalogik/crm-feature/issues/3379
Windows:
Linux:
macOS:
Mobile:
=> feat(action-bar): add new component

src/components/popover-surface/popover-surface.scss
fix https://github.com/Lundalogik/crm-feature/issues/3475
Windows:
Linux:
macOS:
Mobile:
=> feat(popover): add a CSS prop for the max height of the popover

src/components/snackbar/examples/snackbar-positioning.scss, src/components/snackbar/examples/snackbar-positioning.tsx, src/components/snackbar/snackbar.scss, src/components/snackbar/snackbar.tsx
fix https://github.com/Lundalogik/crm-feature/issues/3360
Windows:
Linux:
macOS:
Mobile:
=> feat(snackbar): add CSS variables for positioning the snackbar

src/components/input-field/input-field.e2e.ts, src/components/input-field/input-field.tsx, src/util/random-string.ts
fix https://github.com/Lundalogik/lime-elements/issues/2255
Windows:
Linux:
macOS:
Mobile:
=> Helper text ids

src/components/collapsible-section/collapsible-section.tsx, src/util/makeEnterClickable.ts
Fixes Lundalogik/crm-feature#3535
Windows:
Linux:
macOS:
Mobile:
=> Make collapsible section enter clickable

src/components/checkbox/checkbox.tsx, src/components/switch/examples/switch-vs-checkbox.scss, src/components/switch/examples/switch-vs-checkbox.tsx, src/components/switch/switch.tsx
fix https://github.com/Lundalogik/crm-feature/issues/3539
Windows:
Linux:
macOS:
Mobile:
=> Switch vs checkbox

src/components/switch/switch.tsx
Fixes Lundalogik/crm-feature#3542
Windows:
Linux:
macOS:
Mobile:
=> feat(switch): override default browser behavior on clicking enter

src/components/slider/slider.tsx
fix: Lundalogik/crm-feature#3550
fix: Lundalogik/crm-feature#3287
fix: #1850
Windows:
Linux:
macOS:
Mobile:
=> fix(slider): fix bug where slider might break if the component is resized

src/components/slider/examples/slider-basic.tsx, src/components/slider/slider.tsx
I _strongly_ suggest reviewing this commit by commit 😅 (each commit is more or less trivial on its own, but I have moved code around a bit in two commits, so if you look at the whole diff at once, it's much harder to see what actual code changes have been made).
Windows:
Linux:
macOS:
Mobile:
=> Clean up code in limel-slider

src/components/action-bar/action-bar-item/action-bar-item.scss, src/components/action-bar/examples/_application.scss, src/components/action-bar/examples/action-bar-floating.scss
fix https://github.com/Lundalogik/crm-feature/issues/3561
Windows:
Linux:
macOS:
Mobile:
=> Remove tooltips hacks

.github/workflows/pr-checks.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml
Windows:
Linux:
macOS:
Mobile:
=> Clean up workflows

src/components/form/widgets/select.ts
related to Lundalogik/crm-feature#3591
Windows:
Linux:
macOS:
Mobile:
=> feat(form): add support for disabled options when using a select

src/components/action-bar/action-bar-item/action-bar-item.scss
Fix: https://github.com/Lundalogik/crm-feature/issues/3598
Windows:
Linux:
macOS:
Mobile:
=> fix(action-bar-item): make disabled button visible

src/components/breadcrumbs/breadcrumbs.scss, src/components/breadcrumbs/breadcrumbs.spec.tsx, src/components/breadcrumbs/breadcrumbs.tsx, src/components/breadcrumbs/breadcrumbs.types.ts, src/components/breadcrumbs/examples/breadcrumbs-buttons.tsx, src/components/breadcrumbs/examples/breadcrumbs-divider.tsx, src/components/breadcrumbs/examples/breadcrumbs-icon-color.tsx, src/components/breadcrumbs/examples/breadcrumbs-icon-only.tsx, src/components/breadcrumbs/examples/breadcrumbs-links.tsx, src/components/breadcrumbs/examples/breadcrumbs-styling.scss, src/components/breadcrumbs/examples/breadcrumbs-styling.tsx, src/interface.d.ts
fix: https://github.com/Lundalogik/crm-feature/issues/3042
Windows:
Linux:
macOS:
Mobile:
=> feat(breadcrumbs): add new component

src/components/list/examples/list-separator.tsx, src/components/list/examples/list.tsx, src/components/list/list-item.types.ts, src/components/list/list-renderer.tsx, src/components/list/list.scss, src/components/list/list.tsx, src/components/menu-list/menu-list-renderer.tsx, src/components/menu/examples/menu-separators.tsx, src/components/menu/menu.tsx
fix https://github.com/Lundalogik/lime-elements/issues/2512
Windows:
Linux:
macOS:
Mobile:
=> List separators

src/index.ts
Windows:
Linux:
macOS:
Mobile:
=> feat(src): export `Link` & `Icon` interfaces

src/components/collapsible-section/collapsible-section.e2e.ts, src/components/collapsible-section/collapsible-section.scss, src/components/collapsible-section/collapsible-section.tsx, src/components/collapsible-section/partial-styles/expand-icon.scss
fix https://github.com/Lundalogik/crm-feature/issues/3692
Windows:
Linux:
macOS:
Mobile:
=> Collapsible section height animattion

src/components/picker/picker.tsx
fix https://github.com/Lundalogik/crm-feature/issues/3699
Windows:
Linux:
macOS:
Mobile:
=> Picker less color

src/components/helper-line/examples/helper-line-animation.tsx, src/components/helper-line/examples/helper-line-empty.scss, src/components/helper-line/examples/helper-line-no-content.tsx, src/components/helper-line/helper-line.scss, src/components/helper-line/helper-line.tsx, src/components/input-field/examples/input-field-text.tsx
Windows:
Linux:
macOS:
Mobile:
=> Animate limel helper line

src/components/input-field/input-field.scss, src/components/input-field/input-field.tsx
Windows:
Linux:
macOS:
Mobile:
=> Refactor input field

src/components/helper-line/helper-line.scss
Windows:
Linux:
macOS:
Mobile:
=> Refactor helper line css vars

src/components/file-viewer/file-viewer.e2e.ts, src/components/file-viewer/file-viewer.tsx
Windows:
Linux:
macOS:
Mobile:
=> File viewer pdf fetch

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> chore(packages): upgrade Kompendium from 0.12.5 to 0.12.7

src/components/checkbox/checkbox.tsx, src/components/checkbox/examples/checkbox.tsx, src/components/switch/examples/switch-helper-text.tsx, src/components/switch/examples/switch.tsx, src/components/switch/switch.tsx
Windows:
Linux:
macOS:
Mobile:
=> Invalid switch and checkbox

src/components/input-field/examples/input-field-text.tsx, src/style/mixins.scss
fix https://github.com/Lundalogik/lime-elements/issues/2617
Windows:
Linux:
macOS:
Mobile:
=> Form invalid input fields

guides.ts, src/components/button/examples/button-disabled.tsx, src/design-guidelines/disabled-hidden/disabled-hidden.md, src/design-guidelines/disabled-hidden/examples/button-disabled-vs-hidden.scss, src/design-guidelines/disabled-hidden/examples/disabled-vs-hidden.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/2597
Windows:
Linux:
macOS:
Mobile:
=> feat(button): add guidelines for `disable` and `hide` buttons

src/components/menu-list/menu-list-renderer.tsx, src/components/menu/examples/menu-sub-menu-lazy-loading-infinite.tsx, src/components/menu/examples/menu-sub-menu-lazy-loading-service-mock-server.ts, src/components/menu/examples/menu-sub-menu-lazy-loading-service-mock.ts, src/components/menu/examples/menu-sub-menu-lazy-loading.tsx, src/components/menu/menu.tsx, src/components/menu/menu.types.ts
This is one of three PRs that are connected and extracted from #2574 
They are chained in 3 branches and is best reviewed in this order:
1. https://github.com/Lundalogik/lime-elements/pull/2576 
2. https://github.com/Lundalogik/lime-elements/pull/2577 **This PR**
3. https://github.com/Lundalogik/lime-elements/pull/2578
Windows:
Linux:
macOS:
Mobile:
=> feat(menu): lazy loading

src/components/menu/examples/menu-composite.tsx, src/components/menu/examples/menu-searchable.tsx, src/components/menu/examples/subitems-search.ts, src/components/menu/menu.tsx, src/components/menu/menu.types.ts
This is one of three PRs that are connected and extracted from #2574 
They are chained in 3 branches and is best reviewed in this order:
1. https://github.com/Lundalogik/lime-elements/pull/2576
2. https://github.com/Lundalogik/lime-elements/pull/2577
3. https://github.com/Lundalogik/lime-elements/pull/2578 **This PR**
Windows:
Linux:
macOS:
Mobile:
=> feat(menu): add search functionality

src/components/breadcrumbs/breadcrumbs.scss, src/style/mixins.scss
Windows:
Linux:
macOS:
Mobile:
=> Link mixin

src/components/markdown/markdown.scss, src/components/markdown/partial-styles/_body-text.scss
fix https://github.com/Lundalogik/crm-feature/issues/3804
Windows:
Linux:
macOS:
Mobile:
=> feat(markdown): add CSS props for hyperlinks colors

src/components/action-bar/examples/action-bar-as-list-component.tsx, src/components/dock/examples/dock-custom-component.tsx, src/components/form/examples/basic-form.tsx, src/components/form/examples/custom-component-form.tsx, src/components/form/examples/custom-error-message-form.tsx, src/components/form/examples/layout-form.tsx, src/components/form/examples/list-form.tsx, src/components/form/examples/nested-form.tsx, src/components/form/examples/props-factory-form.tsx, src/components/form/examples/row-layout.tsx, src/components/form/examples/server-errors.tsx, src/components/form/examples/span-fields.tsx, src/components/menu/examples/menu-open-sub-menu-programmatically.tsx, src/components/menu/examples/menu-searchable.tsx, src/components/menu/examples/menu-sub-menu-lazy-loading.tsx, src/components/menu/examples/menu-sub-menu.tsx, src/components/tab-panel/examples/tab-panel.tsx, src/components/table/examples/table-activate-row.tsx, src/components/table/examples/table-custom-components.tsx, src/components/table/examples/table-header-menu.tsx, src/components/table/examples/table-layout-default.tsx, src/components/table/examples/table-layout-lowDensity.tsx, src/components/table/examples/table-layout-stretchColumns.tsx, src/components/table/examples/table-layout-stretchLastColumn.tsx, src/components/table/examples/table-local.tsx, src/components/table/examples/table-movable-columns.tsx, src/components/table/examples/table-remote.tsx, src/components/table/examples/table-selectable-rows.tsx, src/components/table/examples/table-sorting-disabled.tsx, src/components/table/examples/table.tsx
Windows:
Linux:
macOS:
Mobile:
=> chore(docs): update non-standard use of `@link` to custom tag `@sourceFile`

src/design-guidelines/disabled-hidden/examples/button-disabled-vs-hidden.scss, src/design-guidelines/disabled-hidden/examples/disabled-vs-hidden.tsx
fix: 
https://github.com/Lundalogik/lime-elements/assets/50618208/49ef53ff-d035-4e50-87db-970120b61cf5
Windows:
Linux:
macOS:
Mobile:
=> fix(disabled-vs-hidden): make the guidelines responsible

src/util/link-helper.ts
Windows:
Linux:
macOS:
Mobile:
=> feat(input-field): add support for `file://` protocol

package.json
fix: Lundalogik/lime-webclient#4340
Windows:
Linux:
macOS:
Mobile:
=> docs: include `CHANGELOG.md` in the distributed package

README.md, src/components/icon/icon.tsx
fix https://github.com/Lundalogik/lime-elements/issues/2675
Windows:
Linux:
macOS:
Mobile:
=> Docs intro

src/components/form/adapters/widget-adapter.ts, src/components/form/examples/form-with-help.tsx, src/components/form/examples/help-form-schema.ts, src/components/form/examples/row-layout-schema.ts, src/components/form/fields/schema-field.ts, src/components/form/form.scss, src/components/form/form.tsx, src/components/form/form.types.ts, src/components/form/help/help.ts, src/components/form/help/index.ts, src/components/form/row/row.scss, src/components/help/examples/help-placement.tsx
requires: https://github.com/Lundalogik/lime-elements/pull/2291
Windows:
Linux:
macOS:
Mobile:
=> feat(form): enable providing rich help next to form fields

src/components/header/header.tsx
Windows:
Linux:
macOS:
Mobile:
=> Header props

src/components/header/header.scss
required for https://github.com/Lundalogik/crm-feature/issues/3887
Windows:
Linux:
macOS:
Mobile:
=> Icon badge header

src/components/checkbox/checkbox.template.tsx, src/components/switch/switch.tsx
Windows:
Linux:
macOS:
Mobile:
=> Helper line in switch and checkbox

src/components/form/form.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(form): add gap between rows in array items

etc/lime-elements.api.md, src/components/picker/examples/picker-value-as-object.tsx, src/components/picker/picker.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/2758
https://github.com/Lundalogik/lime-elements/assets/50618208/9483c045-3c88-4c97-87f7-1f031d6f9859
Windows:
Linux:
macOS:
Mobile:
=> fix(picker): be able to have value as object

etc/lime-elements.api.md, src/components/chip-set/chip-set.e2e.ts, src/components/chip-set/chip-set.tsx, src/components/file/file.tsx
fix: #2793
Windows:
Linux:
macOS:
Mobile:
=> fix(file): fix bug where links on chips could not be opened

etc/lime-elements.api.md, src/components/chip/chip.scss, src/components/chip/chip.tsx, src/components/chip/examples/chip-button.tsx, src/components/chip/examples/chip-loading.tsx
fix https://github.com/Lundalogik/crm-feature/issues/3934
Windows:
Linux:
macOS:
Mobile:
=> feat(chip): add `invalid` state

src/interface.ts
Windows:
Linux:
macOS:
Mobile:
=> chore: fix exports so dev-build does not fail

package-lock.json, package.json, src/components/markdown/allowed-css-properties.ts, src/components/markdown/examples/markdown-html.tsx, src/components/markdown/markdown-parser.ts, src/components/markdown/sanitize-style.spec.ts, src/components/markdown/sanitize-style.ts
fix: https://github.com/Lundalogik/limepkg-email/issues/590
Windows:
Linux:
macOS:
Mobile:
=> feat(markdown): support text color in html style attribute

src/components/text-editor/text-editor.tsx
Fixes Lundalogik/crm-feature#4038
Windows:
Linux:
macOS:
Mobile:
=> Text editor support lists

.github/workflows/release.yml
fix: Lundalogik/crm-feature#4048
Windows:
Linux:
macOS:
Mobile:
=> ci(release.yml): publish releases on s3

src/components/text-editor/examples/text-editor-with-custom-menu.tsx, src/components/text-editor/menu/full-menu.ts, src/components/text-editor/menu/menu-filter.ts, src/components/text-editor/menu/types.ts, src/components/text-editor/text-editor.tsx
Fixes Lundalogik/crm-feature#4041
Closes https://github.com/Lundalogik/crm-feature/issues/4055
Windows:
Linux:
macOS:
Mobile:
=> Add text editor menu prop

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> Update @typescript-eslint/* from v7.5.0 to v7.7.1

src/examples/example-value.tsx
Windows:
Linux:
macOS:
Mobile:
=> chore(example-value): add missing `?` for optional prop and remove redundant typing

src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx
Windows:
Linux:
macOS:
Mobile:
=> chore(text-editor): forgot to make method private

src/components/input-field/examples/input-field-number-prefix.tsx, src/components/input-field/examples/input-field-number.tsx, src/components/input-field/input-field.tsx
fix: #1402
requires: https://github.com/Lundalogik/lime-elements/pull/2869
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): update number value only when different

src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx
Fixes Lundalogik/crm-feature#4056 and https://github.com/Lundalogik/crm-feature/issues/4112
Windows:
Linux:
macOS:
Mobile:
=> Make text editor work in webclient

etc/lime-elements.api.md, src/components/chip-set/chip-set.tsx, src/components/chip-set/chip.types.ts, src/components/chip-set/examples/chip-image.tsx, src/components/chip/chip.scss, src/components/chip/chip.tsx, src/components/chip/examples/chip-image.tsx, src/global/shared-types/image.types.ts, src/interface.ts
fix https://github.com/Lundalogik/hack-tuesday/issues/345
Windows:
Linux:
macOS:
Mobile:
=> enable adding images to chips

src/components/text-editor/prosemirror-adapter/menu/menu-command.spec.tsx, src/components/text-editor/prosemirror-adapter/menu/menu-commands.ts, src/components/text-editor/prosemirror-adapter/menu/menu-items.ts, src/components/text-editor/prosemirror-adapter/menu/types.ts, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx
Fixes https://github.com/Lundalogik/crm-feature/issues/4084
=> feat(text editor): add explicit menu types

src/components/chip/chip.scss, src/components/chip/chip.tsx
Windows:
Linux:
macOS:
Mobile:
=> UI improvements in chip

src/components/snackbar/snackbar.scss, src/components/snackbar/snackbar.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/2978
Windows:
Linux:
macOS:
Mobile:
=> fix(snackbar): improve UX of dismissible snackbar

src/components/breadcrumbs/breadcrumbs.spec.tsx, src/components/text-editor/text-editor.spec.tsx, src/components/text-editor/text-editor.tsx, src/util/get-attributes.ts
Fixes Lundalogik/crm-feature#4076
Windows:
Linux:
macOS:
Mobile:
=> Add tests for the text editor and related files

src/components/text-editor/prosemirror-adapter/menu/menu-command.spec.tsx, src/components/text-editor/prosemirror-adapter/menu/menu-commands.ts, src/components/text-editor/prosemirror-adapter/menu/menu-items.ts, src/components/text-editor/prosemirror-adapter/menu/menu-schema-extender.ts, src/components/text-editor/prosemirror-adapter/menu/types.ts, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx, src/components/text-editor/utils/markdown-converter.ts
Updates the menu-command factory to make it possible to toggle menu commands. 
Fixes https://github.com/Lundalogik/crm-feature/issues/4130
=> Extend menu commands 

src/components.d.ts, src/components/text-editor/link-menu/editor-link-menu.scss, src/components/text-editor/link-menu/editor-link-menu.tsx, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx
fix https://github.com/Lundalogik/crm-feature/issues/4164
fix https://github.com/Lundalogik/crm-feature/issues/4172
Windows:
Linux:
macOS:
Mobile:
=> handle keyboard navigation problems and more

src/components/banner/banner.scss, src/components/banner/banner.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/4165
https://github.com/Lundalogik/lime-elements/assets/50618208/c905b031-e5b0-4d5b-921b-45641a97be56
Windows:
Linux:
macOS:
Mobile:
=> fix(banner): improve mobile layout

src/components/list/list.scss, src/components/menu-list/menu-list.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(list): improve distances between elements within list items

src/components/text-editor/prosemirror-adapter/menu/menu-commands.ts
Certain node types, in this case blockQuote, wrap the parent node, in this case a paragraph. We need to check if the blockType is active and then lift the selection out of the wrap. 
Not allowing for block quotes to be created across paragraphs is intentional (eg: write multiple paragraphs, try and select them all and wrap all in a block quote). 
Fixes https://github.com/Lundalogik/crm-feature/issues/4214
=> fix(editor menu): allow block quotes to be toggled

src/components/select/select.tsx
fix: #1268
fix: Lundalogik/crm-feature#2808
Windows:
Linux:
macOS:
Mobile:
=> fix(select): fix bug introduced in v37.55.1, completely breaking limel-select

src/components/dialog/dialog.scss, src/components/dialog/dialog.tsx, src/components/dialog/partial-styles/show-hide-animations.scss
fix https://github.com/Lundalogik/lime-elements/issues/2893
Windows:
Linux:
macOS:
Mobile:
=>  refactor(dialog): use native dialog element and remove MDC

src/components/date-picker/flatpickr-adapter/flatpickr-adapter.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(datepicker): use variable correctly

etc/lime-elements.api.md, src/components/snackbar/examples/snackbar-changing-message.tsx, src/components/snackbar/examples/snackbar-dismissible.tsx, src/components/snackbar/examples/snackbar-persistent-non-dismissible.tsx, src/components/snackbar/examples/snackbar-persistent.tsx, src/components/snackbar/examples/snackbar-with-action.tsx, src/components/snackbar/examples/snackbar.tsx, src/components/snackbar/snackbar.e2e.ts, src/components/snackbar/snackbar.tsx
fix https://github.com/Lundalogik/crm-feature/issues/3355
Windows:
Linux:
macOS:
Mobile:
=> Snackbar persistent

.github/dependabot.yml, package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> Fix docs publish

src/components/text-editor/prosemirror-adapter/prosemirror-adapter.scss, src/components/text-editor/text-editor.scss, src/components/text-editor/text-editor.spec.tsx, src/components/text-editor/text-editor.tsx
Windows:
Linux:
macOS:
Mobile:
=> text-editor: varius problems

src/components/markdown/markdown-parser.ts, src/components/markdown/markdown.scss
fixes: https://github.com/Lundalogik/limepkg-email/issues/649
Windows:
Linux:
macOS:
Mobile:
=> fix(markdown): allow MsoNormal class attribute, and add default styling for it

etc/lime-elements.api.md, src/components/markdown/examples/markdown-custom-component.tsx, src/components/markdown/markdown-parser.ts, src/components/markdown/markdown.tsx, src/global/shared-types/custom-element.types.ts, src/interface.ts
Fixes: Lundalogik/crm-feature#4356
Windows:
Linux:
macOS:
Mobile:
=> feat(markdown): add component whitelist

etc/lime-elements.api.md, src/components/chip/partial-styles/_loading.scss, src/components/info-tile/info-tile.scss, src/components/linear-progress/examples/linear-progress-accessible-label.tsx, src/components/linear-progress/examples/linear-progress-indeterminate.tsx, src/components/linear-progress/examples/linear-progress.tsx, src/components/linear-progress/linear-progress.scss, src/components/linear-progress/linear-progress.tsx, src/translations/da.ts, src/translations/en.ts, src/translations/fi.ts, src/translations/nl.ts, src/translations/no.ts, src/translations/sv.ts
Windows:
Linux:
macOS:
Mobile:
=> refactor(linear-progress): get rid of MDC dependecy

README.md, etc/lime-elements.api.md, src/components/chip/chip.tsx
Windows:
Linux:
macOS:
Mobile:
=> feat(chip): remove `@beta` tag

src/components/portal/partial-styles/portal-container.scss, src/components/portal/portal.tsx, src/global/core-styles.scss
respectively.
Windows:
Linux:
macOS:
Mobile:
=> refactor portal and do some improvements

src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx, src/components/text-editor/text-editor.tsx
See commit messages for details.
Credit to @vicgeralds, because I basically lifted the solution straight from 01ce9be4e 🙏
fix: https://github.com/Lundalogik/crm-feature/issues/4312
Windows:
Linux:
macOS:
Mobile:
=> Fix jumping cursor in text-editor

src/components/chip/chip.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/3170
Windows:
Linux:
macOS:
Mobile:
=> fix(chip): improve accessibility while loading

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> chore(package): update @stencil/core from v3.4.1 to v3.4.2

src/components/picker/picker.tsx
fix: #3188
Windows:
Linux:
macOS:
Mobile:
=> fix(picker): clear search when picking a value and multiple is true

src/components/picker/picker.tsx, src/components/portal/portal.tsx
Fixes #3255
Windows:
Linux:
macOS:
Mobile:
=> Fix picker ghost menu

src/components/card/card.scss, src/components/card/examples/card-nested-component.scss, src/components/card/examples/card-nested-component.tsx, src/style/mixins.scss, src/util/3d-tilt-hover-effect.ts
Windows:
Linux:
macOS:
Mobile:
=> improve card UI

.github/workflows/pr-checks.yml
Windows:
Linux:
macOS:
Mobile:
=> ci(pr-checks.yml): fix broken `automerge` job

package-lock.json, package.json, src/components/markdown/markdown-parser.ts, src/components/text-editor/utils/html-converter.ts
fix: Lundalogik/crm-feature#4490
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): close XSS vulnerability

etc/lime-elements.api.md, src/components/text-editor/prosemirror-adapter/plugins/trigger/factory-helpers/append-transaction-handler.spec.ts, src/components/text-editor/prosemirror-adapter/plugins/trigger/factory-helpers/append-transaction-handler.ts, src/components/text-editor/prosemirror-adapter/plugins/trigger/factory-helpers/detect-trigger-removal.spec.ts, src/components/text-editor/prosemirror-adapter/plugins/trigger/factory-helpers/detect-trigger-removal.ts, src/components/text-editor/prosemirror-adapter/plugins/trigger/factory-helpers/get-trigger-event-detail.ts, src/components/text-editor/prosemirror-adapter/plugins/trigger/factory-helpers/monitor-triggered-text.spec.ts, src/components/text-editor/prosemirror-adapter/plugins/trigger/factory-helpers/monitor-triggered-text.ts, src/components/text-editor/prosemirror-adapter/plugins/trigger/factory-helpers/send-trigger-event.ts, src/components/text-editor/prosemirror-adapter/plugins/trigger/factory-helpers/text-input-handler.spec.ts, src/components/text-editor/prosemirror-adapter/plugins/trigger/factory-helpers/text-input-handler.ts, src/components/text-editor/prosemirror-adapter/plugins/trigger/factory.ts, src/components/text-editor/prosemirror-adapter/plugins/trigger/inserter.ts, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx, src/components/text-editor/text-editor.tsx, src/components/text-editor/text-editor.types.ts
fix: Lundalogik/crm-feature#4498
fix: Lundalogik/limepkg-email#127
Windows:
Linux:
macOS:
Mobile:
=> fix triggers not working on iOS and on text-editor inside form

src/components/card/card.scss, src/components/card/card.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/3418
Windows:
Linux:
macOS:
Mobile:
=> fix(card): improve visibility of the header

etc/lime-elements.api.md, src/components/chart/chart.scss, src/components/chart/chart.tsx, src/components/chart/chart.types.ts, src/components/chart/examples/chart-clickable-items.tsx, src/components/chart/examples/chart-items-clickable.ts, src/components/chart/partial-styles/_layout-for-charts-with-x-y-axises.scss, src/components/chart/partial-styles/_nps.scss, src/components/chart/partial-styles/_ring.scss, src/components/chart/partial-styles/_stacked-bar.scss
Windows:
Linux:
macOS:
Mobile:
=> feat(chart): allow making items clickable
