Lundalogik/lime-elements

src/examples/banner/banner.scss, src/examples/button/button.scss, src/examples/color/color-table.scss, src/examples/color/color.scss, src/examples/dialog/dialog-form.scss, src/examples/dialog/dialog-size.scss, src/examples/dialog/dialog-size.tsx, src/examples/flex-container/flex-container.scss, src/examples/icon/icon-background.scss, src/examples/icon/icon.scss, src/examples/input-field/input-field-text-inline.scss, src/examples/switch/switch.scss
The pxToRem() function isn't exported, so we shouldn't use it in examples.
=> docs(pxtorem): remove pxToRem function from examples

src/components/list/list.tsx, src/components/menu-surface/menu-surface.scss, src/components/menu-surface/menu-surface.tsx, src/components/portal/portal.scss, src/components/portal/portal.tsx, src/components/select/select.mdx, src/components/select/select.scss, src/components/select/select.template.tsx, src/components/select/select.tsx, src/examples/select/select-dialog.scss, src/examples/select/select-dialog.tsx, src/util/random-string.ts
This PR introduces a new component called `limel-portal` which takes the portal concept from React (https://reactjs.org/docs/portals.html) and puts it into a component. This allows us to display dropdowns, tooltips and other popovers which are placed inside dialogs in a nicer way without hiding the content inside the dialog itself. There might be a few caveats, but it seems to work quite good.
* Events might not bubble up as expected since the content is moved out to another DOM node
* Any styling that is applied to content from the parent will be lost, if the content is just another web compoent it will work without any issues
* When the node is moved in the DOM, Stencil will invoke the `componentDidUnload`, `disconnectedCallback` and `connectedCallback`, so `componentDidUnload` can not …
=> fix(select): render select menu in document.body

src/components/select/select.tsx
The list component emits two `change` events when a new value is selected. One for the item that was
deselected, and one for the newly selected item. Since it is not possible to deselect a value from
the select (if it is in single select mode), only the second `change` event from the list should
generate a `change` event from the select component.
Windows:
Linux:
macOS:
Mobile:
=> fix(select): only emit one change event when selecting a value

src/components/picker/picker.tsx
BREAKING CHANGE: The `interact` event used to supply a `Chip` used internally by limel-picker, instead of the `ListItem` supplied to limel-picker by the consumer. This has now been fixed. Implementations relying on the incorrect behavior will need to be updated.
Windows:
Linux:
macOS:
Mobile:
=> fix(picker): remove leaking of internal implementation details through the `interact` event

src/components/picker/picker.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(picker): the `interact` event supplies a `ListItem<number | string>` instead of `ListItem<any>`

src/components/chip-set/chip-set.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(chip-set): adds margin to search label

src/components/chip-set/chip-set.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(chip-set): reflect properties `type` and `label` to attribute

package.json
Windows:
Linux:
macOS:
Mobile:
=> chore(package): add `@types/puppeteer` to greenkeeper.ignore

src/components/chip-set/chip-set.e2e.ts, src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/components/list/list-renderer.tsx, src/components/list/list.e2e.ts, src/components/picker/picker.scss, src/components/picker/picker.tsx, src/examples/chip-set/chip-set-input.tsx, src/examples/list/list-secondary.tsx
Chips can't be reached by keyboard at the moment.
Fix #428 
***NB!*** We really should test this on mobile.
Windows:
Linux:
macOS:
Mobile:
=> Improve keyboard navigation for input chip-set, list, and picker

src/components/chip-set/chip-set.e2e.ts, src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/components/snackbar/snackbar.scss, src/components/snackbar/snackbar.tsx
These are some fixes I did while working on removing the dev-dependency on our private icon-set. We'll leave the dev-dependency in for now, but these fixes would still be nice to have 🙂
Windows:
Linux:
macOS:
Mobile:
=> Icon-related fixes

src/components/chip-set/chip-set.tsx, src/components/picker/picker.tsx
Based on #454. I would suggest reviewing and merging that one first, and then pointing this PR to master, before reviewing this. /Ads
Windows:
Linux:
macOS:
Mobile:
=> feat(picker): pressing escape in the dropdown empties and focuses the input

.gitignore, Dockerfile, Jenkinsfile, Makefile, generate_npmrc.sh, package-lock.json, package.json, stencil.config.docs.ts, stencil.config.ts
Developers who have access to Lime's private packages on GitHub Packages should create an `.npmrc` file containing `registry=https://npm.pkg.github.com/lundalogik` in the root of their local repo. Other developers will need to remove the dev-dependency on `@lundalogik/lime-icons8`.
Windows:
Linux:
macOS:
Mobile:
=> chore(package): use GitHub Packages registry

src/components/select/select.scss
fix #426 
Windows:
Linux:
macOS:
Mobile:
=> fix(limel-select): ellipsis when text overflow

src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/components/list/list.scss
How to test in Edge:
- run `npm run docz:build`
- `cd .docz/dist`
- run `serve` 
--> docz site available in windows VM
Windows:
Linux:
macOS:
Mobile:
=> Fix picker icons in edge

Jenkinsfile
We are now running commitlint as a GitHub Action instead.
=> ci(jenkinsfile): remove commitlint step from Jenkins build pipeline

src/components/input-field/input-field.tsx, src/examples/input-field/input-field-text-inline.tsx, src/examples/input-field/input-field-text.tsx
Windows:
Linux:
macOS:
Mobile:
=> feat(input-field): add support for a helper text next to the input field

src/components/dialog/dialog.scss
prevent content to hide the header on scroll bounce
Windows:
Linux:
macOS:
Mobile:
=> fix(dialog): prevent header from shrinking due to large body

src/components/grid/grid.scss, src/examples/grid/grid.scss
BREAKING CHANGE: The default row height of the limel-grid component has been set to 2.5rem (40px). The row height of any given instance of limel-grid can be set using the `--lime-grid-cell-height` CSS variable.
Windows:
Linux:
macOS:
Mobile:
=> feat(grid): set default row height to 2.5rem (40px)

src/components/select/select.tsx
Currently we are setting focus on the first item in the list. If the list is empty, this will result in a `cannot read property focus of null` error.
Windows:
Linux:
macOS:
Mobile:
=> fix(select): don't set focus on first item if null

package-lock.json, package.json
This dependency is no longer needed, as we use commitlint via GitHub Actions.
The dependency on `@commitlint/config-conventional` is still needed by commitizen.
Windows:
Linux:
macOS:
Mobile:
=> chore(package): remove dependency on @commitlint/cli

src/components/form/templates/field.ts, src/components/select/select.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(form): remove double titles and descriptions from form fields

src/components/select/select.e2e.ts, src/components/select/select.scss, src/components/select/select.template.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(select): fix `disabled` state that was broken in v26.1.1

src/components/select/select.tsx
fix #573
Windows:
Linux:
macOS:
Mobile:
=> fix(select): correct default selection, which was broken in v26.1.1

src/components/form/form.mdx, src/components/form/form.scss, src/components/form/templates/object-field.ts, src/components/form/templates/types.ts, src/examples/form/nested-form.tsx
Windows:
Linux:
macOS:
Mobile:
=> feat(form): add template for object fields

src/components/select/select.e2e.ts, src/components/select/select.tsx
The change event should not be emitted when component is mounted since it will set focus and scroll
to the component when the page is loaded. The event is only needed on mobile devices that has not a value preselected, and it is enough to send it the first time the menu is opened.
related to #574 #573
Windows:
Linux:
macOS:
Mobile:
=> fix(select): do not emit change event when component is mounted

rollup-plugin-docz-starter.ts
Windows:
Linux:
macOS:
Mobile:
=> fix: prevent multiple instances of docz

src/components/dialog/dialog.scss
`--dialog-height` was not working correctly since the surface of the dialog did not expand to the
actual height of the dialog
fix #590
Windows:
Linux:
macOS:
Mobile:
=> fix(dialog): set dialog surface to 100% height

src/components/form/form.tsx, src/components/form/templates/array-field-collapsible-item.ts, src/components/form/templates/common.spec.ts, src/components/form/templates/common.ts
fix Lundalogik/lime-admin#84
This PR includes fixes for:
- Expand collapsible section when adding a new collapsible field to reveal its content (also updated default title to _New item_ instead of the array index)
- How to choose a section title:
1. Take field with title or name key
2. Take required field
3. Take first occurrence of string field with value
Windows:
Linux:
macOS:
Mobile:
=> Improve collapsible section

src/components/form/templates/array-field-collapsible-item.ts
Windows:
Linux:
macOS:
Mobile:
=> fix(array-field-collapsible-item): open when deep empty

release.config.js
This is a temporary fix. Everything should work just as it has so far, but with release-builds
passing instead of failing at the very last command in the last step. Docs still need to be
published to aws manually, but they should be built and pushed to github by the release-build.
re #571
=> ci(semantic-release): disable publishing of docs to aws, because it doesn't work anyway

package.json, stencil.config.dist.ts, stencil.config.docs.ts, stencil.config.ts
When running `npm run watch` (or `npm start`), lime-elements is built in dev-mode. However, StencilJS does not output the loader files necessary to load lime-elements in Angular when built in this mode. So we add `npm run watch:prod` for building the prod-build with a running watcher, thus gaining the benefits of auto-build while also being able to load the result in lime-webclient.
=> Fix dev build

src/components/icon/icon.tsx
Sometimes the watcher for `name` triggers rendering of the svg before there's a container element present. The error raised gives no clue to which icon is causing trouble, so check if the element is present, and if not, log a message including the name of the icon to the console.
=> fix(icon): log to console instead of raising error when no container found

.github/workflows/greenkeeper.yml
Greenkeeper will only open a PR if there's a successful CI-build on the branch Greenkeeper creates for an update.
=> ci(greenkeeper): add GitHub Actions workflow for Greenkeeper-branches

src/components/tab-bar/tab-bar.mdx, src/components/tab-bar/tab-bar.scss, src/components/tab-bar/tab-bar.tsx, src/components/tab-panel/tab-panel.mdx, src/components/tab-panel/tab-panel.tsx
There are no more tasks right now for the tab-bar and tab-panel and the interfaces are probably how we want them, so we can probably remove the feature switches now :slightly_smiling_face: 
Windows:
Linux:
macOS:
Mobile:
=> feat(tabs): new tab-bar and tab-panel components

src/components/icon/icon.tsx
While the `renderSvg` function is called too early, regularly if not always, it seems it always gets called again, making the icon appear correctly. Thus, the error-level logging is unnecessary.
Windows:
Linux:
macOS:
Mobile:
=> fix(icon): remove unnecessary `console.error` logging

src/components/badge/badge.scss
Badges that have only 1 digit had a stretched shape. This both looks unusual and wastes a bit of space.
Windows:
Linux:
macOS:
Mobile:
=> fix(badge): make badges with one digit appear like a full circle

src/components/chip-set/chip-set.scss
These changes align leading icons more correctly within the chips, since they are slightly smaller than the chip itself, then there should be equal margin around the chip:
old: <img width="303" alt="Screen Shot 2020-04-02 at 13 42 50" src="https://user-images.githubusercontent.com/35954987/78245523-e535d800-74e7-11ea-9764-8291a30dcc66.png">
new:<img width="214" alt="Screen Shot 2020-04-02 at 13 35 59" src="https://user-images.githubusercontent.com/35954987/78245136-37c2c480-74e7-11ea-9c10-82a8b2f8ef7d.png">
... and also makes the remove (x) buttons on chips better:
It's hard to know whether the cursor is hovering the (x) buttons that remove chips, or whether it's hovering the chip itself. These two of course result in totally different consequences. Therefore it's important to give proper …
=> Improve chip styles

src/components/chip-set/chip-set.scss, src/style/mixins.scss
This is start of a process for unifying the look & feel and behaviour of clickable elements such as Chips, Buttons, Select dropdowns, etc... starting with Chips
Windows:
Linux:
macOS:
Mobile:
=> Elevated chips

src/components/tab-bar/tab-bar.scss, src/components/tab-panel/examples/tab-panel.scss
fix Lundalogik/lime-elements#690
Vanilla tabs from Material Design have two major problems. Firstly, they are ugly and lifeless, too flat and rigid. Secondly, the active tab indicator (the accented bottom border) is not a decent visual sign to indicate which tab is active. It looks like a divider, but what you want to do is actually connecting the active tab to its contents, not separating it from its contents, using a divider. A better UI design for tabs is actually something similar to what Google Chrome has. In Chrome, the active tab is visually distinct due to its background color, therefore users notice it directly. It also looks connected to what is rendered below it, with a minimalist design.
**GIF Example: Tab Bar**
**GIF Example: Tab Panel**
Here I tried to do the same thing …
=> Better tabs, inspired by Chrome

package.json, src/components/picker/picker.tsx
A debounced version of the searcher function was created and stored when the component was created, but there was no handling of updates, and no handling for missing values. The debounced version will now only be created if the value of the `searcher` property is a function, and if the value is updated, a new debounced version will be created, replacing the old one.
re Lundalogik/crm-feature#1017
Windows:
Linux:
macOS:
Mobile:
=> fix(picker): handle updates to the `searcher` property

src/components/chip-set/chip-set.scss
fix: Lundalogik/lime-elements#711
Windows:
Linux:
macOS:
Mobile:
=> fix(chip-set): make chips truncate when their content is too long

src/components/picker/picker.tsx, src/util/dom.ts
Windows:
Linux:
macOS:
Mobile:
=> fix(picker): ensure picker doesn't crash if its value is set to null

src/components/list/examples/list-striped.tsx, src/components/list/list.mdx, src/components/list/list.scss
Fix: Lundalogik/lime-elements#725
Windows:
Linux:
macOS:
Mobile:
=> New props for lists that need striped styles

src/components/list/examples/list-secondary.tsx, src/components/list/list.scss
fix: https://github.com/Lundalogik/lime-elements/issues/740
Windows:
Linux:
macOS:
Mobile:
=> fix(list): center-align contents of lists with or without secondary text

src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/components/input-field/input-field.scss, src/examples/example.scss
fix: https://github.com/Lundalogik/lime-elements/issues/747
Windows:
Linux:
macOS:
Mobile:
=> Transparent input field background

src/components/icon-button/icon-button.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/768
Use what's written in `area-label` as `title` to improve usability and make it easier to perceive buttons with unclear icons.
Windows:
Linux:
macOS:
Mobile:
=> feat(icon-button): show label for icon button on hover

src/components/chip-set/chip-set.scss
fix: https://github.com/Lundalogik/lime-elements/issues/782
Chips can be selected using keyboard (backspace / arrow-keys) to be deleted. No other action is possible, so the styles are focused on "Delete".
Windows:
Linux:
macOS:
Mobile:
=> fix(chip-set): styles when chip is selected

src/components/input-field/input-field.scss, src/components/select/select.scss
fix: https://github.com/Lundalogik/lime-elements/issues/780
Windows:
Linux:
macOS:
Mobile:
=> Make input labels truncate

src/components/input-field/input-field.tsx
fix: Lundalogik/lime-elements#783
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): fix alignment input field with error icon

src/components/chip-set/chip-set.scss
fix: https://github.com/Lundalogik/lime-elements/issues/789
Use `position: absolut;`, `opacity: 0; `and `z-index: -100;`to really hide the input field and render it below all other chips which are visible.
Note
User doesn't have to click on the `<input>` itself to activate it. They click on the container of it -the picker- to activate the input field and make it `focused`.
Windows:
Linux:
macOS:
Mobile:
=> fix(chip-set): render input really "hidden", when it's hidden.

src/components/dialog/dialog.scss, src/components/dialog/dialog.tsx
This modifies how we set `height`, `max-height`, `width`, and `max-width`, so that we better conform to how MDC is setting those values.
fix #786
Windows:
Linux:
macOS:
Mobile:
=> fix(dialog): fix broken max-height, so that dialog is never taller than viewport

src/components/button/button.scss
fix: https://github.com/Lundalogik/lime-elements/issues/808
Windows:
Linux:
macOS:
Mobile:
=> perf(button): hide spinners to avoid constantly running animations

src/components/select/select.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(limel-select): ensure select element don't crash when it's list element doesn't exist

src/components/table/columns.ts, src/components/table/examples/table-local.tsx, src/components/table/examples/table-remote.tsx, src/components/table/table.mdx, src/components/table/table.tsx, src/components/table/table.types.ts
requires #829
Windows:
Linux:
macOS:
Mobile:
=> feat(table): add support for local and remote sorting

src/examples/props.scss, src/examples/props.tsx
Windows:
Linux:
macOS:
Mobile:
=> docs(props): refresh visual styles with dark-mode support

src/components/select/select.tsx
fix #647 
Windows:
Linux:
macOS:
Mobile:
=> fix(select): dont always focus select on a react update

src/components/date-picker/date.types.ts, src/components/date-picker/pickers/Picker.ts
`no` is a non-standard option used in a lot of Lime CRM databases. We convert `no` to `nb` already,
but we should of course also support using the standard language code for Norsk Bokmål.
Windows:
Linux:
macOS:
Mobile:
=> Add `'nb'` for Norsk Bokmål as permitted language option for date-picker

src/components/date-picker/date-picker.tsx, src/components/date-picker/dateFormatter.ts
Windows:
Linux:
macOS:
Mobile:
=> fix(date-picker): support native picker for mobile devices again

.github/workflows/pr-checks.yml
=> ci(github actions): remove WIP check, since github now has draft PRs

package-lock.json
Windows:
Linux:
macOS:
Mobile:
=> chore(package): update sub-dependency instances of `kind-of` to address vulnerability

src/components/input-field/input-field.scss
I'm not sure exactly when support for this was removed, but it doesn't work now, and we've changed the styles of limel-input so that it's using semitransparent backgrounds, gently tinting whatever background the component is used on, so there's no real need for setting the background colour anyway.
Windows:
Linux:
macOS:
Mobile:
=> docs(input-field): remove documentation for `--background-color` which is no longer supported

src/components/form/widgets/input-field.ts
fix #859 
Should widget support undefined values?
- Should support emitting undefined instead of null if the input field is empty to support non required input field values
- Can have a value of undefined initially, but can never be set back to undefined because to clear a select you would have to select the empty/null option, and since the options of the schema form selects are generated via the schema, and since a jsonschema cannot contain undefined since it is not a valid jsonschema value, select elements do not need to support being set back to undefined
- Can have an initial value of undefined, but once it is selected does not need to ever emit undefined since it doesn't make sense for the component. Checkbox components should only ever emit true/false
- Will need to be verified and …
=> fix(schema-form): emit undefined instead of null for empty value

package-lock.json, package.json, src/components/form/form.tsx, src/components/form/validators/format.ts, src/components/form/validators/index.ts
Sometimes, the validator in rjsf incorectly reports validation errors when dependencies are used
within the schema. The reported error did not make any sense since it complained about properties
that did not exist, neither in the schema or the data that was validated. Using Ajv to validate the
form data does not report any errors, even though rjsf also uses Ajv under the hood.
Windows:
Linux:
macOS:
Mobile:
=> fix(form): use Ajv to validate instead of rjsf

src/components/date-picker/date-picker.tsx, src/components/date-picker/pickers/Picker.ts
This commit ensures that the input element has focus when the datepicker closes. It also fixes a bug
where it could look like several input fields had focus at the same time.
fix #764
Windows:
Linux:
macOS:
Mobile:
=> fix(date-picker): improve handling of focus on the input field

src/components/menu/menu.scss
Instead of the dropdown extending upwards from the bottom of the trigger, covering the trigger
element, make it extend upwards from the top of the trigger.
Windows:
Linux:
macOS:
Mobile:
=> fix(menu): when dropdown is rendered upwards from trigger, do not cover the trigger

src/components/input-field/examples/input-field-error-icon.tsx, src/components/input-field/input-field.tsx
The mdcTextField will not respect the invalid class put onto the containing label component
and will instead reset the classes based on its own calculation of whether or not the component
is valid, likely based on native input attributes such as required and the type. This sync update
forces the mdcTextField into an invalid state if the invalid prop is set, otherwise it
lets mdcTextField determine if the component is valid or not.
* Pull master
* Get lime-elements into the browser somehow
* Insert `<limel-text-field invalid help-text="help text" value=""></limel-input-field>` into the dom
* The text field should be red signifying that it is invalid (since the invalid prop is set). 
* Click to focus the input field
* Click away to blur the input field
* Note that the red styling due to the …
=> fix(input-field): sync invalid state to underlying mdctextfield

src/components/list/list.scss, src/components/menu/menu.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1225
Windows:
Linux:
macOS:
Mobile:
=> fix(menu): force tall bottom menus to render inside the viewport

src/components/tab-bar/tab-bar.tsx
fix: Lundalogik/lime-elements#847
Windows:
Linux:
macOS:
Mobile:
=> fix(tab-bar): remove limel-icons when no icon name provided  in limel-tab-bar

src/components/tab-bar/tab-bar.tsx
fix: Lundalogik/lime-elements#852
Windows:
Linux:
macOS:
Mobile:
=> fix(tab-bar): fix tab-bar crashes when previous tabs are undefined

src/components/list/list.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1233
Windows:
Linux:
macOS:
Mobile:
=> fix(list): tall menus render outside screen on Safari iOS+address bar

src/components/button-group/button-group.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1293
Windows:
Linux:
macOS:
Mobile:
=> fix(button-groups): make entire chip look clickable

src/components/table/partial-styles/tabulator-custom-styles.scss, src/components/table/table.scss
Trying to make the new tables look more similar to the old tables, as internally people experience the old tables as less boring 🙃
This PR also removes a layout misalignment in the tables with custom styles.
Windows:
Linux:
macOS:
Mobile:
=> Spacier tables

src/components/button-group/button-group.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1320
Windows:
Linux:
macOS:
Mobile:
=> fix(button-group): remove visual defects on iOS

src/global/core-styles.scss
This reverts commit 5b27cb650e816d69594e72068cf897fb3d039b61.
BREAKING CHANGE: The color palettes should be imported by the consumer, as described in the
documentation and the release notes for v27.0.0. The reverted change was a mistake due to
miscommunication. Our apologies.
Re #924
Windows:
Linux:
macOS:
Mobile:
=> revert(core-styles): revert "let color palette be exported & accessible in webclient"

src/components/linear-progress/linear-progress.tsx
the `<div class="mdc-linear-progress__buffering-dots" />` is not used/offered by lime elements, but the div was rendered, causing a continuously running animation, creating visual disturbance on iPads, and lowering the performance on all platforms.
fix: https://github.com/Lundalogik/crm-feature/issues/1319
Windows:
Linux:
macOS:
Mobile:
=> perf(linear-progress): remove continuous buffering animation

src/components/chip-set/chip-set.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(chip-set): add darker color when hovering over button

src/components/tab-bar/tab-bar.e2e.ts, src/components/tab-bar/tab-bar.tsx, src/components/tab-bar/tabs.spec.ts, src/components/tab-bar/tabs.ts
If tabs are changed rapidly, Stencil will schedule the update of the tabs prop. This will leave us
in a state were the tabs prop still have the old value of the tabs when a new tab is selected, and
thus we will not find the old active tab and cannot deactivate it. To fix this, the tabs prop is
made mutable and we store any changes made to the tabs before we emit the changed tabs in the
`changeTab` event.
fix Lundalogik/crm-feature#1327
Windows:
Linux:
macOS:
Mobile:
=> fix(tab-bar): save tab state by making it mutable

src/components/table/partial-styles/tabulator-arrow.scss, src/components/table/table.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1354
Windows:
Linux:
macOS:
Mobile:
=> fix(table): make Tabulator look more like old tables in web client

src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/components/chip-set/examples/chip-set-input.tsx
fix Lundalogik/crm-feature#1351
Windows:
Linux:
macOS:
Mobile:
=> feat(chip-set): add optional delimiters between chips

src/components/table/columns.spec.ts, src/components/table/columns.ts, src/components/table/table.types.ts, src/global.d.ts
fix Lundalogik/crm-feature#1237
Windows:
Linux:
macOS:
Mobile:
=> fix(table): calculate column width for custom components

src/components/tab-bar/tab-bar.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1336
Windows:
Linux:
macOS:
Mobile:
=> fix(tab-bar): hide unwanted scrollbars on Firefox

src/components/portal/portal.tsx
The popper instance has an event listener on scroll, which causes severe performance issues when
there are a lot of portals on a page e.g. menues in list items etc. The popper instance does not
have to be created until something is actually displayed and needs to be positioned.
Windows:
Linux:
macOS:
Mobile:
=> perf(portal): create popper instance when portal is displayed

src/components/table/columns.spec.ts, src/components/table/columns.ts, src/components/table/element-pool.spec.ts, src/components/table/element-pool.ts, src/components/table/table.tsx
When sorting in the table, new elements were created all the time for the custom components. This is
a waste of resources and also made the table flicker due to elements being expensive to create and
boot up. This PR introduces an object pool for all custom components in a table. As soon as the
table is given new data, all old components will be released from the pool so that they can be
reused.
fix Lundalogik/crm-feature#1384
The last commit of this PR should probably be it's own PR, but it was such a small fix so I included it here anyway!
Windows:
Linux:
macOS:
Mobile:
=> Fix table flickering

src/components/table/table.tsx
Tabulator is requesting data with an AJAX request even though it has been given data when it was
created. It seems unnecessary for us to emit the `load` event as well when this happens, since we
can just initialize the table with the data that has been given to us.
re Lundalogik/lime-crm-components#150
Windows:
Linux:
macOS:
Mobile:
=> fix(table): ignore first ajax request if table is created with data

src/components/table/examples/table-default-sorted.tsx, src/components/table/table.mdx, src/components/table/table.tsx
fix #961
Windows:
Linux:
macOS:
Mobile:
=> feat(table): add default sorting

src/examples/example-value.scss
Windows:
Linux:
macOS:
Mobile:
=> docs: small style fix for multiline values - use full width

src/color-system.md, src/components/button-group/button-group.tsx, src/components/button-group/examples/button-group-icons.tsx, src/components/file/file.tsx, src/components/table/examples/table-low-density.tsx
Those that require more attention
Thanks to https://github.com/elviswolcott/remark-admonitions we can highlight pieces of text in the documentations.
Windows:
Linux:
macOS:
Mobile:
=> docs: use remark-admonitions syntax to highlight instructions

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> chore(package): update eslint to v7.10.0

package.json
We are already using the latest version of tabulator-tables, but package.json was only
requiring an older version. This commit updates package.json to require the currently
latest version, or newer.
Windows:
Linux:
macOS:
Mobile:
=> chore(package): update package.json to match the currently used version of tabulator-tables

src/index.html
And trigger release.
BREAKING CHANGE: Lime Elements no longer supplies ES5-builds. Browser support for ES Modules (esm)
is now required. If you are loading `lime-elements` with one `<script type="module" src="…">` tag
and one `<script nomodule src="…">` tag, you should remove the latter.
Windows:
Linux:
macOS:
Mobile:
=> feat(stencil): update to StencilJS v2

src/components/chip-set/chip-set.tsx
fix Lundalogik/crm-feature#1474
Windows:
Linux:
macOS:
Mobile:
=> fix(chip-set): only emit one startEdit event when focusing on it

src/components/table/partial-styles/tabulator-arrow.scss
fix: https://github.com/Lundalogik/lime-elements/issues/974
Windows:
Linux:
macOS:
Mobile:
=> fix(table): render sorting arrow correctly

src/components/table/columns.spec.ts, src/components/table/columns.ts
fix: https://github.com/Lundalogik/crm-feature/issues/1507
Windows:
Linux:
macOS:
Mobile:
=> fix(table): use default formatter for column if invalid component config is provided

package.json
fix: Lundalogik/crm-feature#1467
This is something you should do according to this:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
This is also a requirement in the latest version of lime-crm-components.
The compiler cannot find the Element interfaces anymore without this
fix (HTMLLimelBadgeElement etc). This caused a lot of tests to fail and
without this fix we would have to use the more generic HTMLElement
interface instead.
The types that we previously had here are already exposed in `index.ts`
Windows:
Linux:
macOS:
Mobile:
=> fix(types): publish auto generated types for the source code

src/components/table/table.tsx
fix Lundalogik/crm-feature#1509
Windows:
Linux:
macOS:
Mobile:
=> fix(table): set max page of tabulator when totalRows is updated

src/components/switch/switch.tsx
fix: Lundalogik/crm-feature#1514
This fix ensures that the switch value is not updated if the
component has not loaded.
Windows:
Linux:
macOS:
Mobile:
=> fix(switch): ensure no exception is thrown in the console

src/components/table/table.tsx
fix Lundalogik/crm-feature#1509
Windows:
Linux:
macOS:
Mobile:
=> fix(table): always update table pages after data has been updated or loaded

src/components/table/partial-styles/tabulator-loader.scss, src/components/table/table.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1452
Now, normally loading only shows a spinner. If loading takes more time, user will see a backdrop that dimmes out the content until everything is loaded.
Windows:
Linux:
macOS:
Mobile:
=> fix(table): loader appears smoothly, instead of blinking into the screen

src/components/input-field/examples/input-field-pattern.tsx, src/components/input-field/input-field.tsx
Required by https://github.com/Lundalogik/limepkg-esign/pull/530
Commit one:
* We want to use the pattern attribute provided on the input tag.
Pattern is not supported for all available input types, for example not for number. How should we handle this? Seems like pattern is not applied when I'm using it with `number` type, so it don't break at least. Is that enough?
Commit two:
* Discover some weirdness. 
I was trying to change `this.value` programmatically from our add-on without keystrokes so it matched the pattern. However, it turned out that `mdcTextValue` was out of sync with `this.value`, so the UI displayed that the value did not match the pattern even though it was a match! …
=> feat(input-field): add support for regex pattern

src/components/input-field/input-field.tsx
In Firefox on Windows, scrolling changes the value of the input, but only if the input is focused. When that happens, the page will not scroll, which should indicate to the user that something else happened instead.
Scroll behaviour when initiating scroll while hovering the input element in different browsers on BrowserStack:
- Windows:
- Firefox updates the value and prevents scrolling of page when input is focused, does not update value and allows scrolling of page when input is not focused
- Chrome and Edge scroll the page, not the value, regardless of focus state
- macOS:
- Chrome, Safari, Firefox, Edge (yes, Edge on macOS 🙄), and Opera all scroll the page, not the value, regardless of focus state
fix Lundalogik/crm-feature#1538
(Check any that applies, it's ok to leave boxes …
=> fix(input-field): do not prevent scrolling while hovering numeric input fields

src/components/tab-bar/examples/tab-bar-with-dynamic-tab-width.tsx, src/components/tab-bar/examples/tab-bar-with-equal-tab-width.tsx, src/components/tab-bar/tab-bar.tsx
Windows:
Linux:
macOS:
Mobile:
=> Docs bring back guidelines for tabs

src/components/input-field/input-field.tsx
fix Lundalogik/crm-feature#1538
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): yet *another* attempt at fixing the issue of scrolling numeric input fields

src/components/input-field/examples/input-field-showlink.tsx, src/components/input-field/input-field.tsx
For inputs of type `email`, `tel`, and `url`, `showLink` can be set to `true` to show a trailing icon with a `mailto:`,`tel:`, or normal link, respectively. The default icon can be overridden using the `trailingIcon` property.
fix Lundalogik/crm-feature#1565
Windows:
Linux:
macOS:
Mobile:
=> feat(input-field): add option `showLink` for type `email`, `tel`, and `url`

src/components/dialog/dialog.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1529
Windows:
Linux:
macOS:
Mobile:
=> fix(dialog): make headers & headings look nicer

src/components/tab-panel/tab-panel.e2e.ts, src/components/tab-panel/tab-panel.tsx
If the tab panel is given a new set of tabs with new IDs, we need to hide all the old panels since
we do not know if one of the old panels should be visible or not. Otherwise content from two tabs
might be visible at the same time.
fix Lundalogik/crm-feature#1494
Windows:
Linux:
macOS:
Mobile:
=> fix(tab-panel): set correct display on panels when new tabs are given

stencil.config.dist.ts, tsconfig.dist.json, tsconfig.json
For some reason there were a lot of errors shown in VSCode for all the example components. The build
still worked, but it's annoying to have errors all over the file when writing new examples. It seems
VSCode used the production version of tsconfig instead of the dev one, so by specifying another file
for the production build we can use the default tsconfig for the whole project.
Windows:
Linux:
macOS:
Mobile:
=> build(tsconfig): use specified tsconfig for production builds

src/components/table/partial-styles/tabulator-paginator.scss, src/components/table/table.tsx
fix: Lundalogik/crm-feature#1551
Windows:
Linux:
macOS:
Mobile:
=> fix(table): show no pagination when only one page exists

guides.ts, src/components/button/button.scss, src/components/button/button.tsx, src/components/button/examples/button-click.tsx, src/components/button/examples/button-reduce-presence.tsx, src/decluttering.md
Adding `has-reduced-presence` to limel-button hides the button when it is disabled and not either loading or showing the checkmark after loading.
fix: Lundalogik/crm-feature#1581
Windows:
Linux:
macOS:
Mobile:
=> feat(button): add `has-reduced-presence` helper class

src/components/button/examples/button-reduce-presence.tsx
Windows:
Linux:
macOS:
Mobile:
=> docs(button): fix broken link to Design Guidelines section of docs

src/components/collapsible-section/collapsible-section.scss
collapsible sections
fix: https://github.com/Lundalogik/crm-feature/issues/1622
Mostly improves experience on Android, where tapping on sections selects the text too
Windows:
Linux:
macOS:
Mobile:
=> fix(collapsible-section): disallow user selection of headings in 

src/components/collapsible-section/partial-styles/expand-icon.scss
This will prevent immediately triggering too many animations while user is
moving  their cursor over sections (like in overview tab in object cards)
fix: https://github.com/Lundalogik/crm-feature/issues/1641
Windows:
Linux:
macOS:
Mobile:
=> fix(collapsible-section): set delay for micro animations

src/components/input-field/examples/input-field-icon-trailing.tsx, src/components/input-field/input-field.scss, src/components/input-field/input-field.tsx, src/components/input-field/partial-styles/trailing-icon.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1650
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): add interactivity & more affordance to trailing icon

src/components/table/columns.spec.ts, src/components/table/columns.ts, src/components/table/table.tsx
fix Lundalogik/crm-feature#1621
Windows:
Linux:
macOS:
Mobile:
=> Table nested properties

src/components/input-field/input-field.tsx
When limel-input-field of type `textarea` had a value, and was hidden at the time of creation (e.g.
when placed inside a limel-dialog or limel-collapsible-section), the label would be missing. This
fixes that problem.
fix #950
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): fix missing label when prefilled and placed in dialog or collapsible-section

src/components/table/partial-styles/tabulator-paginator.scss
tables which don't have aggregation & pagination bars
fix: https://github.com/Lundalogik/crm-feature/issues/1695
Windows:
Linux:
macOS:
Mobile:
=> fix(table): correctly calculate height of tables 

src/components/form/adapters/widget-adapter.ts, src/components/form/examples/basic-schema.ts, src/components/form/form.types.ts
According to react-jsonschema-form the difference between readonly and disabled fields is that the
text value of readonly fields can still be selected, while that is not possible for disabled fields.
None of the default lime-elements components that we map to the standard fields in the form have a
readonly state so we have to treat them the same for now and set the disabled state instead.
`readOnly` is part of the JSON schema specification and setting that will set the correct state as
expected. However, there is nothing in the specification that will allow something to be set as
disabled. Even though the standard components does not support both disabled and readonly, a custom
component could still support it since both are present on the `FormComponent` interface, e.g. the
limel-picker …
=> fix(form): allow fields to be rendered as read only

src/components/tab-bar/tab-bar.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1698
Windows:
Linux:
macOS:
Mobile:
=> fix(tab-bar): reduce original letter spacing in MD tabs

src/components/input-field/examples/input-field-showlink.tsx, src/components/input-field/input-field.tsx, src/components/input-field/link-helper.spec.ts, src/components/input-field/link-helper.ts
I copied the lime-link-helper.service.ts file from the webclient repo that was used in the old card and did some small refactoring changes to it. ~~The type of the input-field cannot be url because then the full url is required. Therefore, it is set to type = 'text'.~~
fix Lundalogik/crm-feature#1628
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): improve action for incomplete url:s, improve target for relative url:s

src/components/dialog/dialog.tsx
fix: #1009
Windows:
Linux:
macOS:
Mobile:
=> Don't render empty footer for limel-dialog

src/components/color-system/examples/color-palette-extended.css, src/components/color-system/examples/colors-in-components.scss, src/components/color-system/examples/contrast-color-palette.scss, src/components/color-system/examples/dark-light-mode.scss, src/components/color-system/examples/extended-color-palette.scss, src/components/color-system/examples/lime-color-palette.scss, src/components/color-system/examples/primary-color-palette.scss, src/components/color-system/examples/ui-color-palette.scss, src/index.html, stencil.config.docs.ts, stencil.config.ts
Since we don't support dark-mode in most components, many of the examples in the docs look completely broken when viewed in dark-mode. This PR makes sure we only load the light-mode version of our colour variables.
Some examples on the _Guidelines / Color System_-page require both dark-mode and light-mode to be supported, so the reader can switch between them and see how that affects the colours. For those examples, we now specifically import the complete set of our colour variables instead.
Windows:
Linux:
macOS:
Mobile:
=> docs: load stylesheet for light-mode only, as we don't fully support dark-mode yet

src/components/icon-button/icon-button.scss, src/components/icon-button/icon-button.tsx
fix: #1065 
Windows:
Linux:
macOS:
Mobile:
=> fix(icon-button): remove sticky mdc ripple effects

.eslintrc.js, src/components/chip-set/chip-set.tsx, src/components/dialog/dialog.tsx, src/components/file/file.tsx, src/components/input-field/examples/input-field-number.tsx, src/components/input-field/input-field.tsx, src/components/linear-progress/linear-progress.tsx, src/components/picker/picker.tsx, src/components/portal/portal.tsx, src/components/select/select.e2e.ts
It's far too easy to abuse the ternary operator to make multiline statements in the code that is hard to read. I suggest we add an ESLint rule to not allow them at all
Windows:
Linux:
macOS:
Mobile:
=> style(eslint): disallow multiline ternary operator

src/components/form/examples/props-factory-form.tsx, src/components/form/examples/props-factory-picker.tsx, src/components/form/examples/props-factory-schema.ts, src/components/form/form.tsx
Windows:
Linux:
macOS:
Mobile:
=> docs(form): add example for `propsFactory`

src/components/chip-set/chip-set.tsx
fix #1064
This code was removed in this commit https://github.com/Lundalogik/lime-elements/commit/4e473a131dab790feb909ead0ed846795aa0ccf5
Is there any reason for us to consider that only one _startEdit_ event is sent?
Windows:
Linux:
macOS:
Mobile:
=> fix(chip-set): emit startEdit event when text field gets focus

src/components/collapsible-section/collapsible-section.scss, src/components/collapsible-section/collapsible-section.tsx
only shown when sections are open, not when collapsed.
fix: https://github.com/Lundalogik/crm-feature/issues/1747
Windows:
Linux:
macOS:
Mobile:
=> fix(collapsible-section): add divider lines on headers

src/components/tab-panel/tab-panel.tsx
Content inside the newly activated tab may need to redraw once visible, so we use the resize event
trick.
fix: Lundalogik/crm-feature#1696
fix: Lundalogik/crm-feature#1697
Windows:
Linux:
macOS:
Mobile:
=> fix(tab-panel): emit resize event to trigger component re-layout when changing tabs

src/components/collapsible-section/collapsible-section.scss, src/components/form/form.scss
Due to layout design,  content of collapsible sections
do not need to have distance with the header.
At the bottom, there is already space as margin.
fix: https://github.com/Lundalogik/lime-elements/issues/1069
Windows:
Linux:
macOS:
Mobile:
=> fix(collapsible-section): make `--body-padding` work only on the sides

package-lock.json, package.json, src/components/input-field/input-field.tsx
Note to reviewer: This needs to be tested in the Lime CRM web client, because the input field hasn't been lagging when running in the docs.
fix: Lundalogik/crm-feature#1719
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): debounce changes to input, to avoid lost characters in some consumer applications

src/components/popover/popover.tsx, src/components/portal/contains.spec.ts, src/components/portal/contains.ts, src/components/portal/portal.tsx
If the popover contains e.g. a limel-select, the dropdown of the select will be placed inside a
limel-portal while the popover content is inside another portal. Clicking inside the select dropdown
should not emit a close event, se we have to go back through all the portals to the source element
tree when deciding if the event should be emitted or not.
Windows:
Linux:
macOS:
Mobile:
=> fix(popover): do not emit close event when clicking inside nested portals

src/components/table/columns.ts
This PR makes it possible to add event listeners to custom components of the table view, both in the header and in the cells
Windows:
Linux:
macOS:
Mobile:
=> Table component events

package-lock.json, package.json
This just updates the dev-dependency, which is used to provide icons for the published
documentation. In production, the consumer of lime-elements is responsible for providing the icons.
fix: Lundalogik/crm-feature#1788
Windows:
Linux:
macOS:
Mobile:
=> chore(package): update dev-dependency on lime-icons8 from v2.1.0 to v2.2.1

src/components/input-field/examples/input-field-showlink.tsx, src/components/input-field/input-field.e2e.ts, src/components/input-field/input-field.scss, src/components/input-field/input-field.tsx, src/components/input-field/input-field.types.ts
- fix(input-field): correctly link the label to the input or textarea element
- test(input-field): add tests for input-field
- refactor(input-field): duplicate less code
- refactor(input-field): add some missing typings
- feat(input-field): add `type='urlAsText'`, allowing urls that are not fully qualified
fix: #1071
fix: Lundalogik/crm-feature#1595
Windows:
Linux:
macOS:
Mobile:
=> input-field: fix small bug, add tests, refactor, add small feature to input-field

src/components/menu-surface/menu-surface.tsx, src/components/menu/menu.scss, src/components/picker/picker.scss, src/components/picker/picker.tsx, src/components/portal/portal.scss, src/components/portal/portal.tsx, src/components/select/select.scss, src/components/select/select.template.tsx
The popper needs to recalculate on which side the container should flip at when the container's
dimension changes
fix Lundalogik/crm-feature#1722
fix Lundalogik/crm-feature#1705
Review:
Windows:
Linux:
macOS:
Mobile:
=> fix(portal): popper is updated when container height is updated

src/components/table/examples/header-menu.scss, src/components/table/examples/header-menu.tsx, src/components/table/examples/table-header-menu.tsx, src/components/table/partial-styles/header-component.scss
fix: Lundalogik/crm-feature#1806
Windows:
Linux:
macOS:
Mobile:
=> fix(table): correct alignment for custom components in column header

src/components/input-field/input-field.e2e.ts, src/components/input-field/input-field.scss, src/components/input-field/input-field.tsx
fix: #1128
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): remove unnecessary validation when using `urlAsText`

src/components/date-picker/flatpickr-adapter/flatpickr-adapter.scss
The problem was that the text color of the options in the select menu was set to white. Firefox uses
white background in a select menu. Now we don't override the default color of the select options.
fix Lundalogik/crm-feature#1770
Windows:
Linux:
macOS:
Mobile:
=> fix(flatpickr-adapter): fix bad contrast in month select in Firefox

src/components/collapsible-section/collapsible-section.scss
I think this bug was introduced by using `overflow:hidden` in fix(collapsible-section): use better default colors for header and body 7b7527fe02144a0b8561a7f0192cf3b569d5d569 . I don't know if there was a reason for adding overflow hidden but everything seems to work when remove it. 
fix Lundalogik/crm-feature#1739
Windows:
Linux:
macOS:
Mobile:
=> fix(collapsible-section): fix chopped letters in section-headers

src/components/table/partial-styles/header-component.scss, src/components/table/table.scss
Also make sure that their titles can truncate when
column header size has changed.
fix: https://github.com/Lundalogik/crm-feature/issues/1815
Windows:
Linux:
macOS:
Mobile:
=> fix(table): make col headers respect component's initial width

src/components/list/list.scss, src/components/select/examples/select-narrow.tsx, src/components/select/examples/select-with-icons.tsx, src/components/select/option.types.ts, src/components/select/select.scss, src/components/select/select.template.tsx, src/components/select/select.tsx
according to size rhythm guidelines
fix: https://github.com/Lundalogik/crm-feature/issues/1790
Windows:
Linux:
macOS:
Mobile:
=> feat(select): enable adding icons to select options

src/components/list/list.scss
fixes this problem, where top corners didn't get correct radius:
Windows:
Linux:
macOS:
Mobile:
=> fix(list): border radius on all corners when only 1 item is displayed

src/components/popover/examples/popover.scss
Windows:
Linux:
macOS:
Mobile:
=> docs(popover): fix wrong property name in example

src/components/checkbox/checkbox.scss
this improves usability and makes it more
clear which box is checked
Windows:
Linux:
macOS:
Mobile:
=> fix(checkbox): use default material design style for checked state

.github/workflows/pr-checks.yml
Windows:
Linux:
macOS:
Mobile:
=> ci(pr-checks.yml): split publishing of docs into separate job, so failure does not fail the ci job

src/components/menu-surface/menu-surface.tsx, src/components/picker/picker.tsx
fix #1062
Windows:
Linux:
macOS:
Mobile:
=> fix(menu-surface): do not kill click events when clicking in an allowed element

src/components/button/button.scss
and do not occupy any visual width in the UI
fix: https://github.com/Lundalogik/crm-feature/issues/1890
Windows:
Linux:
macOS:
Mobile:
=> fix(button): make buttons with has-reduced-presence really disappear

src/components/header/examples/header.scss, src/components/header/examples/header.tsx, src/components/header/header.scss, src/components/header/header.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/1888
Windows:
Linux:
macOS:
Mobile:
=> feat(header): add support for `supporting-text`

src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/components/chip-set/examples/chip-icon-colors.tsx, src/components/chip-set/examples/chip-set-input.scss, src/components/chip-set/examples/chip-set-input.tsx
Strong dominant colors make chips or buttons look like CTAs (Call To Action elements). This should be avoided and colors should be used to communicate meaningful messages or attract attention where needed.
Default styles should be neutral.
fix: https://github.com/Lundalogik/crm-feature/issues/1886
Windows:
Linux:
macOS:
Mobile:
=> fix(chip-set): update `--icon-color` default value to `rgb(var(--contrast-1100))`

src/components/file/examples/file-accepted-types.tsx, src/components/file/file.tsx
fix: #1174
Windows:
Linux:
macOS:
Mobile:
=> feat(file): add accept prop to filter selectable file types

src/components/popover/popover.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/1902
Windows:
Linux:
macOS:
Mobile:
=> fix(popover): add forgotten border radius prop for popover

src/components/popover-surface/popover-surface.scss, src/components/popover-surface/popover-surface.tsx, src/components/popover/examples/popover.tsx, src/style/internal/z-index-variables.scss, src/style/shadows.scss
makes most sense when used with `:focus-visible`
fix: https://github.com/Lundalogik/crm-feature/issues/1868
Windows:
Linux:
macOS:
Mobile:
=> fix(shadows): add shadow styles to use for `focused` elements

src/components/select/select.scss
requires: https://github.com/Lundalogik/lime-elements/pull/1179
Windows:
Linux:
macOS:
Mobile:
=> fix(select): better visualize `focused` with keyboard

.eslintrc.js, src/components/form/form.types.ts, src/components/form/internal.types.ts, src/components/form/templates/object-field.ts, src/components/form/templates/types.ts, src/components/form/widgets/types.ts
Add new property `collapsibleDefaultOpen` to interface `LimeSchemaOptions`.
fix: Lundalogik/crm-feature#1609
Windows:
Linux:
macOS:
Mobile:
=> feat(form): allow collapsible-sections to be loaded either open or closed

src/components/icon-button/icon-button.scss
fix: https://github.com/Lundalogik/crm-feature/issues/1878
Windows:
Linux:
macOS:
Mobile:
=> fix(icon-button): visualize focus state when navigating with keyboard

src/components/tab-bar/partial-styles/tab-bar-scroller.scss, src/components/tab-bar/tab-bar.scss, src/components/tab-bar/tab-bar.tsx
This happens when clicking fast on the `left` or `right` scroller buttons.
Now they stay in place while user hovers, but look kind of disabled.
They also disappear with a delay.
They're still clickable though, but that's because we can't access
the styles of `limel-icon-button` from outside.
fix: https://github.com/Lundalogik/crm-feature/issues/1862
Windows:
Linux:
macOS:
Mobile:
=> fix(tab-bar): prevent unintended clicks on the last tab

src/components/date-picker/date-picker.scss, src/components/date-picker/date-picker.tsx
Copy of fix from #1137 but for limel-date-picker.
Windows:
Linux:
macOS:
Mobile:
=> fix: pass z-index to datepicker portal

src/components/picker/examples/picker-leading-icon-example.tsx, src/components/picker/picker.tsx
Windows:
Linux:
macOS:
Mobile:
=> feat(picker): add leading icon to picker

src/components/date-picker/date-picker.tsx
Ensure that you cannot open the picker when the input field is enabled
Windows:
Linux:
macOS:
Mobile:
=> fix(date-picker): ensure picker respects the `disabled` property

src/components/popover/popover.scss, src/components/popover/popover.tsx, src/index.html
Complimentary PR to #1137, adding CSS variable for the popover z-index so it renders correctly with other elements.
Before: Using popover with button as the trigger inside a limel-dialog shows the dialog on top of the popover
After: Using popover with icon button as trigger inside a limel-dialog, where a limel-select is used as the popover content
Windows:
Linux:
macOS:
Mobile:
=> feat(popover): add consumer-overridable css property `--popover-z-index`

src/components/checkbox/checkbox.tsx, src/components/chip-set/chip-set.tsx, src/components/date-picker/date-picker.tsx, src/components/file/examples/file.tsx, src/components/file/file.tsx, src/components/input-field/input-field.tsx, src/components/select/select.tsx, src/components/slider/slider.tsx, src/components/switch/switch.tsx
For most components, the properties do the same thing, and either can be used. In those cases, the addition of `readonly` is only to allow a more consistent interface between this and more complicated input components which do differentiate between the two.
For a few more complicated components, there is a difference between disabled and readonly, where readonly disallows changes to the value, but allows other interactions with the component, whereas disabled disallows all interaction.
This PR also includes a fix for a bug I found while making these changes to `limel-file`.
fix: #1195
Windows:
Linux:
macOS:
Mobile:
=> Add `readonly` property alongside `disabled` for all input components

src/components/chip-set/chip-set.tsx, src/translations/da.ts, src/translations/en.ts, src/translations/fi.ts, src/translations/nl.ts, src/translations/no.ts, src/translations/sv.ts
Windows:
Linux:
macOS:
Mobile:
=> feat(chip-set): make clear all chips button's label translatable

src/components/form/fields/schema-field.ts
Windows:
Linux:
macOS:
Mobile:
=> fix(form): custom form components can be set to readonly in schema

src/components/form/widgets/date-picker.ts, src/components/form/widgets/input-field.ts
fix: https://github.com/Lundalogik/crm-feature/issues/1960
Windows:
Linux:
macOS:
Mobile:
=> Input fields emit null instead of undefined

src/components/button/button.scss
and no label
fix: https://github.com/Lundalogik/crm-feature/issues/1973
Windows:
Linux:
macOS:
Mobile:
=> fix(button): render it a perfect square when there is only an icon

src/components/menu/menu.tsx
The default button was unstyled and we wouldn't want anyone to use it. Additionally, supplying a
custom trigger element is trivial, so there's no reason not to expect the consumer to do so.
Further, the default element seems to have been rendered every time the component re-rendered, even
though it was never seen by the user. Ergo: kill it with fire!
Fixed position was used to get around a bug in the placement of the menu. This bug has since been
fixed, which makes this attribute obsolete.
fix: #1201
Windows:
Linux:
macOS:
Mobile:
=> limel-menu: deprecate some old stuff

src/components/tab-bar/tab-bar.scss
Focused tab does not require an extra click outside of it to lose
its styles which indicate that it is `focused`
fix: https://github.com/Lundalogik/crm-feature/issues/1969
Windows:
Linux:
macOS:
Mobile:
=> fix(tab-bar): improve visualization of focus state

src/components/button-group/button-group.scss, src/components/chip-set/chip-set.scss
Visualizes keyboard navigation on Chrome & Firefox
only when non-pointer input is being used,
e.g. tabbed into using keyboard
fix: https://github.com/Lundalogik/crm-feature/issues/1967
Windows:
Linux:
macOS:
Mobile:
=> fix(chip-set): visualize keyboard navigation for chips

src/components/dialog/dialog.tsx, src/components/dialog/examples/dialog-nested-close-events.tsx
fix: #1200
Windows:
Linux:
macOS:
Mobile:
=> docs(dialog): add info and example regarding "nested" `close` events inside a dialog

src/components/icon-button/icon-button.scss
Windows:
Linux:
macOS:
Mobile:
=> Make sure the icon is dead center regardless of the size of the limel-icon-button

src/global/core-styles.scss, src/style/internal/mdc-variables.scss
Some css variables are not defined correctly. Move them to the global stylesheet file, and define
them on `:root` instead of `:host`.
fix: Lundalogik/crm-feature#2056
Windows:
Linux:
macOS:
Mobile:
=> fix(styles): define css variables once on `:root` instead of on every `:host`

src/components/dialog/dialog.tsx
The check for a slot named button now actually works and is called before renderFooter, which was
not the case in the initial implementation.
`<footer>` is always there in the current implementation and breakpoints shows that `renderFooter` gets called before `initialize`, thus always showing the footer element.
The breakpoint also showed that `initialize` was called from `componentDidLoad` and this fix moves the query for the slot named `button` to `componentWillLoad` which makes the feature work as intended.
Windows:
Linux:
macOS:
Mobile:
=> fix(dialog): query host element before renderFooter is called

src/components/list/list.scss, src/style/internal/z-index-variables.scss
in Chrome on Windows, menus flicker when they
have a scroll bar and user hovers on them.
fix https://github.com/Lundalogik/crm-feature/issues/2090
Windows:
Linux:
macOS:
Mobile:
=> fix(list): prevent flickering of scrollable menus

src/components/input-field/input-field.scss, src/components/input-field/partial-styles/_cropped-label-hack.scss, src/style/internal/shared_input-select-picker.scss
fix: Lundalogik/crm-feature#1671
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): prevent labels getting cut off when input field is focused

src/components/shadows/examples/shadow-examples.scss, src/components/shadows/examples/surface-shadows-bad-usage.scss, src/components/size/examples/size-edge-case.scss, src/examples/example-value.scss
Note: requires latest version of Kompendium
Windows:
Linux:
macOS:
Mobile:
=> chore(docs): make text colors in examples work better with the new Kompendium in dark mode

src/components/form/form.tsx
fix Lundalogik/lime-elements#1235
Windows:
Linux:
macOS:
Mobile:
=> valid decimal values in the form component is no longer reported as invalid

src/components/slider/examples/slider-multiplier-percentage-colors.tsx, src/components/slider/examples/slider-multiplier.tsx, src/components/slider/examples/slider.tsx, src/components/slider/partial-styles/_readonly.scss, src/components/slider/partial-styles/percentage-color.scss, src/components/slider/slider.scss, src/components/slider/slider.tsx
Windows:
Linux:
macOS:
Mobile:
=> For sliders, make `readonly` and `disabled` visually distinct

src/components/slider/slider.tsx
fix Lundalogik/crm-feature#2114
Windows:
Linux:
macOS:
Mobile:
=> the slider be able to use the configured step incase decimals/percentage

src/components/form/adapters/widget-adapter.ts
fix: Lundalogik/crm-feature#2071
Windows:
Linux:
macOS:
Mobile:
=> feat(form): add support for readonly property on form fields

src/components/form/widgets/input-field.ts
This fixes so that the form no longer considers it self as valid when a text field that is
required is set to empty
fix Lundalogik/crm-feature#2112
Windows:
Linux:
macOS:
Mobile:
=> fix(form): an empty required text field is considered invalid

src/components/input-field/input-field.tsx
When adding text in the middle of an existing string in the input field the cursor sometimes jumps
to the end of the input.
fix #1255
Windows:
Linux:
macOS:
Mobile:
=> fix(input): cursor jumps to end of input when rapidly typing

src/components/switch/examples/switch.tsx, src/components/switch/partial-styles/_readonly.scss, src/components/switch/switch.tsx
fix https://github.com/Lundalogik/lime-elements/issues/1257
Windows:
Linux:
macOS:
Mobile:
=> fix(switch): make switch keep correct styles when readonly is true or false

src/components/checkbox/checkbox.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(checkbox): use cursor style pointer to indicate label can be clicked

src/components/select/examples/select-multiple.tsx, src/components/select/examples/select.tsx, src/components/select/partial-styles/_readonly.scss, src/components/select/select.scss, src/components/select/select.template.tsx, src/components/select/select.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/2160
Windows:
Linux:
macOS:
Mobile:
=> feat(select): make `readonly` and `disabled` visually distinct

src/components/input-field/input-field.scss
fix https://github.com/Lundalogik/crm-feature/issues/2222
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): truncate `formatted-input` for type number

src/components/chip-set/chip-set.scss
fix: Lundalogik/crm-feature#2231
Windows:
Linux:
macOS:
Mobile:
=> fix(chip-set): fix broken focus highlighting for keyboard navigation

src/components/dialog/dialog.scss, src/components/dialog/examples/dialog-closing-actions.tsx, src/components/dialog/examples/dialog-form.scss, src/components/dialog/examples/dialog-form.tsx, src/components/dialog/examples/dialog-fullscreen.tsx, src/components/dialog/examples/dialog-heading.tsx, src/components/dialog/examples/dialog-nested-close-events.tsx, src/components/dialog/examples/dialog-size.tsx, src/components/dialog/examples/dialog.tsx, src/components/flex-container/flex-container.scss
buttons are located in the footer slot.
fix https://github.com/Lundalogik/crm-feature/issues/2232
Windows:
Linux:
macOS:
Mobile:
=> fix(flex-container): make action buttons slot work nicely in `limel-dialog`

src/components/dialog/dialog.scss, src/components/dialog/dialog.tsx, src/components/dialog/dialog.types.ts, src/components/dialog/examples/dialog-heading.scss, src/components/dialog/examples/dialog-heading.tsx, src/components/header/header.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/1908
Windows:
Linux:
macOS:
Mobile:
=> fix(dialog): replace `heading` with `limel-header`

src/components/icon/icon.tsx
There was a weird indentation for a whole section in the documentation due to an incorrect line
break and use of the @ sign at the start of a row
Windows:
Linux:
macOS:
Mobile:
=> docs(icon): remove weird indentation

src/components/button/button.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2252 
Windows:
Linux:
macOS:
Mobile:
=> fix(button): prevent icons from shrinking when button is squeezed

package-lock.json, package.json
* **nav:** only render chevron for nav items that have children ([0ee58af](https://github.com/jgroth/kompendium/commit/0ee58af4797600964dd587ec9b30fe60e10a5e98))
* **nav:** in narrow mode, clicking on a nav item with no children now closes the menu ([8688f34](https://github.com/jgroth/kompendium/commit/8688f348b51397eeeae823a15131e7187ed814c1)), closes [#29](https://github.com/jgroth/kompendium/issues/29)
* **nav:** in narrow mode, clicking outside the nav bar now closes it ([888114b](https://github.com/jgroth/kompendium/commit/888114bcdbf180a6e13d07378e6db7220068d886)), closes [#29](https://github.com/jgroth/kompendium/issues/29)
Windows:
Linux:
macOS:
Mobile:
=> chore(package): update kompendium from v0.8.8 to v0.9.0

package-lock.json, package.json
Adds switch for toggling dark-mode, and scrolls the view to the chosen section when navigating.
Windows:
Linux:
macOS:
Mobile:
=> chore(package): update kompendium from v0.9.0 to v0.10.0

src/components/input-field/input-field.tsx, src/components/select/select.template.tsx
This helps keeping the UI consistent and clean,
specially when many `readonly` input fields with and without values are
juxtaposed with each other.
fix https://github.com/Lundalogik/crm-feature/issues/2230
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): render empty `readonly` field with a `–` value & `--float-above` label

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> chore(package): update kompendium from v0.10.0 to v0.10.1

src/components/chip-set/chip-set.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(chip-set): make label truncate correctly when there is a leading icon

src/components/menu-surface/menu-surface.scss, src/components/menu/menu.scss, src/components/menu/menu.tsx
We offer the possibility of tweaking `--menu-surface-width`
for `limel-menu`. But this was not working, because `limel-menu-surface`
would go into `limel-portal--container`;
and no defined variable would follow.
Windows:
Linux:
macOS:
Mobile:
=> fix(menu): pass css props defined for menu to portal

src/components/table/table.scss
fix https://github.com/Lundalogik/crm-feature/issues/2269
Windows:
Linux:
macOS:
Mobile:
=> fix(table): center align loading spinner

src/components/chip-set/chip-set.tsx, src/components/chip-set/chip.types.ts, src/components/file/examples/file-composite.tsx, src/components/file/examples/file-custom-icon.tsx, src/components/file/examples/file.tsx, src/components/file/file-metadata.ts, src/components/file/file.tsx, src/components/file/icon-background-colors.ts, src/components/file/icon-fill-colors.ts, src/components/file/icons.ts
fix: https://github.com/Lundalogik/hack-tuesday/issues/187
fix: https://github.com/Lundalogik/crm-feature/issues/2088
Windows:
Linux:
macOS:
Mobile:
=> feat(file): display icon of most common filetypes on chip

src/components/collapsible-section/collapsible-section.scss, src/components/collapsible-section/collapsible-section.tsx
Users now can tab and select section headers,
and also press the ENTER key to open or closes a section
fix: https://github.com/Lundalogik/crm-feature/issues/1972
Windows:
Linux:
macOS:
Mobile:
=> feat(collapsible-section): enable keyboard navigation and interaction

src/components/form/examples/custom-component-form.tsx, src/components/table/examples/table-custom-components.tsx, src/components/table/examples/table-header-menu.tsx, src/components/table/table.tsx
The interfaces for custom components, both for limel-form and for limel-table, have been too easy to miss. This PR adds descriptions to the relevant examples, including links to the documentation for the relevant interfaces.
Windows:
Linux:
macOS:
Mobile:
=> Improve docs for limel-form and limel-table

src/components/table/table.tsx
fix: Lundalogik/crm-feature#2027
Windows:
Linux:
macOS:
Mobile:
=> fix(table): don't scroll table to the left after each reload

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> chore(package): upgrade Kompendium from v0.10.1 to v0.10.2

.github/workflows/pre-release.yml, release.config.js
Including `[no ci]` will prevent GitHub Actions from running the workflow
at all. But we want to run the release workflow even if the last commit
happens to be a pre-release commit. So we use `[release]` instead of
`[no ci]`. That way, the workflow will run, and we can skip or run stuff
depending on what workflow we're in.
Windows:
Linux:
macOS:
Mobile:
=> ci(semantic-release): use `release` instead of `no ci` in release commits

package-lock.json, package.json
This gives access to newly added logos of Lime Technologies,
as well as a few of Lime products, such as CRM, Go, and Elements;
which can now be used as `limel-icon`.
Windows:
Linux:
macOS:
Mobile:
=> feat(package): upgrade @lundalogik/lime-icons8 from v2.4.0 to v2.5.0

src/components/chip-set/chip-set.scss, src/style/internal/shared_input-select-picker.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2295
Windows:
Linux:
macOS:
Mobile:
=> chore(style): remove unused mixin for `label--float-above`

src/components/list/list.scss, src/components/list/partial-styles/_static-actions.scss, src/components/picker/actions.types.ts, src/components/picker/examples/picker-static-action.tsx, src/components/picker/picker.tsx, src/style/_theme-color-variables.scss, src/style/internal/z-index.scss
This PR is a part of a bigger feature that requires changes in multiple repos.
These are the PRs that belong together.
- ~[Lime webclient](https://github.com/Lundalogik/lime-webclient/pull/1839)~ replaced by [Lime webclient](https://github.com/Lundalogik/lime-webclient/pull/1845)
- [Lime core](https://github.com/Lundalogik/lime-core/pull/917)
- ~[Lime crm components](https://github.com/Lundalogik/lime-crm-components/pull/519)~ replaced by [Lime crm components](https://github.com/Lundalogik/lime-crm-components/pull/530)
- [Lime elements](https://github.com/Lundalogik/lime-elements/pull/1282) (Current)
**Background:**
fix: Lundalogik/crm-feature#2238
The wanted feature is to be able to create a new limeobject directly in the object form, both in create new dialog and the object overview …
=> Static actions picker

src/components/chip-set/chip-set.tsx
Fix: https://github.com/Lundalogik/crm-feature/issues/1871
Windows:
Linux:
macOS:
Mobile:
=> fix(chip-set): show delimiter directly after first chip

src/components/picker/picker.tsx
fix https://github.com/Lundalogik/crm-feature/issues/2103
Windows:
Linux:
macOS:
Mobile:
=> feat(picker): make delimiter of chip-set available in picker

src/components/table/table.scss, src/components/table/table.tsx
We could use tabulator's placeholder option and send in a DOM node instead of a string. However, I
think it is an easier solution not to use the placeholder option  and instead just render the empty
message in the render method.
fix Lundalogik/crm-feature#2326
Windows:
Linux:
macOS:
Mobile:
=> fix(table): don't show empty message when loading the table

src/components/table/table.scss
When a table is empty, the `tabulator-empty-text` div is rendered.
It covered the headers and therefore blocked any clicks.
With `pointer-events: none;` we let clicks go through.
fix https://github.com/Lundalogik/crm-feature/issues/2333
Windows:
Linux:
macOS:
Mobile:
=> fix(table): make column headers of a empty tables clickable

src/components/picker/examples/picker-multiple.tsx, src/components/picker/picker.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/2332 
Windows:
Linux:
macOS:
Mobile:
=> fix(picker): show delimiter only when multiple is true

src/components/slider/partial-styles/percentage-color.scss, src/style/colors.scss
This way, any component –internal or external– that needs to visualize
a percentage using Lime Technologies' color conventions
can do so by reusing our CSS variable names.
This PR is needed for https://github.com/Lundalogik/crm-feature/issues/2338
Windows:
Linux:
macOS:
Mobile:
=> feat(style): make Lime's percentage colors universally available

src/components/select/select.scss
fix https://github.com/Lundalogik/lime-elements/issues/1365
Windows:
Linux:
macOS:
Mobile:
=> fix(select): give more space to label by reducing dropdown-icon's margin

src/style/internal/shared_input-select-picker.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2348
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): fix cut-off label for input fields with leading icon

src/components/list/list.scss
fixes #1370, Lundalogik/limepkg-workorder-list#38
Tested with modified "list with actions" example to get the combination action menu + badge icons.
```typescript
public render() {
return (
<limel-list
badgeIcons={true}
iconSize="large"
items={this.items}
onSelect={this.onSelectAction}
/>
);
}
```
**Before**
**After**
Also, margins of the action menu icon are unaffected even when using something different than the default icon size.
UPDATE:
Also makes sure that action menu is vertically centered (ty @Kiarokh @mjlime).
Before and after:
Windows:
Linux:
macOS:
Mobile:
=> fix(list): only apply badge effect to graphic

.github/workflows/release.yml
Because we prefer not to get new commits on `next` between the time we merge `next`
into `main`, and the time the created release commit is merged back to `next`, this
commit changes the release workflow from running on push to running nightly. We also
add a workflow_dispatch trigger.
Windows:
Linux:
macOS:
Mobile:
=> ch(release.yml): run release nightly instead of on push

.github/workflows/release.yml
I realised running nightly does not help for avoiding new commits on `next`, since
we would still have to do the merge from `next` to `main` at a time when no new
commits would be added to `next` between the merge and the release. So scheduling
the release to run nightly actually just made the problem worse 🤦.
Partially reverts 93c54ae59.
Windows:
Linux:
macOS:
Mobile:
=> ci(release.yml): revert back to running on push

package.json
You can now run `npm run test:watch` and have the watcher run _both_ spec and e2e tests 🥳
Windows:
Linux:
macOS:
Mobile:
=> chore(package.json): add script `npm run test:watch`

src/components/menu-list/menu-list-item.types.ts, src/components/menu-list/menu-list-renderer-config.ts, src/components/menu-list/menu-list-renderer.tsx, src/components/menu-list/menu-list.e2e.ts, src/components/menu-list/menu-list.scss, src/components/menu-list/menu-list.tsx, src/components/menu-list/menu-list.types.ts, src/components/menu-list/partial-styles/_has-grid-layout.scss, src/components/menu-list/partial-styles/_static-actions.scss, src/components/menu-list/partial-styles/custom-styles.scss, src/components/menu-list/partial-styles/enable-multiline-text.scss, src/components/menu-list/radio-button/radio-button.scss, src/components/menu-list/radio-button/radio-button.template.tsx, src/components/menu/menu.e2e.ts, src/components/menu/menu.tsx, src/components/menu/menu.types.ts, src/interface.d.ts
**EDIT:** _To clarify, the idea here is to initially make the smallest possible change that completely separates limel-menu from limel-list, so that no future changes made to limel-menu will cause changes to limel-list. This means a lot of duplicated code in this PR, and a lot of dead code too. That will be cleaned up in successive PRs._
This is the first step (step 2 is here: #1417) that will allow us to remove all menu-specific code from limel-list, and all code not necessary for use with limel-menu from limel-menu-list.
Later, it might be possible to make limel-menu-list part of the limel-menu component, but that's an issue for a later step.
To make the changes easier to follow, I've split the change into several steps:
1. The first commit only duplicates the whole folder …
=> Create a duplicate of limel-list, called limel-menu-list, only used by limel-menu

src/components/progress-flow/progress-flow-item/progress-flow-item.scss
The -y causes a scrollbar to appear under certain circumstances related to size of the window and length of the string in the "button".
Windows:
Linux:
macOS:
Mobile:
=> fix: scrollbar showing in progress flow component

src/interface.d.ts
Windows:
Linux:
macOS:
Mobile:
=> fix(menu): remove export of deleted interface

src/components/button-group/examples/button-group-composite.tsx, src/components/chip-set/examples/chip-set-composite.tsx, src/components/form/examples/custom-component-picker.tsx, src/components/form/examples/props-factory-picker.tsx, src/components/table/examples/header-menu.tsx
There were some imports with weird paths, and they caused the build in
`lime-webclient/frontend/admin/` to fail when you had linked a local dev-build.
Windows:
Linux:
macOS:
Mobile:
=> chore: fix weird imports in examples

publish-docs.js
fix: #1433
Windows:
Linux:
macOS:
Mobile:
=> docs: add symlink to latest NEXT-version

src/components/menu/examples/menu-composite.tsx, src/components/menu/menu.tsx
The property `fixed` was deprecated long ago. Removing it reduces complexity of the code slightly,
and also slightly improves performance, since there are some checks we no longer need to perform.
BREAKING CHANGE: The deprecated property `fixed` on `limel-menu` has been removed.
Windows:
Linux:
macOS:
Mobile:
=> perf(menu): remove deprecated property `fixed`

src/components/menu/examples/menu-open-left.tsx, src/components/menu/menu.tsx
Support for using `limel-menu` without supplying your own trigger element has been
deprecated for a long while. Remove that support.
BREAKING CHANGE: Support for using `limel-menu` without supplying you own trigger
element has been removed. The deprecated property `label`, which was only used when
the default trigger element was used, has thus also been removed.
Windows:
Linux:
macOS:
Mobile:
=> perf(menu): remove deprecated support for default trigger

src/components/dialog/dialog.types.ts
The property has been deprecated for a long time, and setting it no longer has any
effect.
BREAKING CHANGE: The deprecated property `badgeIcon` on the interface `DialogHeading`
has been removed. Setting the property already had no effect, but since the property
has now been removed, any consumers that are importing types from
**@limetech/lime-elements** and are setting this property, will get an error when
building. The solution is to simply not set the property.
Windows:
Linux:
macOS:
Mobile:
=> chore(dialog): remove deprecated property `badgeIcon` from `DialogHeading`

src/components/picker/examples/picker-icons.tsx, src/components/picker/examples/picker-static-action.tsx, src/components/picker/picker.tsx
The property `displayFullList` on `limel-picker` is deprecated and setting it has no
effect. Remove it.
BREAKING CHANGE: The deprecated property `displayFullList` on `limel-picker` has been
removed. Setting the property had no effect even before this change, but since the
property has now been removed, any consumers that are importing types from
@limetech/lime-elements and are setting this property, will get an error when
building. The solution is to simply not set the property.
Windows:
Linux:
macOS:
Mobile:
=> chore(picker): remove deprecated and unused property `displayFullList`

src/components/form/form.types.ts, src/components/form/templates/field.ts
The property is deprecated, so remove it.
BREAKING CHANGE: The deprecated property `span` has been removed from the interface
`FormLayoutOptions`. To achieve the same functionality, switch the interface used from
`FormLayoutOptions` to `GridLayoutOptions` and set the property `colSpan` instead.
Windows:
Linux:
macOS:
Mobile:
=> chore(form): remove the deprecated property `span` from `FormLayoutOptions`

src/components/snackbar/snackbar.e2e.ts
This test has been blinking repeatedly for a while now. Just increasing the timout
is a poor fix, but it might help a little.
Windows:
Linux:
macOS:
Mobile:
=> test(snackbar): increase timeout for blinking test

src/components/list/list-item.types.ts
Windows:
Linux:
macOS:
Mobile:
=> fix(list): fix broken import of `MenuItem` so docs builds correctly

src/components/form/form.scss
fix https://github.com/Lundalogik/crm-feature/issues/2467
Windows:
Linux:
macOS:
Mobile:
=> 2467 nested headings in forms

src/components/collapsible-section/collapsible-section.scss
fix https://github.com/Lundalogik/crm-feature/issues/2459
Windows:
Linux:
macOS:
Mobile:
=> fix(collapsible-section): render header in 2 lines first, then truncate

src/components/date-picker/pickers/MonthPicker.tsx
fix: #1455
Windows:
Linux:
macOS:
Mobile:
=> fix(date-picker): prevent month picker from sometimes skipping a year when navigating

src/components/collapsible-section/collapsible-section.e2e.ts, src/components/collapsible-section/collapsible-section.tsx
To test the new tests, I would recommend looking at the test description, then breaking the code, so that it no longer does what the test description says, then check that the test fails.
So, for something like `limel-collapsible-section > with a header and body > when clicking the header > opens`, you might want to comment out the code inside the `onClick` function. Then check that that specific test fails in the expected way. If other tests fail (which some probably will), check that it makes sense that they fail because of the change you made. Then undo the change, and repeat for the next test 🙂
Windows:
Linux:
macOS:
Mobile:
=> Add tests and minor fixes for collapsible-section

src/components/list/list.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/1424
Users can jump to an item in a list by typing the first X letters.
Example:
┌──────────────┐
│    Robin  <----- Active selection
├──────────────┤
│     Alex     │
├──────────────┤
│    Frank     │
├──────────────┤
│   Francis    │
└──────────────┘
* The user types "Fra" -> Selection in list will jump to "Frank"
* The user types "A" -> Selection in list will jump to "Alex"
* The user types "R" -> Selection in list will jump to "Robin"
* The user types "Franc" -> Selection in list will jump to "Francis"
Windows:
Linux:
macOS:
Mobile:
=> feat(limel-list): enable keyboard typeahead navigation

src/components/form/templates/array-field.ts
also use a simpler icon
fix: https://github.com/Lundalogik/crm-feature/issues/2495
Windows:
Linux:
macOS:
Mobile:
=> fix(form): use `title` as label on button-add-new

src/components/list/list.scss
fix https://github.com/Lundalogik/lime-elements/issues/1467
Windows:
Linux:
macOS:
Mobile:
=> fix(list): make list items to be as wide as the list

src/components/progress-flow/progress-flow-item/progress-flow-item.scss
in some bizarre way, (probably when the component is embedded
in another web-component) iOS could not render the dividers correctly
due to combination of `overflow` and `transform`.
fix: https://github.com/Lundalogik/crm-feature/issues/2453
Windows:
Linux:
macOS:
Mobile:
=> fix(progress-flow): fix rendering problem on iOS

src/components/color-picker/color-picker-palette.scss, src/components/color-picker/color-picker-palette.tsx, src/components/color-picker/color-picker.scss, src/components/color-picker/color-picker.spec.tsx, src/components/color-picker/color-picker.tsx, src/components/color-picker/examples/color-picker-readonly.tsx, src/components/color-picker/examples/color-picker.tsx, src/components/color-picker/swatches.ts, src/design-guidelines/color-system/examples/shared-styles.scss
Things left to fix:
fix https://github.com/Lundalogik/crm-feature/issues/2503
Windows:
Linux:
macOS:
Mobile:
=> feat: add `limel-color-picker` component

src/components/color-picker/color-picker.spec.tsx, src/components/color-picker/color-picker.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/2522
Windows:
Linux:
macOS:
Mobile:
=> fix(color-picker): render the tooltip if there is a tooltip label

src/components/color-picker/color-picker.scss, src/components/color-picker/partial-styles/_lime-admin-hack.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2524
Windows:
Linux:
macOS:
Mobile:
=> fix(color-picker-pallet): add support for deprecated lime colors

src/components/slider/examples/slider-multiplier.tsx, src/components/slider/slider.tsx
When step is configured and the initial value is not a multiple of the step value, the slider will
round the value to the nearest step when it is changed for the first time. After a valid value has
been set, only discrete valid values will be possible to pick.
re Lundalogik/crm-feature#2301 Lundalogik/crm-feature#2419
Windows:
Linux:
macOS:
Mobile:
=> fix(slider): round invalid values to step

src/components/form/adapters/widget-adapter.ts, src/components/form/widgets/select.ts
fix: #1477
Windows:
Linux:
macOS:
Mobile:
=> honor `lime.component.props.disabled` for form components

src/components/menu-list/menu-list.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2491
Windows:
Linux:
macOS:
Mobile:
=> fix(menu-list): add margin to visualize keyboard-focused items

src/components/menu-list/menu-list.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2542
Windows:
Linux:
macOS:
Mobile:
=> fix(menu-list): display: block, to avoid a vertical scroll bar

stencil.config.dist.ts, stencil.config.docs.ts, stencil.config.ts
Once build warning less…
Builds just fine, tests pass. I haven't tested the docs or in lime-webclient yet, so please do! No hurry though 😊
Windows:
Linux:
macOS:
Mobile:
=> chore: remove deprecated config option `namedExports`

src/components/form/examples/custom-error-message-form.tsx, src/components/form/examples/custom-error-message-schema.ts, src/components/form/form.tsx
Make it possible to provide the [transformErrors](https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/form-props/#transformerrors) function to customize the error messages.
Windows:
Linux:
macOS:
Mobile:
=> feat(form): add transformErrors prop

src/components/checkbox/checkbox.scss, src/components/checkbox/checkbox.template.tsx, src/components/checkbox/checkbox.tsx, src/components/checkbox/examples/checkbox-helper-text.tsx, src/components/checkbox/partial-styles/_helper-text.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2516
Windows:
Linux:
macOS:
Mobile:
=> feat(checkbox): add support for displaying `helperText`

src/components/slider/partial-styles/_helper-text.scss, src/components/slider/slider.scss
As a convention, it's better to keep imports at the bottom,
in case they are overriding something.
Also this keep it consistent with other components.
Additionally removed the extension `.scss` as it's not needed.
fix https://github.com/Lundalogik/crm-feature/issues/2592
Windows:
Linux:
macOS:
Mobile:
=> style(slider): move imported partial styles to the last line

src/components/list/list.scss, src/components/menu-list/menu-list-renderer.tsx, src/components/menu-list/menu-list.scss, src/components/menu/examples/menu-basic-secondary-text.scss, src/components/menu/examples/menu-basic-secondary-text.tsx, src/components/menu/menu.tsx
fix https://github.com/Lundalogik/crm-feature/issues/2609
Windows:
Linux:
macOS:
Mobile:
=> Fixes for limel-menu with secondaryText

src/components/checkbox/checkbox.tsx
fix #1527  (that PR contains a visual repro that should not be added to the examples, hence this separate PR with the fix)
when the checkbox is disconnected and the mdc checkbox
instance is destroyed, it will prematurely remove the
animation end handler that removes all the animation
classes mdc adds when interacting with the checkbox.
Windows:
Linux:
macOS:
Mobile:
=> fix(checkbox): clean up animation classes before reconnected

src/components/dialog/dialog.scss
fix: https://github.com/Lundalogik/lime-elements/issues/1525
Windows:
Linux:
macOS:
Mobile:
=> fix(dialog): add padding to the footer in mobile view

src/components/menu-surface/menu-surface.scss, src/components/menu/examples/menu-basic-secondary-text.tsx, src/components/menu/examples/menu-grid.tsx, src/components/menu/menu.scss, src/components/menu/menu.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/2623
Windows:
Linux:
macOS:
Mobile:
=> Specify a default max-width for limel-menu

src/components/input-field/input-field.scss, src/components/select/select.scss, src/components/slider/slider.scss, src/style/internal/shared_input-select-picker.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2624
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): make sure label has our default label color

src/components/table/partial-styles/_row-selection.scss
fix https://github.com/Lundalogik/crm-feature/issues/2641
Windows:
Linux:
macOS:
Mobile:
=> fix(table): fix row selector visual defects, on selected & hovered rows

src/components/table/partial-styles/_row-selection.scss
fix: https://github.com/Lundalogik/lime-elements/issues/1541
Windows:
Linux:
macOS:
Mobile:
=> fix(table): prevent moving the checkbox column

src/components/checkbox/checkbox.scss, src/components/checkbox/partial-styles/_helper-text.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2635
Windows:
Linux:
macOS:
Mobile:
=> fix(checkbox): avoid rendering long labels on the next row below the checkbox

src/components/table/table.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(table): never emit internal row selector column

src/components/table/examples/table-selectable-rows.tsx, src/components/table/table.tsx, src/components/table/table.types.ts
Updating aggregate values only is not currently possible without changing the columns and re-initialize the table.
By adding a new `@Prop` called `aggregates` the user of `<limel-table>` can let the table re-render with new aggregate values. A watcher of the added prop can call Tabulator's `recalc` function to update the values in its calculation row (`bottomCalc`).
Note: The aggregator given by the column definition should have higher priority than the value in the `aggregates` prop. 
This feature is added to support updating the aggregate value as the user selects rows using the `selection` prop added in #1514.
Windows:
Linux:
macOS:
Mobile:
=> feat(table): add aggregates property

src/components/badge/badge.scss
We [refactored limel badge recently](https://github.com/Lundalogik/lime-elements/pull/1577) and made the host a flex. I a badge is placed inside a container that doesn't have enough space for it, it will shrink. This PR fixes that:
Windows:
Linux:
macOS:
Mobile:
=> fix(badge): don't let it shrink in width, when container is too small

src/components/list/list.e2e.ts
My editor said these awaits where unnecessary, as the functions they are awaiting aren't async, and the tests pass without them too.
Windows:
Linux:
macOS:
Mobile:
=> test(list): remove unnecessary awaits

src/components/menu-surface/menu-surface.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2668 
Windows:
Linux:
macOS:
Mobile:
=> fix(menu-surface): avoid extra margin

src/components/table/partial-styles/_row-selection.scss
fix https://github.com/Lundalogik/lime-elements/issues/1609
Windows:
Linux:
macOS:
Mobile:
=> fix(table): correct checkbox target area size in row selectors

src/components/list/list.tsx
Note to the reviewer: There are two commits, one pure refactor and one that changes the functionality. Reviewing them one by one is recommended. I tried adding a regression test for the bug, but couldn't get it to work, and I don't think we should delay getting the bug fix because I'm currently having trouble understanding how to properly test for errors in async functionality involving user input 😅 (My failures at adding a test can be witnessed in #1602)
/ @adrianschmidt
Setting selectedIndex -1 on mdc-list will cause consequential errors.
This happens when none of the items are selected or if the selected prop is missing on the items.
Bug introduced in this commit: https://github.com/Lundalogik/lime-elements/commit/0a2fad6ed61d6c071ce364fb2fb255adbf9c357c
Not sure if this will cause …
=> fix(list): don't set selected index on mdc-list if selected item not found

src/components/table/partial-styles/_row-selection.scss, src/components/table/partial-styles/tabulator-arrow.scss, src/components/table/table.scss
Windows:
Linux:
macOS:
Mobile:
=> Table color corrections

src/components/table/partial-styles/_row-selection.scss, src/components/table/partial-styles/tabulator-custom-styles.scss
fix https://github.com/Lundalogik/crm-feature/issues/2670
⚠️ requires: https://github.com/Lundalogik/lime-elements/tree/1609-fix-checkbox-size-table-
Windows:
Linux:
macOS:
Mobile:
=> 2670 correctly align select all checkbox in low density

src/components/table/table.e2e.ts, src/components/table/table.tsx
- Tabulator has an instance type check on the given element, requiring full e2e tests to be used over `newSpecPage`
- Using e2e tests requires mutation of properties (from the outside, not from the inside ie using `@Prop({ mutable: true  })` after adding the element, thus adding mutability of the selectable prop
- Row selection + select all interaction is not testable (even after waiting for page changes + select event) and is intentionally left out
- This PR does not intend to add a complete set of tests covering all limel-table features, but hopefully we can add more in the future (preferably without e2e tests)
Windows:
Linux:
macOS:
Mobile:
=> add some table tests

src/components/table/table.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/2673
Windows:
Linux:
macOS:
Mobile:
=> fix(table): make 'selectAll' is disabled if the table is empty

src/components/input-field/input-field.scss, src/components/input-field/input-field.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/1624
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): make icons disabled if input-field is empty

.github/dependabot.yml, package-lock.json, package.json
@rjsf/core 4.x makes Lime Admin unusable with certain schemas + data and until further investigation is done, this bump  must be reverted to provide a functional product.
The rjsf playground shows the same error using the problematic schema + data and is caused by the large nested structure and live validation performed.
Windows:
Linux:
macOS:
Mobile:
=> Revert major update of @rjsf/core and configure dependabot to ignore future major updates

src/components/dialog/dialog.tsx
Prompted by a request from @DavidAkkerman:
> Almost a year ago, you helped me solve a problem with the rendering of a dialog in the web client, by advising me to use the dialogservice for creating the dialog. I am now getting questions from several other appers that are running into the same problem, because the first thing everyone does is going to the lime-elements documentation page and copy-paste some code from the examples, which most of the time works really well. However, if you go to the documentation of the dialog, the example just shows that you can render a button and a dialog in the same web component, and that you only have to set the dialog as open when you click the button. I'm guessing it's not possible to use the dialogservice in the example because it's not available, …
=> docs(dialog): add note about opening dialogs in Lime CRM

docs-index.html, publish-docs.js
It's a pita to update the index page, since you have to check out the gh-pages branch to make changes to it. This PR adds the file to the normal branches. When publishing, we always grab the file from the latest published `next`-version.
See the respective commit messages for the small changes I made to the index file.
Update: I added functionality for removing outdated patch versions (we only keep the latest patch version for each minor version—so if we have 1.2.3 and 1.2.4, we remove the 1.2.3 version), and outdated NEXT versions (when we release v35.0.0, all `NEXT-35.0.0-next.*` are removed).
Windows:
Linux:
macOS:
Mobile:
=> Make the index page for docs versions get published from the latest `next`, also update some stuff on that page

.eslintrc.js, src/components/form/fields/schema-field.ts, src/components/form/form.types.ts, src/components/table/table.types.ts
Windows:
Linux:
macOS:
Mobile:
=> eslint: fix false positives from rule `no-shadow`

src/components/table/partial-styles/tabulator-custom-styles.scss
fix https://github.com/Lundalogik/crm-feature/issues/2744
Windows:
Linux:
macOS:
Mobile:
=> fix(table): make sure horizontal scrollbar is shown on windows browsers

.czrc, package-lock.json, package.json
Also remove direct dependency on `commitizen`.
Windows:
Linux:
macOS:
Mobile:
=> chore: use official `cz-conventional-changelog` instead of fork

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> chore(packages): upgrade kompendium from v.0.11.0 to 0.11.1

src/components/picker/picker.tsx
Before: 
It's too grey and hard to read. Also no good distance on the sides.
After:
fix: https://github.com/Lundalogik/crm-feature/issues/2758
Windows:
Linux:
macOS:
Mobile:
=> fix(picker): improve look and readability of empty result message

src/components/form/form.tsx, src/components/form/form.types.ts
fix: https://github.com/Lundalogik/crm-feature/issues/2657
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): avoid unnecessary code error messages at webclient

src/components/progress-flow/progress-flow-item/partial-styles/_selected-indicator.scss, src/components/progress-flow/progress-flow-item/progress-flow-item.scss, src/components/progress-flow/progress-flow.scss, src/style/internal/z-index.scss
The progress-flow component will now have its own stacking content.
So if other elements in the dom have z-index, they will not be covered by
elements of the component which have a z-index.
Windows:
Linux:
macOS:
Mobile:
=> fix(progress-flow): prevent `z-index` overlapping problems by isolating the component

src/components/form/templates/object-field.ts
Set the React JSON schema form object field collapsible sections id to be equal to the schema object
property path.
fix: Lundalogik/crm-feature#1885
Windows:
Linux:
macOS:
Mobile:
=> feat(forms): set rjsf collapsible sections id

src/components/dialog/dialog.scss
When a dialog is displayed fullscreen inside a popup window, the current backdrop creates an ugly
grey border around the dialog element. There should not be a need for a backdrop like that when a
dialog is displayed fullscreen in a popup window.
Windows:
Linux:
macOS:
Mobile:
=> feat(dialog): add CSS properties for max size

package-lock.json, package.json
adds new icons for visualizing widget sizes
fix https://github.com/Lundalogik/crm-feature/issues/2859
Windows:
Linux:
macOS:
Mobile:
=> feat(packages): upgrade lime-icons8 from 2.7.0 to 2.8.0

package-lock.json, package.json
fix https://github.com/Lundalogik/crm-feature/issues/2865
Windows:
Linux:
macOS:
Mobile:
=> chore(packages): upgrade @lundalogik/lime-icons8 from 2.8.0 to 2.9.0

src/components/form/templates/object-field.ts
@BjornOstberg experienced a bug where the application crashes because `$ref` is undefined. By his own admission it may well be that they are using collapsible-section incorrectly, but since the feature is a "nice to have" rather than "system critical", we should fail gracefully instead of crashing hard. This addition of optional chaining should hopefully achieve that…
Windows:
Linux:
macOS:
Mobile:
=> fix(form): avoid crash if object-field is missing $ref

src/components/progress-flow/examples/progress-flow-colors-css.scss, src/components/progress-flow/progress-flow-item/partial-styles/_colors.scss, src/components/progress-flow/progress-flow.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2841
Windows:
Linux:
macOS:
Mobile:
=> fix(progress-flow): make it possible to set an icon color

src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/components/chip-set/examples/chip-set-input-type-search.tsx, src/components/chip-set/examples/chip-set-input-type-text.tsx, src/components/picker/picker.tsx
fix: #1718
Windows:
Linux:
macOS:
Mobile:
=> feat(chip-set): make it possible to set `input` type of `search` or `text`

src/components/form/templates/common.spec.ts, src/components/form/templates/common.ts
When an object has a title or a name, the function returns the title or a name. If no title or
name given, it will return the required property value as a title. In our case the property is
neither a title/name nor a required property which caused the crash. This PR solves the issue
fix Lundalogik/crm-feature#2857
Windows:
Linux:
macOS:
Mobile:
=> fix(common): avoid crashes when no name/title and required prop given

src/components/list/list-renderer.tsx, src/components/list/list.scss
Using tab, user can now focus the menu and trigger
it by pressing `enter` or `space` key.
fix https://github.com/Lundalogik/lime-elements/issues/1215
Windows:
Linux:
macOS:
Mobile:
=> fix(list): make action menu accessible with keyboard

src/components/button/button.scss, src/components/button/button.tsx
We have removed the ripple effect from almost all elements.
This will unify our styles more.
In this component, the original Material Design ripple was not
showing at all when clicking. Probably due to lack of some `import`s.
The div was only used to add a not-so-visible highlight
when the button was focused using keyboard.
Windows:
Linux:
macOS:
Mobile:
=> fix(button): remove the `ripple` div & add our own keyboard focus styles

src/components/dock/dock-button/dock-button.scss, src/components/dock/dock.scss, src/components/dock/examples/dock-colors-css.scss, src/components/dock/partial-styles/shrink-expand-button.scss
We have decided that variables that indicate the default state of something
do not need suffixes like `--default` or `--deselected`.
background: https://github.com/Lundalogik/lime-elements/pull/1792#discussion_r929902050
Windows:
Linux:
macOS:
Mobile:
=> fix(dock): remove `--deselected` suffix from CSS vars

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> chore(packages): upgrade Kompendium from 0.11.1 to 0.11.3

src/components/input-field/examples/input-field-placeholder.tsx, src/components/input-field/input-field.tsx
fix https://github.com/Lundalogik/crm-feature/issues/2921
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): prevent visual defects if no label is provided

src/components/code-editor/code-editor.tsx
Bug: If you change the value (a state variable for example) given to a limel-code-editor, the CodeMirror component won't reflect the change.
Before:
https://user-images.githubusercontent.com/435885/186658760-295d8617-5643-411c-bbba-430850d6187b.mov
After
https://user-images.githubusercontent.com/435885/186658809-0b7a39bf-23ea-4c81-a0c1-c7c57cd8e413.mov
Windows:
Linux:
macOS:
Mobile:
=> fix(code-editor): update editor when value changes

src/components/code-editor/code-editor.scss
The editor works fine with overflow...:
...but not when the content is not making the component to overflow.
Before:
After:
Windows:
Linux:
macOS:
Mobile:
=> fix(code-editor): stretch to parent

src/components/code-editor/code-editor.scss
Windows:
Linux:
macOS:
Mobile:
=> Code editor font size

package-lock.json, package.json, src/components/code-editor/code-editor.scss, src/components/code-editor/code-editor.tsx, src/components/code-editor/examples/code-editor-with-linting-and-folding.tsx, src/global/core-styles.scss, src/style/internal/codemirror-tooltip.scss, tsconfig.dev.json
Adds linting and folding support for JSON! 🎉 
(needs tooltip CSS from @Kiarokh or @LucyChyzhova !)
Windows:
Linux:
macOS:
Mobile:
=> feat(code-editor): lint and fold json

src/components/code-editor/code-editor.tsx
The code editor fails to render when passing a null value to it, due to a null ref inside CodeMirror.
Windows:
Linux:
macOS:
Mobile:
=> fix(code-editor): translate null value to empty string

src/components/dock/dock-button/dock-button.spec.tsx, src/components/dock/dock-button/dock-button.tsx
fix Lundalogik/crm-feature#2931
Windows:
Linux:
macOS:
Mobile:
=> feat(dock-button): emit event when dock menu is opened

src/components/dock/dock-button/dock-button.tsx, src/components/dock/dock.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(dock): emit event when a dock menu is opened

src/components/code-editor/code-editor.tsx
Continuation of #1824, which only fixed the initial render and not when the component is re-rendered.
Changing the value prop to null after the initial render gives the following error, which this PR will fix:
Windows:
Linux:
macOS:
Mobile:
=> fix(code-editor): avoid null reference in codemirror

src/components/code-editor/code-editor.tsx
Backport of feature from the Lime Angular code editor. When a user hits tab it will indent with spaces instead of tabs.
Windows:
Linux:
macOS:
Mobile:
=> fix(code-editor): indent with spaces

package-lock.json, package.json
fix https://github.com/Lundalogik/crm-feature/issues/2969
Windows:
Linux:
macOS:
Mobile:
=> chore(packages): upgrade @lundalogik/lime-icons8 from 2.10.0 to 2.11.0

src/components/progress-flow/progress-flow-item/partial-styles/_selected-indicator.scss, src/components/progress-flow/progress-flow-item/progress-flow-item.scss
Disabled but passed steps will not look bad.
There is no transparency, and instead there is a
lock icon to visualize disabled state.
fix https://github.com/Lundalogik/lime-elements/issues/1770
Windows:
Linux:
macOS:
Mobile:
=> fix(progress-flow): visualize disabled steps better

src/components/button/button.scss, src/components/chip-set/chip-set.scss, src/components/collapsible-section/collapsible-section.scss, src/components/dock/dock-button/dock-button.scss, src/components/dock/partial-styles/shrink-expand-button.scss, src/components/popover-surface/popover-surface.scss, src/components/select/select.scss, src/style/mixins.scss
We use the same mixin in crm-components already.
Windows:
Linux:
macOS:
Mobile:
=> use mixin to visualize keyboard focus

src/components/menu-list/menu-list.e2e.ts, src/components/menu-list/menu-list.tsx, src/components/menu/menu.tsx
The changes should be easy enough to follow if reviewed commit-by-commit.
Windows:
Linux:
macOS:
Mobile:
=> Some simple cleanup in limel-menu. (Fixes annoying warning when menu item is selected.)

.github/workflows/cleanup.yml, .github/workflows/pr-checks.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml, generate_npmrc.sh, package-lock.json, package.json, src/components/button-group/button-group.e2e.ts, src/components/collapsible-section/collapsible-section.e2e.ts, src/components/icon-button/icon-button.e2e.ts, src/components/icon/examples/icon-finder.tsx, src/components/input-field/input-field.e2e.ts, src/components/progress-flow/progress-flow-item/progress-flow-item.e2e.ts, src/icons/angle_left.svg, src/icons/angle_right.svg, src/icons/external_link.svg, src/icons/high_importance.svg, src/icons/unit-test.svg, stencil.config.ts
Windows:
Linux:
macOS:
Mobile:
=> chore: remove dependency on `lime-icons8`

src/components/chip-set/chip-set.scss, src/style/internal/z-index.scss
fix: #1864
Windows:
Linux:
macOS:
Mobile:
=> fix(chip-set): resolve z-index issues by using css `isolation`

src/components/badge/badge.spec.ts, src/components/badge/examples/badge-number.tsx, src/components/badge/format.ts
This reverts commit b8ed94897c3fa228d9243c8252b870d0f6a64c17.
`k` means "kilo", which is what we want. `K` means "Kelvin".
We should use the correct unit even if some of our users are unaware of the difference, because it matters to those who _are_ aware of the difference, but not to those who aren't.
Windows:
Linux:
macOS:
Mobile:
=> revert: "fix(badge): make all number units upper case"

src/components/popover-surface/popover-surface.scss, src/style/internal/z-index.scss
fix: Lundalogik/lime-elements#1864
Windows:
Linux:
macOS:
Mobile:
=> fix(popover): resolve z-index issues by using css `isolation`

src/components/tab-bar/examples/tab-bar.tsx, src/components/tab-bar/tab.types.ts
We added the possibility to have string labels in badges in this release: https://github.com/Lundalogik/lime-elements/releases/tag/v36.1.0-next.1
However, it is not possible to use it in tabs because we didn't update the Tab interface.
Use case: 
Windows:
Linux:
macOS:
Mobile:
=> feat(tab): allow string labels in badge

src/components/input-field/input-field.scss, src/components/input-field/input-field.tsx
In input field, prefix overlaps with the input value for type number
fix: #1870
=> fix(input-field): fix big prefix overlaps with value

src/components/input-field/input-field.scss, src/components/input-field/partial-styles/_readonly.scss
fix: https://github.com/Lundalogik/lime-elements/issues/1883
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): align `-` when the textarea is empty and readonly

src/components/select/select.template.tsx
`limel-select` with multiple values doesn't show `-` when no value is selected in the `readonly` mode.
Closes #1862.
=> fix(select): select with multiple values doesn't show the empty value (-) when readonly

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> chore(deps-dev): bump codemirror from 5.65.3 to 5.65.9

.github/workflows/pr-checks.yml, .github/workflows/pre-release.yml, .github/workflows/publish-docs.yml, .github/workflows/release.yml
Windows:
Linux:
macOS:
Mobile:
=> Move publishing of docs to reusable workflow

.github/workflows/sonarcloud.yml
Dependabot ought to behave itself, so running SonarCloud's scans on its PRs should hopefully not be necessary.
If we change our minds, and want to run them, the `SONAR_TOKEN` secret needs to be added to the Dependabot secrets in the repo config on GitHub.
Windows:
Linux:
macOS:
Mobile:
=> ci(sonarcloud): do not run SonarCloud scan on Dependabot PRs

src/components/snackbar/snackbar.e2e.ts
fix: #1612
Windows:
Linux:
macOS:
Mobile:
=> test(snackbar): hopefully fix blinking test

.github/workflows/publish-docs.yml
Windows:
Linux:
macOS:
Mobile:
=> ci(publish-docs.yml): update check for whether to run `link-docs` job

src/components/shortcut/examples/shortcut-notification.scss, src/components/shortcut/examples/shortcut-notification.tsx, src/components/shortcut/examples/shortcut-styling.scss, src/components/shortcut/examples/shortcut-styling.tsx, src/components/shortcut/examples/shortcut-with-click-handler.tsx, src/components/shortcut/examples/shortcut.scss, src/components/shortcut/examples/shortcut.tsx, src/components/shortcut/shortcut.e2e.ts, src/components/shortcut/shortcut.scss, src/components/shortcut/shortcut.tsx
Fix: https://github.com/Lundalogik/crm-feature/issues/3025
Windows:
Linux:
macOS:
Mobile:
=> feat(dashboard-shortcut): add `limel-dashboard-shortcut` component

src/components/shortcut/shortcut.tsx
Windows:
Linux:
macOS:
Mobile:
=> refactor(shortcut): fix misspelling

src/components/circular-progress/circular-progress.scss, src/components/circular-progress/circular-progress.tsx, src/components/circular-progress/examples/circular-progress-css-variables.scss, src/components/circular-progress/examples/circular-progress-css-variables.tsx, src/components/circular-progress/examples/circular-progress-props.tsx, src/style/internal/z-index.scss
fix: https://github.com/Lundalogik/lime-elements/issues/1942
Windows:
Linux:
macOS:
Mobile:
=> feat(circular-progress): add prefix functionality

src/components/date-picker/flatpickr-adapter/_flatpickr.scss
Removes duplicated rules that SonarCloud is nagging about, which causes the commit status to be red.
Let's make sonarcloud status green again.
Windows:
Linux:
macOS:
Mobile:
=> chore: remove duplicate rules

src/components/split-button/split-button.e2e.ts, src/components/split-button/split-button.scss, src/components/split-button/split-button.spec.tsx, src/components/split-button/split-button.tsx
fix https://github.com/Lundalogik/crm-feature/issues/3086 
Windows:
Linux:
macOS:
Mobile:
=> fix(split-button): don't render the menu if there are no menu items

src/components/select/select.scss
The keyboard focus works but is not visible👇
https://user-images.githubusercontent.com/50618208/202453694-a7d29331-013f-40a5-9556-6d55d6b7acec.mov
Windows:
Linux:
macOS:
Mobile:
=> fix(select): visualize keyboard focus

src/components/dialog/dialog.scss
fix https://github.com/Lundalogik/lime-elements/issues/1953
Windows:
Linux:
macOS:
Mobile:
=> 1953 dialog body padding

src/components/input-field/input-field.scss
Previously it was rendered, but transparent,
which made it selectable by user, and readable for assistive tech.
fix https://github.com/Lundalogik/lime-elements/issues/1963
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): do not render unformatted value when field is readonly

.github/workflows/pr-checks.yml, .github/workflows/publish-docs.yml
Windows:
Linux:
macOS:
Mobile:
=> ci(workflows): fix docs publish fail because it tries to post link on non-existing PR

src/components/select/select.template.tsx
Sets `aria-expanded` to `true` when the dropdown menu is open, and to `false` when it is closed.
fix https://github.com/Lundalogik/lime-elements/issues/1966
Windows:
Linux:
macOS:
Mobile:
=> fix(select): toggle `aria-expanded` to improve accessibility

src/components/info-tile/examples/info-tile-badge.scss, src/components/info-tile/examples/info-tile-badge.tsx, src/components/info-tile/examples/info-tile-loading.scss, src/components/info-tile/examples/info-tile-loading.tsx, src/components/info-tile/examples/info-tile-progress.scss, src/components/info-tile/examples/info-tile-progress.tsx, src/components/info-tile/examples/info-tile-styling.scss, src/components/info-tile/examples/info-tile-styling.tsx, src/components/info-tile/examples/info-tile.scss, src/components/info-tile/examples/info-tile.tsx, src/components/info-tile/info-tile.e2e.ts, src/components/info-tile/info-tile.scss, src/components/info-tile/info-tile.tsx, src/components/info-tile/info-tile.types.ts, src/global/shared-types/link.types.ts, src/interface.d.ts
fix: https://github.com/Lundalogik/crm-feature/issues/3025
Add `limel-info-tile` on the start page as a widget, with the following config, and try different sizes:
```json
{
"icon": "full_of_shit",
"label": "Money we earned through some crazy deals this year",
"value": "20,000",
"prefix": "earned",
"suffix": "SEK",
"href": "https://www.google.com",
"target": "_blank",
"progressValue": "24"
}
````
````json
{
"icon": "poo",
"label": "Such a wonderful year",
"value": "4 432",
"prefix": "money",
"suffix": "SEK",
"href": "https://www.google.com",
"target": "_blank",
"badge": "2345",
}
````
Windows:
Linux:
macOS:
Mobile:
=> feat(info-tile): add `limel-info-tile` component

src/components/form/widgets/code-editor.ts
The linting allows the user to see syntax errors in the JSON code shown in the editor.
Folding makes it possible to collapse pieces of code.
fix https://github.com/Lundalogik/crm-feature/issues/3105
Windows:
Linux:
macOS:
Mobile:
=> fix(form): enable `lint` and `fold` for code editor in form

src/components/shortcut/examples/shortcut-with-click-handler.tsx, src/components/shortcut/examples/shortcut.tsx, src/components/shortcut/shortcut.e2e.ts, src/components/shortcut/shortcut.tsx
Now `target`, `href` and `title`, are set
using the `link` interface.
BREAKING CHANGES
Instead of individual props for `target`, `href` and `linkTitle`,
the component now only has one prop for `link`.
Check out the documentations for more info.
fix https://github.com/Lundalogik/lime-elements/issues/1977
Windows:
Linux:
macOS:
Mobile:
=> fix(shortcut): use `link` interface

.github/workflows/release.yml
Windows:
Linux:
macOS:
Mobile:
=> ci(release.yml): merge release back to `next` without "fast-forward"`

src/components/progress-flow/progress-flow.tsx
We want to add `value` to each `progress-flow-item` element just like a `select` element have a `value` on each `option` element.
This is for two reasons.
1. I think it's expected behavior.
2. We need it to track a specific flow in Heap (Product analytics).
Windows:
Linux:
macOS:
Mobile:
=> feat(progress-flow): update some internals to enable tracking using Heap 

src/components/picker/picker.tsx, src/components/picker/searcher.types.ts
Windows:
Linux:
macOS:
Mobile:
=> docs(picker): add documentation for the `Searcher` type

src/components/form/fields/schema-field.ts, src/components/form/form.types.ts
fix Lundalogik/crm-feature#3036
Windows:
Linux:
macOS:
Mobile:
=> feat(form): adds schema path to custom components form info

src/components/form/fields/schema-field.ts
fix: Lundalogik/crm-feature#3136
Windows:
Linux:
macOS:
Mobile:
=> fix(form): prevent error if `idSchema` is undefined

src/components/info-tile/info-tile.e2e.ts, src/components/info-tile/info-tile.tsx
fix: #2022
Windows:
Linux:
macOS:
Mobile:
=> fix(info-tile): do not crash if `value` is undefined

src/components/info-tile/info-tile.e2e.ts, src/components/info-tile/info-tile.tsx
Backport of fix for #2022
Windows:
Linux:
macOS:
Mobile:
=> Backport info tile fix

src/components/info-tile/info-tile.scss
fix: https://github.com/Lundalogik/crm-feature/issues/3144
Windows:
Linux:
macOS:
Mobile:
=> fix(info-tiles): adjust the layout if no container queries support

src/components/table/partial-styles/tabulator-paginator.scss
We don't use SVGs in the CSS anymore.
Instead we draw the arrow icons, using CSS
and colors that react to color-scheme.
Windows:
Linux:
macOS:
Mobile:
=> fix(table): make pagination buttons fully support dark mode

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> docs(kompendium): update kompendium from v0.11.4 to v0.12.1

src/components/button/button.tsx
Since v36.0.0-next.5, setting the `loading` property to `true` also disables the button, but the documentation had not been updated to reflect this new behaviour.
Windows:
Linux:
macOS:
Mobile:
=> docs(button): fix description of `loading` property to match updated behaviour

src/components/switch/switch.scss
fix https://github.com/Lundalogik/lime-elements/issues/2056 
Windows:
Linux:
macOS:
Mobile:
=> fix(switch): specify color for label to support dark mode better

.github/workflows/cleanup.yml, .github/workflows/pr-checks.yml, .github/workflows/pr-comment.js, .github/workflows/pre-release.yml, .github/workflows/publish-docs.yml, .github/workflows/release.yml, .github/workflows/sonarcloud.yml
Actions using node 12 are deprecated in GitHub Actions, so we need to update to versions that are using a later version of node.
Windows:
Linux:
macOS:
Mobile:
=> Update actions using node 12

src/components/form/form.scss
fix https://github.com/Lundalogik/lime-elements/issues/2055
Windows:
Linux:
macOS:
Mobile:
=> fix(form): use dark mode friendly CSS variable for headline & body text

src/components/header/examples/header-responsive.tsx, src/components/header/examples/header.tsx, src/components/header/header.scss, src/components/header/header.tsx
I found this in a six month old branch… it doesn't seem to have been merged. I'm not sure if I never opened a pull request, or if I did but it didn't get merged for some reason… 🤷‍♂️
Windows:
Linux:
macOS:
Mobile:
=> feat(header): add named slot `actions` and deprecate unnamed slot

src/components/collapsible-section/collapsible-section.scss
fix https://github.com/Lundalogik/lime-elements/issues/2060
Windows:
Linux:
macOS:
Mobile:
=> fix(collapsible-section): make header title color respect dark mode

.github/workflows/cleanup.yml, .github/workflows/pr-checks.yml, .github/workflows/pre-release.yml, .github/workflows/publish-docs.yml, .github/workflows/release.yml
Read more here: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Windows:
Linux:
macOS:
Mobile:
=> ci(workflows): update workflows using deprecated set-output functionality

src/components/chip-set/chip-set.scss, src/style/internal/shared_input-select-picker.scss
fix https://github.com/Lundalogik/lime-elements/issues/2063
Windows:
Linux:
macOS:
Mobile:
=> 2063 icon and delimiter color of chip set

.github/workflows/pre-release.yml
Windows:
Linux:
macOS:
Mobile:
=> ci(pre-release.yml): trigger update in lime-crm-building-blocks when `next` is released

src/components/info-tile/info-tile.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(info-tile): make sure icon does not grow too large on older browsers

src/components/tab-bar/partial-styles/tab-bar-scroller.scss, src/components/tab-bar/tab-bar.scss, src/components/tab-panel/examples/tab-panel.scss, src/components/tab-panel/tab-panel.scss, src/style/internal/z-index.scss
fix https://github.com/Lundalogik/lime-elements/issues/2082
Windows:
Linux:
macOS:
Mobile:
=> Tab dark mode

src/components/slider/slider.scss
fix https://github.com/Lundalogik/lime-elements/issues/2087
Windows:
Linux:
macOS:
Mobile:
=> fix(slider): make min & max labels react to dark mode

src/components/dialog/examples/dialog-action-buttons.scss, src/components/split-button/split-button.scss
fix: https://github.com/Lundalogik/lime-elements/issues/2078
Windows:
Linux:
macOS:
Mobile:
=> fix(split-button): make sure it stretches in mobile view

src/components/split-button/split-button.scss
fix: https://github.com/Lundalogik/lime-elements/issues/2096
Windows:
Linux:
macOS:
Mobile:
=> fix(split-button): do not emit `click` events when button is disabled

src/components/date-picker/date.types.ts, src/components/date-picker/dateFormatter.ts, src/components/date-picker/pickers/Picker.ts
See individual commits for details. (If you review this commit by commit, you will see that each change is _extremely_ small, and very easy to understand.)
Windows:
Linux:
macOS:
Mobile:
=> Add languages to date picker

src/components/form/row/row.scss
by making their colors more grey.
fix https://github.com/Lundalogik/crm-feature/issues/3197
Windows:
Linux:
macOS:
Mobile:
=> fix(form): make icons in `row` layout visually less dominant

.github/workflows/pr-checks.yml
Windows:
Linux:
macOS:
Mobile:
=> ci(pr-checks.yml): allow one run per PR even for dependabot PRs

.github/workflows/pr-checks.yml
Windows:
Linux:
macOS:
Mobile:
=> ci(pr-checks.yml): update `xt0rted/block-autosquash-commits-action` to v2.2.0

.github/workflows/pr-checks.yml
Windows:
Linux:
macOS:
Mobile:
=> ci(pr-checks.yml): skip certain jobs when running on merge queue

README.md, package-lock.json, package.json
This was only used by commitizen, but the necessary config to actually use it has been missing anyway. This dependency adds quite a lot of sub-dependencies to the project, so rather than adding the config, we can just remove this and slim down the dependencies instead.
Windows:
Linux:
macOS:
Mobile:
=> chore: remove dependency on `cz-conventional-changelog`

src/components/dock/dock-button/dock-button.scss, src/components/dock/dock-button/dock-button.tsx, src/components/dock/dock.scss, src/components/dock/dock.tsx, src/components/dock/dock.types.ts, src/components/dock/examples/dock-notification.scss, src/components/dock/examples/dock-notification.tsx, src/components/dock/examples/my-custom-menu-with-notifications.scss, src/components/dock/examples/my-custom-menu-with-notifications.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/2070
Windows:
Linux:
macOS:
Mobile:
=> feat(dock): enable displaying a notification badge on the buttons

src/components/badge/badge.scss, src/components/badge/badge.tsx, src/components/badge/examples/badge.scss, src/components/badge/examples/badge.tsx
This updates the documentation to make the `label` property on limel-badge optional.
fix #2140
Windows:
Linux:
macOS:
Mobile:
=> feat(badge): make label optional

src/components/dock/dock-button/dock-button.tsx, src/components/menu-list/menu-list-renderer.tsx, src/components/menu-list/menu-list.scss, src/components/menu/examples/menu-notification.tsx, src/components/menu/menu.scss, src/components/menu/menu.tsx, src/components/menu/menu.types.ts
Makes it possible to add a notification badge to menu items when using Menu.
fixes: Lundalogik/crm-feature#3215
Windows:
Linux:
macOS:
Mobile:
=> Menu item badge

.github/workflows/cleanup.yml, .github/workflows/pre-release.yml, .github/workflows/publish-docs.yml, .github/workflows/release.yml
Windows:
Linux:
macOS:
Mobile:
=> Replace instances of `lime-ci` with `lime-opensource`, and use `lime-opensource` when publishing docs

src/components/input-field/examples/input-field-textarea.tsx, src/components/input-field/input-field.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/2161#issuecomment-1455723243
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): make possible to use placeholder in textarea type

.github/dependabot.yml, package-lock.json, package.json, release.config.js
It seems like the docs cannot be published when using typescript v5.0.2, so revert back to v4.9.5.
Windows:
Linux:
macOS:
Mobile:
=> chore: make it possible to publish the docs again

src/translations/nl.ts
Windows:
Linux:
macOS:
Mobile:
=> fix(callout): add missing Dutch translation of `Caution`

src/components/callout/callout.scss, src/components/callout/callout.tsx, src/components/callout/callout.types.ts, src/components/callout/examples/callout-styles.scss, src/components/callout/examples/callout-styles.tsx
it is needed because we have a minimalistic flat UI design language. It means elements are usually perceived and differentiated from each other by very minimal visual details, such as their background colors (and not-so-often by the shadows around them, or borders). So not being able to change the default hard-coded background color from --contrast-300 means you can not use this component on a background color that is --contrast-200, --contrast-300 or --contrast-400, due to lack of contrast between the surrounding UI and this component. So, the consumer should have the possibility to tune that color. And with that, there comes a natural need to tune the contrast of the text too (to make it readable on a darker or lighter background).
(Check any that applies, it's ok to leave boxes …
=> feat(callout): add support for custom colors

src/components/callout/callout.e2e.ts, src/components/callout/callout.helpers.ts, src/components/callout/callout.tsx, src/components/callout/examples/callout-composite.tsx, src/components/callout/examples/callout-custom-heading.tsx, src/components/callout/examples/callout-custom-icon.tsx
Windows:
Linux:
macOS:
Mobile:
=> feat(callout): add support for custom heading and icon

src/components/slider/partial-styles/_helper-text.scss, src/components/slider/partial-styles/_readonly.scss, src/components/slider/partial-styles/_thumb.scss, src/components/slider/partial-styles/percentage-color.scss, src/components/slider/slider.scss, src/components/slider/slider.tsx
This was an effort to fix some rendering bugs, which would happen when the container of the slider was
resized. While trying to find a solution,
we noticed that there are many nested
containers and hoped that these simplifications
could help solve the issue. We hoped to get something perhaps from the MDC's inbuilt tech. But so far
we don't see a noticeable improvement.
However, the code is simpler now.
Windows:
Linux:
macOS:
Mobile:
=> refactor(slider): get rid of nested structure & simplify things

.github/workflows/sonarcloud.yml
Lock to v1.8 to avoid further surprises happening on master
Windows:
Linux:
macOS:
Mobile:
=> build: lock sonarcloud scanner action

src/components/checkbox/checkbox.template.tsx, src/components/checkbox/partial-styles/_helper-text.scss, src/components/chip-set/chip-set.tsx, src/components/chip-set/partial-styles/_helper-text.scss, src/components/input-field/input-field.scss, src/components/input-field/input-field.tsx, src/components/select/partial-styles/_helper-text.scss, src/components/select/select.scss, src/components/select/select.template.tsx, src/components/slider/partial-styles/_helper-text.scss, src/components/slider/slider.tsx
related to: https://github.com/Lundalogik/crm-feature/issues/3334
waiting for: https://github.com/Lundalogik/lime-elements/pull/2269
fix: https://github.com/Lundalogik/lime-elements/issues/2257
fix: https://github.com/Lundalogik/lime-elements/issues/2258
fix: https://github.com/Lundalogik/lime-elements/issues/2263
Windows:
Linux:
macOS:
Mobile:
=> Use the new `limel-helper-line` component (which is `@private`) in different input fileds

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> docs(packages): upgrade Kompendium from `0.12.2` to `0.12.3`

src/components/callout/callout.scss, src/components/callout/callout.tsx, src/components/callout/examples/callout-custom-type.scss, src/components/callout/examples/callout-custom-type.tsx, src/components/callout/examples/callout-styles.scss, src/components/callout/examples/callout-styles.tsx
If using a custom type let's say "success", then it wasn't possible to use `--callout-color` to style the component because the `--limel-callout-tint-color` variable was undefined. So I added a default value for it
Windows:
Linux:
macOS:
Mobile:
=> fix(callout): support custom types

src/components/input-field/input-field.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): show "clear all" button when field is not empty

src/components/action-bar/action-bar-item/action-bar-overflow-menu.spec.tsx, src/components/action-bar/action-bar.spec.tsx, src/components/action-bar/action-bar.tsx
This PR adds unit tests for the `limel-action-bar`. It's mostly concerned about how we handle overflow of the `limel-action-bar-items` into the `limel-action-bar-overflow-menu`.
The reason for creating a follow up PR for this was due to the large size of PR containing the action bar.
Fixes Lundalogik/crm-feature#3379
Connected to Lundalogik/lime-elements#2315
Windows:
Linux:
macOS:
Mobile:
=> Tests for action bar

src/global/icon-cache.ts
Something.I overlooked in a recent review
Windows:
Linux:
macOS:
Mobile:
=> style(icon-cache): fix docstring return

src/components/list/list.scss
This feature was added here https://github.com/Lundalogik/lime-elements/pull/2337/files#diff-817817636ecff6902e33d23a4566f3ce0c76c4b8c1604695c95b7acc3c40b066R43-R45, but somehow we forgot to type `var`
Windows:
Linux:
macOS:
Mobile:
=> fix(list): correctly enable usage of `--list-margin` variable

src/components/slider/slider.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(slider): use a unique id for the helper text & use it by `aria-controls`

src/components/button/button.tsx, src/util/makeEnterClickable.ts
Added helper function that you would put in componentWillLoad that adds the event listeners needed to make buttons clickable with enter.
We add it to limel-buttons to make testing easy (this will probably conflict with another similar issue, and we need to fix this conflict before merge).
Fixes Lundalogik/crm-feature#3518
I tested it by throwing in a timeout in `componentWillLoad` that calls the add/remove event. I suggest trying something similar, calling them in different orders, maybe repeatedly, and see if it breaks.
The docs have a really good playground for the limel-button to test this functionality.
Windows:
Linux:
macOS:
Mobile:
=> feat(button-like-components): add helper function for enter clicking

src/components/checkbox/checkbox.template.tsx, src/components/checkbox/checkbox.tsx
The `aria-controls` and `aria-describedby` are using these IDs to give clues to assistive technologies.
In the former implementation, we were lacking ids
for the helper text elements.
Windows:
Linux:
macOS:
Mobile:
=> fix(checkbox): create a unique id for the helper text & use it by `aria` attributes

src/components/tooltip/examples/tooltip-basic.tsx, src/components/tooltip/tooltip.spec.tsx, src/components/tooltip/tooltip.tsx
Windows:
Linux:
macOS:
Mobile:
=> Some small cleanups in limel-tooltip

src/components/portal/portal.tsx, src/components/tooltip/examples/tooltip-max-character.scss, src/components/tooltip/examples/tooltip-max-character.tsx, src/components/tooltip/tooltip-content.scss, src/components/tooltip/tooltip.scss, src/components/tooltip/tooltip.tsx, src/design-guidelines/declutter/declutter.md
fix: #1408
fix: https://github.com/Lundalogik/crm-feature/issues/2590
Windows:
Linux:
macOS:
Mobile:
=> Position tooltip relative to target element instead of relative to limel-tooltip element

src/components/dock/dock-button/dock-button.tsx, src/components/tooltip/tooltip.spec.tsx, src/components/tooltip/tooltip.tsx
Enables consumers to decide where to visually
render the tooltip, in relation to its trigger element.
fix https://github.com/Lundalogik/lime-elements/issues/2446
Windows:
Linux:
macOS:
Mobile:
=> feat(tooltip): add `openDirection` prop

src/components/list/list.tsx
Windows:
Linux:
macOS:
Mobile:
=> docs(list): update description of `change` event to match current functionality

src/components/action-bar/action-bar.types.ts
Fixes Lundalogik/crm-feature#3452
Windows:
Linux:
macOS:
Mobile:
=> feat(action-bar-icon-interface): make `icon` field required when `iconOnly` is true

src/components/linear-progress/linear-progress.tsx
fix https://github.com/Lundalogik/crm-feature/issues/3585
Windows:
Linux:
macOS:
Mobile:
=> Avoid rendering the component unless the value is a number

src/components/form/form.scss
Fix: https://github.com/Lundalogik/crm-feature/issues/3602
Windows:
Linux:
macOS:
Mobile:
=> fix(form): separate code editor from other elements

src/components/menu-surface/menu-surface.scss
Last items of menus with many items could
be rendered outside of the screen, preventing
the user from reaching them by scrolling.
This was specially problematic for menus which
have a static placement in the UI.
fix: https://github.com/Lundalogik/lime-elements/issues/2477
Windows:
Linux:
macOS:
Mobile:
=> fix(menu): prevent long menus to overflow out of the screen

src/components/checkbox/partial-styles/_readonly.scss, src/components/switch/partial-styles/_readonly.scss, src/components/switch/switch.scss
Fix: https://github.com/Lundalogik/crm-feature/issues/3312
Windows:
Linux:
macOS:
Mobile:
=> Readonly switch and checkbox

src/components/popover-surface/popover-surface.scss
Having large elements inside the popover surface would result in too wide or too tall popovers. Basically the content went beyond the `width` which was defined by `--popover-surface-width`.
fix: https://github.com/Lundalogik/crm-feature/issues/3623
Windows:
Linux:
macOS:
Mobile:
=> fix(popover): prevent large content to overflow the component's surface

src/global/shared-types/icon.types.ts
fix https://github.com/Lundalogik/lime-elements/issues/1303
Windows:
Linux:
macOS:
Mobile:
=> chore(shared-types): add icon interface

package-lock.json, package.json
Windows:
Linux:
macOS:
Mobile:
=> chore(packages): upgrade Kompendium from 0.12.3 to 0.12.5

src/components/icon-button/icon-button.e2e.ts, src/components/icon-button/icon-button.scss, src/components/icon-button/icon-button.tsx
This component is very minimal and simple, and we are completely overwriting MDC styles with our own styles. 
We don't use MDC ripple effect, and nothing else from the MDC. 
There is no need for us to be dependent on MDC here anymore.
Windows:
Linux:
macOS:
Mobile:
=> Icon button: remove dependency of MDC

src/components/breadcrumbs/breadcrumbs.scss, src/components/dialog/dialog.scss, src/components/dialog/dialog.tsx, src/style/mixins.scss
fix https://github.com/Lundalogik/lime-elements/issues/1998
Windows:
Linux:
macOS:
Mobile:
=> Fade out content that overflow out of the top and bottom edges of a dialog's content

src/components/input-field/input-field.tsx
To test this, you can go to the _Input Field with Completions_ example in the docs, inspect the component, and make sure you select the `limel-input-field` element. Then go to the console and run `$0.completions = ['hej', 'svejs']`. Then focus the input field, and the completions should have updated.
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): handle completions changing after component is loaded

src/components/action-bar/action-bar-item/action-bar-item.scss
fix https://github.com/Lundalogik/lime-elements/issues/2510
Windows:
Linux:
macOS:
Mobile:
=> fix(action-bar): do not display tooltip of invisible action buttons

package-lock.json, package.json, src/components/markdown/markdown-parser.ts, stencil.config.dist.ts, stencil.config.docs.ts, stencil.config.ts
There were both build errors and runtime errors with the versions Dependabot had updated to. The versions have been updated to the latest in package.json, the code has been updated to accommodate for the breaking changes, and the build was updated to get rid of some runtime errors
The `remark-footnotes` package could not be updated, so it was removed. It also have been deprecated https://github.com/remarkjs/remark-footnotes. The footnotes seem to work anyway, perhaps since we already use `remark-gfm`
Windows:
Linux:
macOS:
Mobile:
=> fix(markdown): update remark versions to latest

src/components/chip-set/partial-styles/_file-picker.scss
fix https://github.com/Lundalogik/crm-feature/issues/3645
Windows:
Linux:
macOS:
Mobile:
=> fix(file): render dropzone help text better when file picker has a small width

src/components/list/list.tsx
See #2482 as reference.
This solves some of the keyboard navigation issues we've had with the limel-list element.
See Kia showing the bug that is fixed here:
https://github.com/Lundalogik/lime-elements/assets/35954987/fa1a6d0d-cc6b-4fdf-8769-c327c2141b01
Windows:
Linux:
macOS:
Mobile:
=> fix(list): recreate the mdcList on item change

src/index.ts
A few types accidently got lost when #2522 was merged. This should add them back again
Windows:
Linux:
macOS:
Mobile:
=> fix(types): export missing types again

src/components/config/config.tsx, src/components/input-field/input-field.tsx, src/global/config.ts
The property "locale" specifies the user's locale and/or preferences in which numbers should be formatted. This affect the formatting of integers and decimals
fix Lundalogik/crm-feature#3673
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): apply the user's locale when formatting numbers

src/components/dialog/dialog.tsx, src/components/dialog/examples/dialog-heading-actions.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/1861
Windows:
Linux:
macOS:
Mobile:
=> feat(dialog): add actions to the heading area

src/components/breadcrumbs/breadcrumbs.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(breadcrumbs): don't render icon if name isn't specified

src/components/file-viewer/examples/file-viewer-custom-actions.tsx, src/components/file-viewer/examples/file-viewer-filename.tsx, src/components/file-viewer/examples/file-viewer-inbuilt-actions.tsx, src/components/file-viewer/examples/file-viewer-office.tsx, src/components/file-viewer/examples/file-viewer-with-picker.scss, src/components/file-viewer/examples/file-viewer-with-picker.tsx, src/components/file-viewer/examples/file-viewer.scss, src/components/file-viewer/examples/file-viewer.tsx, src/components/file-viewer/examples/limel-example-file-viewer-inbuilt-actions.scss, src/components/file-viewer/extension-mapping.spec.tsx, src/components/file-viewer/extension-mapping.tsx, src/components/file-viewer/file-viewer.e2e.ts, src/components/file-viewer/file-viewer.scss, src/components/file-viewer/file-viewer.spec.tsx, src/components/file-viewer/file-viewer.tsx, src/components/file-viewer/file-viewer.types.ts, src/components/file-viewer/fullscreen.ts, src/components/file-viewer/partial-styles/ui-controls.scss, src/translations/da.ts, src/translations/en.ts, src/translations/fi.ts, src/translations/nl.ts, src/translations/no.ts, src/translations/sv.ts
fix https://github.com/Lundalogik/crm-feature/issues/3622
Steps below can be done in follow-up PRs. The component is `@private` at the moment.
Windows:
Linux:
macOS:
Mobile:
=> chore(file-viewer): add new component

src/components/code-editor/code-editor.tsx, src/components/code-editor/code-editor.types.ts
fix: Lundalogik/lime-crm-components#1846
Windows:
Linux:
macOS:
Mobile:
=> feat(code-editor): add jinja2 language mode type

src/components/icon-button/icon-button.tsx
Generating a new id on every render is problematic. Better to do it only once when the component is created.
Windows:
Linux:
macOS:
Mobile:
=> refactor(icon-button): generate `tooltipId` only once

src/components/table/columns.ts, src/components/table/table.e2e.ts
This sets the default sorting direction, when clicking on the tabulator in the table view, to descending. 
Fixes https://github.com/Lundalogik/crm-feature/issues/3655
=> feat(column sorting): set default sort direction to descending

CONTRIBUTING.md
Windows:
Linux:
macOS:
Mobile:
=> docs(CONTRIBUTING.md): add section about how we structure our code

src/components/input-field/input-field.tsx
The portal is currently used to show auto-completion suggestions. But the plan is to use it for showing even the helper-line. This change will make the next thing easier.
I believe this change provides a better code organization, and achieves the same functionality
in terms of rendering the autocomplete list with the same conditions and handling the same interactions.
The core structure and logic of rendering the list, controlling its visibility, and handling user interactions remain consistent in both versions.
Windows:
Linux:
macOS:
Mobile:
=> refactor(input-field): simplify the logic for rendering the portal

src/components/helper-line/helper-line.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(helper-line): when hidden, it should not have any height

src/components/chip-set/chip-set.tsx, src/components/chip-set/examples/chip-set-input.tsx, src/components/file/examples/file.tsx, src/components/file/file.tsx, src/components/picker/picker.tsx
Windows:
Linux:
macOS:
Mobile:
=> feat(chip-set): enable consumers to make it `invalid`

src/components/file-viewer/file-viewer.e2e.ts, src/components/file-viewer/file-viewer.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(file-viewer): use fileType to create a URL for the file

src/components/form/adapters/widget-adapter.ts, src/components/form/fields/schema-field.ts
This makes sure fields that have a value and an error are rendered as invalid.
Also, empty fields that are not required are always rendered as invalid when they have errors.
Fixes: Lundalogik/crm-feature#3478
Windows:
Linux:
macOS:
Mobile:
=> Make non-empty and optional fields with errors invalid

src/components/menu-list/menu-list-renderer.tsx, src/components/menu-list/menu-list.scss, src/components/menu/examples/item-constants.ts, src/components/menu/examples/menu-composite.tsx, src/components/menu/examples/menu-open-sub-menu-programmatically.scss, src/components/menu/examples/menu-open-sub-menu-programmatically.tsx, src/components/menu/examples/menu-sub-menu.tsx, src/components/menu/menu.tsx, src/components/menu/menu.types.ts
This is one of three PRs that are connected and extracted from #2574 
They are chained in 3 branches and is best reviewed in this order:
1. https://github.com/Lundalogik/lime-elements/pull/2576 **This PR**
2. https://github.com/Lundalogik/lime-elements/pull/2577
3. https://github.com/Lundalogik/lime-elements/pull/2578
Windows:
Linux:
macOS:
Mobile:
=> feat(menu): enable having nested menus (sub-menus)

src/components/file-viewer/file-viewer.tsx
> The [loading](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#loading) attribute on an [<img>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img) element (or the [loading](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#loading) attribute on an [<iframe>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe)) can be used to instruct the browser to defer loading of images/iframes that are off-screen until the user scrolls near them.
> 
> ```html
> <img src="image.jpg" alt="..." loading="lazy" />
> <iframe src="video-player.html" title="..." loading="lazy"></iframe>
> ```
> The load event fires when the eagerly-loaded content has all been loaded; at that time, it's entirely possible (or even likely) that there may be lazily-loaded …
=> File viewer lazy load

src/components/select/select.template.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/2618
Windows:
Linux:
macOS:
Mobile:
=> fix(select): don't render empty icons

src/util/link-helper.ts
As requested by @EdvinLP in [Open Hours](https://teams.microsoft.com/l/message/19:8eb8d446f40d4696ba03bee0d3b47a56@thread.tacv2/1700479963932?tenantId=15f5bb21-07a4-42c6-ada2-08965bd62081&groupId=2f699c45-fe12-4487-81ae-829eb08a675a&parentMessageId=1700479963932&teamName=Lime%20CRM&channelName=Dev%20Open%20Hours%20(Tues%20and%20Thurs%2010.00%20-%2011.00)&createdTime=1700479963932) (internal link)
Windows:
Linux:
macOS:
Mobile:
=> fix: add support for `m-files://` links

src/components/menu/menu.types.ts
A very small typing issue, where we missed that the search results of the `MenuSearcher` type could contains `ListSeparators`
Windows:
Linux:
macOS:
Mobile:
=> fix(menu): be able to use ListSeparator in search result

src/components/help/examples/help-and-documentation.ts, src/components/help/examples/help-open-direction.tsx, src/components/help/examples/help-placement.scss, src/components/help/examples/help-placement.tsx, src/components/help/examples/help-read-more.tsx, src/components/help/examples/help.tsx, src/components/help/help-content.tsx, src/components/help/help.scss, src/components/help/help.tsx, src/components/help/limel-help-content.scss
Specially Intended to be used here: https://github.com/Lundalogik/lime-elements/pull/2622
Windows:
Linux:
macOS:
Mobile:
=> feat(help): add new component

src/components/dialog/dialog.types.ts, src/components/dialog/examples/dialog-heading-actions.tsx, src/components/dialog/examples/dialog-heading.scss, src/components/header/header.tsx
related to https://github.com/Lundalogik/crm-feature/issues/3818
Windows:
Linux:
macOS:
Mobile:
=> Continue enabling `Icon` interface in other components

src/components/button/button.scss, src/components/button/button.tsx, src/components/button/partial-styles/_has-reduced-presence.scss
`limel-button` includes an internal `button` element. There is no reason to depend on MDC, merely to get a bunch of styles.  We don't get any specific functionality from MDC as far as I can say. Everything else is handled basically inside the component already.
Windows:
Linux:
macOS:
Mobile:
=> Dematerialize `limel-button`, remove its dependency on MDC

src/design-guidelines/size/size-rhythms.md
- Auto linting
- Move an "important" note in an admonition block
Windows:
Linux:
macOS:
Mobile:
=> docs(size-rhythms): improve docs

src/components/button/button.scss, src/components/icon-button/icon-button.scss, src/components/select/select.scss, src/style/mixins.scss
fix: https://github.com/Lundalogik/crm-feature/issues/2894
Windows:
Linux:
macOS:
Mobile:
=> chore(mixins): add a mixin for visualising open dropdown states

src/components/header/header.tsx, src/components/list/list-renderer.tsx, src/components/menu-list/menu-list-renderer.tsx, src/components/picker/picker.tsx
fix https://github.com/Lundalogik/lime-elements/issues/2686
Windows:
Linux:
macOS:
Mobile:
=> More icon interface

src/components/split-button/split-button.scss
the menu trigger has a dark color
Windows:
Linux:
macOS:
Mobile:
=> fix(split-button): use the same color for the menu trigger

src/components/markdown/examples/markdown-code.tsx, src/components/markdown/partial-styles/_pre-code.scss
fix https://github.com/Lundalogik/lime-elements/issues/2649
Windows:
Linux:
macOS:
Mobile:
=> Markdown code

src/components/menu/examples/menu-searchable.tsx, src/components/menu/menu.tsx
Fixes #2660 
Windows:
Linux:
macOS:
Mobile:
=> fix(menu): show empty result when no search hits

src/components/markdown/examples/markdown-composite.scss, src/components/markdown/examples/markdown-composite.tsx, src/components/markdown/markdown.tsx
This is an example I have locally to test out how a specific markdown/HTML will be rendered in Lime CRM. We have custom styling which make it render in another way than a regular markdown.
So this example makes very much sense to have so that we can test content out directly in the docs.
https://github.com/Lundalogik/lime-elements/assets/1814702/9030f83f-f074-4efc-bcd9-395dd4a72762
Windows:
Linux:
macOS:
Mobile:
=> docs(markdown): add composite example

src/components/markdown/partial-styles/_tables.scss
In Lime CRM, the markdown component is sometimes used to render the HTML content of an email. Since emails can have lots of nested tables, the UI will be rendered horribly with below styles. In such cases, we just want to default to the user agent stylesheet for tables.
This is for internal use in Lime CRM, which is why there is no public documentation for this. Requested by @TommyLindh2 
Add paste the content of this example in the Composite Example of `limel-markdown`.
👇 
[test.txt](https://github.com/Lundalogik/lime-elements/files/13949937/test.txt)
⚠️ Below data is fake
It looks like this
The content of the mail can you see here:
[test.txt](https://github.com/Lundalogik/lime-elements/files/13949937/test.txt)
(Check any that applies, it's ok to leave boxes unchecked if testing …
=> chore(markdown): enable resetting table styles, for Lime CRM's internal use

src/components/action-bar/action-bar.spec.tsx, src/components/action-bar/action-bar.tsx
Screen reader users will have a better experience, understanding the structure of the component better, when ARIA roles explain the relationship of the buttons and their containers (the action bar).
fix https://github.com/Lundalogik/lime-elements/issues/2702
Windows:
Linux:
macOS:
Mobile:
=> fix(action-bar): improve accessibility, using ARIA roles

src/components/file-viewer/file-viewer.tsx, src/components/menu/menu.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(types): some exported types were exported as `any`

src/components/header/header.scss, src/components/header/header.tsx
Windows:
Linux:
macOS:
Mobile:
=> Header improvements

src/components/action-bar/action-bar.types.ts
`ActionBarItem` inherits from `MenuItem` which is generic, so `ActionBarItem` should be too
Windows:
Linux:
macOS:
Mobile:
=> feat(action-bar): make `ActionBarItem` generic

src/components/picker/picker.tsx
Fix: https://github.com/Lundalogik/lime-elements/issues/2749
Windows:
Linux:
macOS:
Mobile:
=> fix(limel-picker): don't show an empty icon if no icon is provided

src/components/icon/get-icon-props.spec.ts, src/components/icon/get-icon-props.ts
fix: #2752
Windows:
Linux:
macOS:
Mobile:
=> fix(icon): do not crash if icon is `null`

.eslintrc.js, src/components/form/examples/form-with-help.tsx, src/components/form/form.types.ts, src/components/form/widgets/input-field.ts, src/components/help/examples/help-read-more.tsx, src/components/help/help.tsx, src/components/help/help.types.ts
Fixes problem mentioned in [this Slack message](https://lime-technologies.slack.com/archives/C1K6TN9BK/p1705587480128879).
> Ok, I found out that some types exported from Lime Elements are broken again :disappointed: I fixed them a while back, but now some of them were just exported as any again, leading to a lot of confusion and loss of type hints. It happens if anything is imported from @limetech/lime-elements from within lime elements itself, so please keep this in mind and do not do it! :smile:  (it's ok to import from @limetech/lime-elements in the examples, and this is actually how we should do it in there). Here's a PR to fix it, we maybe could investigate if it's possible to check for this kind of error automatically since it's hard to discover manually and I just did it by …
=> Avoid future cases of broken type exports

src/components/breadcrumbs/breadcrumbs.tsx
Windows:
Linux:
macOS:
Mobile:
=> perf(breadcrumbs): fix minor memory leak in limel-breadcrumbs

src/components/button-group/button-group.scss, src/components/button/button.scss, src/components/button/button.tsx, src/components/chip-set/chip-set.scss, src/components/chip-set/partial-styles/_file-picker.scss, src/components/collapsible-section/collapsible-section.scss, src/components/icon-button/icon-button.scss, src/components/icon-button/icon-button.tsx, src/components/input-field/input-field.scss, src/components/select/select.scss, src/components/split-button/split-button.scss, src/components/split-button/split-button.tsx, src/components/switch/switch.scss, src/style/internal/shared_input-select-picker.scss
When the host element is disabled, but has an `onClick`
event defined, we filter that out now, instead of preventing
clicks using a CSS hack.
fix https://github.com/Lundalogik/crm-feature/issues/3317
Windows:
Linux:
macOS:
Mobile:
=> Don't block all pointer events on disabled components, just block the click event instead

etc/lime-elements.api.md, src/components/chip-set/chip-set.scss, src/components/chip/chip.e2e.ts, src/components/chip/chip.scss, src/components/chip/chip.tsx
Only possible to see this when the chip has a `href`,
is `removable`, and is `disabled`
Windows:
Linux:
macOS:
Mobile:
=> improvements in `limel-chip`

src/components/dialog/dialog.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/2420
https://github.com/Lundalogik/lime-elements/assets/50618208/42daedb6-8f6b-40f3-bedf-72b699d878a9
but:
https://github.com/Lundalogik/lime-elements/assets/50618208/d322dfb9-024d-42bd-a284-1d3a259de210
However, if we change the input type to "button" everything magically works 🥹
Windows:
Linux:
macOS:
Mobile:
=> fix(dialog): avoid keyboard automatically opening when dialog opens on android

etc/lime-elements.api.md, src/components/config/config.tsx, src/global/config.ts
re 852282d
fix: #2781 
Windows:
Linux:
macOS:
Mobile:
=> fix(config): revert unintentional breaking change in 37.2.0

etc/lime-elements.api.md, src/components/chip-set/chip-set.e2e.ts, src/components/chip-set/chip-set.scss, src/components/chip-set/chip-set.tsx, src/components/chip-set/chip.types.ts, src/components/chip/chip.tsx
Only possible to see this when the chip has a `href`,
is `removable`, and is `disabled`
fix https://github.com/Lundalogik/crm-feature/issues/3917
Windows:
Linux:
macOS:
Mobile:
=> refactor(chip-set): replace mdc-chip with limel-chip 

src/components/chip-set/chip-set.scss, src/components/chip-set/partial-styles/_file-picker.scss, src/components/chip/chip.scss, src/components/collapsible-section/collapsible-section.scss, src/components/color-picker/color-picker.scss, src/components/form/form.scss, src/components/header/examples/header-slot-actions.tsx, src/components/header/examples/header.tsx, src/components/header/header.tsx, src/components/helper-line/helper-line.scss, src/components/input-field/input-field.scss, src/components/list/list.scss, src/components/list/partial-styles/enable-multiline-text.scss, src/components/progress-flow/progress-flow.scss, src/components/select/examples/select-narrow.scss, src/components/select/select.scss, src/components/select/select.tsx, src/components/slider/partial-styles/_thumb.scss, src/components/slider/slider.scss, src/style/internal/shared_input-select-picker.scss
The input field was necessarily tall and the height and the UI design of
all other input elements such as slider, select, picker, etc… was based
on the height & visual density of the `limel-input-field`. This resulted in
UI designs in consuming applications which were too "airy" and had a
low information density. This change will make all input elements smaller
which prevent such UI and layout design issues. Additionally, `limel-select`
used to offer a narrow UI design, which was enabled by adding an `is-narrow`
class on the component. That would render it smaller in height.
Since the component will render with the same narrow hight now by default,
that feature is removed and adding that class will not have any
visible effects.
BREAKING CHANGE:
If you have layout designs with hardcoded …
=> fix(components): decrease the height and headspace of input elements

etc/lime-elements.api.md, src/components/chip/chip.scss, src/components/chip/chip.tsx, src/components/chip/examples/chip-loading.scss, src/components/chip/examples/chip-loading.tsx, src/components/chip/examples/chip-progress.scss, src/components/chip/examples/chip-progress.tsx, src/components/chip/partial-styles/_loading.scss, src/components/chip/partial-styles/_progress.scss, src/style/color-palette-extended.css
This renders the chip with an indeterminate progress indicator, showing to the end user that something is being loaded or calculated.
fix https://github.com/Lundalogik/crm-feature/issues/3933
Windows:
Linux:
macOS:
Mobile:
=> visualize different types of progress on `limel-chip`

api-extractor.json, etc/lime-elements.api.md, src/components/action-bar/action-bar.types.ts, src/components/form/form.types.ts, src/components/menu-list/menu-list.types.ts
Windows:
Linux:
macOS:
Mobile:
=> chore: tweak api-extractor config and make some minor fixes

src/components/input-field/input-field.scss, src/style/internal/shared_input-select-picker.scss
fix: https://github.com/Lundalogik/crm-feature/issues/3959
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): make a placeholder text visible in dark mode

etc/lime-elements.api.md, src/components/picker/picker.tsx, src/components/picker/searcher.types.ts, src/components/picker/value.types.ts
Windows:
Linux:
macOS:
Mobile:
=> fix(limel-picker): align event types with values types

etc/lime-elements.api.md, src/components/picker/searcher.types.ts
Windows:
Linux:
macOS:
Mobile:
=> fix(limel-picker): searcher returns array of ListItem or ListSeparator

src/components/file-dropzone/file-dropzone.tsx
There should be no dropzone highlight if the its is disabled.
Windows:
Linux:
macOS:
Mobile:
=> fix(file-dropzone): no highlight on disable

etc/lime-elements.api.md, src/components/file-dropzone/file-dropzone.tsx, src/components/file-input/examples/file-input-type-filtering.tsx, src/components/file-input/examples/file-input.tsx, src/components/file-input/file-input.tsx
Adds a limel-file-input component that can wrap any clickable element that generates a `click` event. It will catch all click events and trigger the file input dialog to open.
The file types to be selectable can be controlled with the `accept` prop. It should conform to the HTML attribute accept format https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept
Following is example usage of the file-dropzone and file-input components working together.  A user can select files both by dragging them into the `<limel-file-dropzone>` or by clicking the `<limel-button>` wrapped in `limel-file-input`
```tsx
<limel-file-dropzone onFilesSelected={files: FileInfo[] => console.log(files)}>
<my-component />
<limel-file-input>
<limel-button label="Select files" />
</limel-file-input> …
```
=> Add a `file-input` component

src/components/file-dropzone/examples/file-dropzone-type-filtering.tsx, src/components/file-dropzone/examples/file-dropzone.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(file-dropzone): improve examples

src/components/tab-bar/tab-bar.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(tab-bar): ensure component is initialized before handling resize event

src/components/file/examples/file.tsx, src/components/file/file.scss, src/components/file/file.tsx
Makes use of the new `limel-file-dropzone` and `limel-file-input` component in `limel-file`. All the other functionality of `limel-file` should be unchanged.
Fixes https://github.com/Lundalogik/crm-feature/issues/3941
Windows:
Linux:
macOS:
Mobile:
=> Use new dropzone/input component in `limel-file`

etc/lime-elements.api.md, src/components/menu/menu.tsx
Removes additional debouncing of search in `limel-menu` since we already have debounced change events from the text input.
This means we avoid rendering a loading animation for more than half a second when the searcher resolves instantly.
Windows:
Linux:
macOS:
Mobile:
=> Menu search less loading

src/components/file-dropzone/examples/file-dropzone-type-filtering.scss, src/components/file-dropzone/file-dropzone.scss
Previously, it was a unnecessarily a `grid`,
which used to set certain expectations on its children. A block element is generic, and the consumer
can change it to whatever is suitable where they use it.
required for https://github.com/Lundalogik/lime-crm-components/pull/2187/
Windows:
Linux:
macOS:
Mobile:
=> fix(file-dropzone): display the component as a block element

etc/lime-elements.api.md, package-lock.json, package.json, src/components/text-editor/examples/text-editor-basic.tsx, src/components/text-editor/partial-styles/_prosemirror-menu.scss, src/components/text-editor/partial-styles/_prosemirror.scss, src/components/text-editor/text-editor.scss, src/components/text-editor/text-editor.spec.tsx, src/components/text-editor/text-editor.tsx
Fixes Lundalogik/crm-feature#3977
This PR in its current state just shows how the examples from the documentation might be added to the CRM, to show that things do work. But we still have to write a more robust editor from the ground up.
For reviewing:
To see what is available in Prosemirror, you may want to have a look at the Prosemirror repositories here:
https://github.com/orgs/ProseMirror/repositories?type=all 
The guide is excellent, and found at https://prosemirror.net/docs/guide/
The tutorials are also excellent https://prosemirror.net/examples/
From investigating this, I would say there are no real limitations. But implementation is generally much harder. In this issue we want to create a wrapper around a Prosemirror view, and construct the editor to have
1) Custom "lime-ish" …
=> Add rich text editor (prosemirror version)

src/components/text-editor/partial-styles/_prosemirror-menu.scss
fix https://github.com/Lundalogik/crm-feature/issues/4042
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): ensure menubar items won't grow tall

src/components/markdown/examples/markdown-headings.tsx, src/components/markdown/partial-styles/_body-text.scss, src/components/markdown/partial-styles/_headings.scss
These styles are used when markdown is renderer.
Previously headings were being rendered too large.
The result was not intended for rendering a web-page or
a presentation, where large headings improves
the presentation.
It was rather small blocks of text, for instance
representing or rendering content of "email",
or an "article".
fix https://github.com/Lundalogik/crm-feature/issues/4033
Windows:
Linux:
macOS:
Mobile:
=> fix(markdown): better heading styles

src/components/action-bar/action-bar.scss
before:
after:
Windows:
Linux:
macOS:
Mobile:
=> fix(action-bar): highlight the floating action bar

src/components/markdown/allowed-css-properties.ts, src/components/markdown/markdown-parser.ts
fix: Lundalogik/limepkg-email#695
This can be tested by adding the following snippet to the composite example for `limel-markdown` in the docs for this PR and compare to the result when using the docs for the latest release.
```html
<img
border="0"
style="width: 0.3229in; height: 0.3229in;"
src="https://lundalogik.github.io/lime-elements/versions/latest/favicon.svg"
alt="signature_2123812728"
/>
<br>
<br>
<img
border="0"
width="31"
height="31"
src="https://lundalogik.github.io/lime-elements/versions/latest/favicon.svg"
alt="signature_2123812728"
/>
```
The result should look like this:
Windows:
Linux:
macOS:
Mobile:
=> feat(markdown): allow `height` and `width` in inline `style` attribute

src/components/text-editor/examples/text-editor-as-form-component.tsx, src/components/text-editor/examples/text-editor-basic.tsx, src/components/text-editor/examples/text-editor-composite.tsx, src/components/text-editor/prosemirror-adapter/partial-styles/_prosemirror-menu.scss, src/components/text-editor/prosemirror-adapter/partial-styles/_prosemirror.scss, src/components/text-editor/text-editor.scss, src/components/text-editor/text-editor.tsx
Windows:
Linux:
macOS:
Mobile:
=> feat(text-editor): implement `readonly` prop

etc/lime-elements.api.md, src/components/select/examples/select-separators.tsx, src/components/select/select.template.tsx, src/components/select/select.tsx
fix https://github.com/Lundalogik/crm-feature/issues/4054
Windows:
Linux:
macOS:
Mobile:
=> feat(select): enable separators in dropdown list items

src/components/text-editor/examples/text-editor-composite.tsx, src/components/text-editor/prosemirror-adapter/partial-styles/_prosemirror-menu.scss, src/components/text-editor/prosemirror-adapter/partial-styles/_prosemirror.scss, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.scss, src/components/text-editor/text-editor.scss, src/components/text-editor/text-editor.tsx, src/style/internal/fieldset.scss
Windows:
Linux:
macOS:
Mobile:
=> feat(text-editor): implement label prop

src/components/text-editor/prosemirror-adapter/menu/menu-commands.ts, src/components/text-editor/prosemirror-adapter/menu/menu-items.ts, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.spec.tsx, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx
With this PR we use our action bar to create the menu items.
Commands for the various actions tied to those menu items are created and dispatched to the Editor via transactions. 
This decouples us from the built-in limitations of Prose-Mirror's menu enabling us to modify or add to the menu when we want.
A good example of a use-case for this would be add-ons wanting to add functionality to allow the user to pre-populate the text editor with a pre-built template. 
We can provide the foundation to implement that type of functionality from the consumer without worrying about navigating Prose-mirror restrictions. 
Further iteration on the action bar will be taken to distinguish menu items that will be used for prose-mirror(editor) functions but that won't be required for the intents and …
=> feat(text editor): Add custom menu

src/components/text-editor/text-editor.scss, src/components/text-editor/text-editor.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/4079
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): render an empty value for `readonly`

src/components/markdown/allowed-css-properties.ts, src/components/markdown/markdown-parser.ts
fix: https://github.com/Lundalogik/lime-elements/issues/2938
Windows:
Linux:
macOS:
Mobile:
=> fix(markdown): don't use height as a property to render an image

src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx
Stencil complains loudly when you trigger a rerender from inside the `componentDidLoad` lifecycle method. That is well and good, but we do not have a choice in this case, so we suppress the warning, so that legitimate warnings stand out better.
Windows:
Linux:
macOS:
Mobile:
=> text-editor/prosemirror-adapter: suppress Stencil-warning about triggering re-render from componentDidLoad

src/components/text-editor/examples/text-editor-height.scss, src/components/text-editor/examples/text-editor-height.tsx, src/components/text-editor/prosemirror-adapter/partial-styles/_prosemirror.scss, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.scss, src/components/text-editor/text-editor.scss, src/components/text-editor/text-editor.tsx
and never grows taller or wider than its own container
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): ensure editor resizes with its container

src/components/circular-progress/partial-styles/_percentage-colors.scss
fix: https://github.com/Lundalogik/crm-feature/issues/4070
https://github.com/Lundalogik/lime-elements/assets/50618208/1f0463e3-b246-4510-bf8c-8b16a92b3bee
Windows:
Linux:
macOS:
Mobile:
=> fix(percentage-colors): properly display percentage colors

src/components/text-editor/prosemirror-adapter/menu/menu-items.ts
This PR updates the icons used in the text editor menu and adds a helper function to display the correct keybindings to the user depending on the users system.
fixes https://github.com/Lundalogik/crm-feature/issues/4094
=> feat(text editor): add new icons and mod/option key display depending on user system

src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx
The `initializeTextEditor` should be a arrow function to work properly
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): fix broken menu

src/components/text-editor/examples/text-editor-composite.tsx, src/components/text-editor/text-editor.scss, src/components/text-editor/text-editor.tsx
…Text`
Windows:
Linux:
macOS:
Mobile:
=> text editor `helperText`

src/components/text-editor/examples/text-editor-composite.tsx, src/components/text-editor/text-editor.scss, src/components/text-editor/text-editor.tsx
Windows:
Linux:
macOS:
Mobile:
=> refactor(text-editor): initiate readOnly as false

src/components/text-editor/text-editor.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): improve accessibility of `label`

src/components/text-editor/text-editor.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): prevent the label from blocking clicks on the content

etc/lime-elements.api.md, src/components/text-editor/examples/text-editor-composite.tsx, src/components/text-editor/text-editor.scss, src/components/text-editor/text-editor.tsx
Windows:
Linux:
macOS:
Mobile:
=> feat(text-editor): add `required` prop

src/components/text-editor/text-editor.scss
for `hover` and `focus-within`
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): transition outlines & correctly visualize states

src/components/text-editor/text-editor.scss
fix https://github.com/Lundalogik/crm-feature/issues/4102
Windows:
Linux:
macOS:
Mobile:
=> chore(text-editor): shorten the address to the mixins.scss file

src/components/dock/dock-button/dock-button.scss, src/components/dock/dock-button/dock-button.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(dock): change opening direction of popover menus

src/components/menu-list/menu-list.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(menu): avoid error when `items` is undefined

src/components/list/list.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(list): avoid error when `items` is undefined

src/components/table/columns.spec.ts
Windows:
Linux:
macOS:
Mobile:
=> test(table): prevent console.warn logging expected warning to test output

src/components/dialog/dialog.tsx
Windows:
Linux:
macOS:
Mobile:
=> docs(dialog): fix broken link to DialogService (renamed to DialogRenderer)

etc/lime-elements.api.md, src/components/text-editor/examples/text-editor-allow-resize.scss, src/components/text-editor/examples/text-editor-allow-resize.tsx, src/components/text-editor/examples/text-editor-composite.tsx, src/components/text-editor/examples/text-editor-size.scss, src/components/text-editor/examples/text-editor-size.tsx, src/components/text-editor/text-editor.scss, src/components/text-editor/text-editor.tsx
Also enable consumers to turn this resizing possibility off.
fix https://github.com/Lundalogik/crm-feature/issues/4097
Windows:
Linux:
macOS:
Mobile:
=> feat(text-editor): enable end users to resize the editor

src/components/input-field/input-field.e2e.ts, src/components/input-field/input-field.scss, src/components/input-field/input-field.tsx, src/style/internal/shared_input-select-picker.scss
Makes sure the mdc textfield disabled state is updated correctly. This required changing how the invalid icon is rendered as well.
Rendering an input field as disabled with a trailing icon and later setting `disabled={false}` did not work for some reason. When initializing `MDCTextField`, it will disable the trailing icon by setting tabindex="-1" which makes it unclickable. The problem can be seen here: 
https://github.com/Lundalogik/lime-elements/assets/5563232/fd3efad7-2c38-49d8-b9a1-55796f756cd0
It is possible to reproduce by changing the date picker composite example, adding `disabled: true` to the initial state `props` and removing ``key={`updateOnFormChange-${this.key}`}`` when rendering `<limel-date-picker>`.
When updating the disabled state, the initial invalid state of the input …
=> Fix disabled trailing icon remains disabled until input field changes

src/components/input-field/examples/input-field-pattern.tsx, src/components/input-field/input-field.tsx
Avoids rendering a value that's out of sync with input while the user is typing.
- Waits until any debounced change event has been emitted before rendering new value
- Flushes any debounced change event on blur
Also changes validation of input to avoid triggering `invalid` events while rendering, and to remove some inconsistent behaviour when input is invalid.
Fixes #1425 
fix: #2742
fix: #1267
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): handle change better to keep value in sync

src/components/chip-set/chip-set.tsx
Also hides the delimiter after the last chip as long as it is not followed by an input. 
Fixes #2299
Windows:
Linux:
macOS:
Mobile:
=> Hide chip set counter when maxItems = 1

src/components/text-editor/examples/text-editor-form-data.ts, src/components/text-editor/text-editor.scss
Fixes Lundalogik/crm-feature#4098
Windows:
Linux:
macOS:
Mobile:
=> Fix text editor disabled invalid

src/components/text-editor/examples/text-editor-composite.tsx, src/components/text-editor/text-editor.scss, src/components/text-editor/text-editor.tsx
We were adding specificity of "if not `readonly`" then these
are the colors. But further down, we actually specified colors for the
readonly mode. So this was an overkill. Also would complicate styles
for next commit, for the `disabled` state.
Windows:
Linux:
macOS:
Mobile:
=> feat(text-editor): enable `disabled` prop

src/components/list/list.tsx
The mdc list will end up in a broken state if we deselect the selected item when type is radio.
Fixes #2980
Initial bug was introduced in [this](https://github.com/Lundalogik/lime-elements/pull/2821) PR.
I'm not sure if there is another solution to this instead of the "quick-fix" exception I implemented now. If you have something in mind please go ahead 🙂
Windows:
Linux:
macOS:
Mobile:
=> fix(list): don't deselect selected item when radio type

src/components/dock/dock-button/dock-button.tsx
The intersection observer was re-created every time the button in the menu was clicked, causing the callback to be invoked multiple times
Windows:
Linux:
macOS:
Mobile:
=> perf(dock): avoid re-creating observer whenever menu is opened

etc/lime-elements.api.md, src/components/chip/chip.scss, src/components/chip/chip.tsx, src/components/chip/examples/chip-menu.tsx, src/translations/da.ts, src/translations/en.ts, src/translations/fi.ts, src/translations/nl.ts, src/translations/no.ts, src/translations/sv.ts
See the description in the linked issue
fix https://github.com/Lundalogik/crm-feature/issues/4023
Windows:
Linux:
macOS:
Mobile:
=> chip: add an ellipsis menu for additional actions

src/components/button/button.tsx
Allows giving a button focus programmatically, using `myButton.focus()`.
I think this worked before without `{ delegatesFocus: true }`, but either browsers or Stencil changed something.
Windows:
Linux:
macOS:
Mobile:
=> fix(button): allow setting focus on button

etc/lime-elements.api.md, src/components/action-bar/action-bar-item/action-bar-item.tsx, src/components/text-editor/prosemirror-adapter/menu/menu-commands.ts, src/components/text-editor/prosemirror-adapter/menu/menu-items.ts, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx
Updated the command factory to include functionality to check whether the mark, eg: 'strong', 'em', 'heading' ... is active at the cursor or on the selection and update the menu items accordingly. 
Fixes [Implement selected in limel-text-editor](https://github.com/Lundalogik/crm-feature/issues/4116)
=> Use 'selected' to show the user which menu item is active

etc/lime-elements.api.md, src/components/text-editor/prosemirror-adapter/menu/menu-items.ts, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx, src/components/text-editor/text-editor.tsx, src/translations/da.ts, src/translations/en.ts, src/translations/fi.ts, src/translations/nl.ts, src/translations/no.ts, src/translations/sv.ts
In order for translations to work some streamlining of the initialisation process of the text editor and to ensure that relevant data is loaded properly was required.
Fixes https://github.com/Lundalogik/crm-feature/issues/4089
Fixes https://github.com/Lundalogik/crm-feature/issues/4118
=> feat(text editor): Enable use of translation strings for menu items

src/components/input-field/input-field.scss
fix: Lundalogik/crm-feature#4127
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): show number input when editing

src/components/chip-set/chip-set.scss
The clear all button was never shown when using recent version of Chrome or Edge.
This is because `:not(.has-chips) .clear-all-button` started matching when it didn't before. The selector needs to be more clear about which element containing the clear all button we're interested in.
Windows:
Linux:
macOS:
Mobile:
=> fix(chip-set): show clear all button

src/components/text-editor/examples/text-editor-as-form-component.scss, src/components/text-editor/examples/text-editor-as-form-component.tsx
This is mainly meant as a way to visualize when the form is dirty or not.
Windows:
Linux:
macOS:
Mobile:
=> docs(text-editor): add save and reset buttons to form component example

src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx
Fixes Lundalogik/crm-feature#4099
Windows:
Linux:
macOS:
Mobile:
=> Text editor quality improvements

src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx
Fixes Lundalogik/crm-feature#4099
**How to test:**
I've done my best to test it. Here's what to look for.
Thinking of edge cases, there's only one, which is when the initial value is empty. Try and check if this has any strange behaviour.
Also, the save button should disappear when the value goes back to what it originally was. So if your text editor says "some sentence", and you edit it to something else, and then back to "some sentence", we should not see the save button.
We believe the cause of the original bug was the fact that the default content type was changed from "html" to "markdown". To test, try and change the content type in the card component in lime admin and see if the bug persists.
Make sure saving continues to work as expected.
(Check any that applies, it's ok to leave …
=> Fix text editor gets dirty

src/components/text-editor/text-editor.scss
fix: https://github.com/Lundalogik/lime-elements/issues/3015
https://github.com/Lundalogik/lime-elements/assets/50618208/be881ef0-074b-43a0-8c7c-da8ffabc04ff
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): better visualization of readonly state

src/components/text-editor/prosemirror-adapter/plugins/image-remover-plugin.ts, src/components/text-editor/prosemirror-adapter/plugins/link-plugin.ts, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx
Updates the link plugin which handles pasting to purge images from content pasted into the text editor. 
Fixes https://github.com/Lundalogik/crm-feature/issues/4152
=> feat(text editor): block pasted inline images

src/components.d.ts, src/components/text-editor/prosemirror-adapter/menu/types.ts, src/components/text-editor/prosemirror-adapter/plugins/menu-action-interaction-plugin.ts, src/components/text-editor/prosemirror-adapter/plugins/menu-state-tracking-plugin.ts, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx
There's a risk of the prosemirror adapter becoming too heavy with different parts of the text editor being too tightly coupled. 
We should adopt the same approach for extending the adaptor as we do for menu-state tracking, via plugins. This is the way prosemirror expects us to do it and it enables us to keep a good separation of concerns allowing for future development of this tool as and when it's needed. 
This PR extracts the menu-state-tracking to a standalone plugin and does the same for handling interactions with the action bar items. 
- the `menu-state-tracking-plugin` tracks the state of the editor view to determine if a markType or nodeType is active within the active commands and returns an object of the active menu types `Record<EditorMenuTypes, boolean>`
- the …
=> Convert menu handling to plugins

src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx
Fixes Lundalogik/lime-elements#3010
How to test:
I have been using this code below, which replaces the existing basic prosemirror editor example
```
import { LimelProsemirrorAdapterCustomEvent } from '@limetech/lime-elements';
import { Component, Element, h, State } from '@stencil/core';
/**
* Basic example
*
* Try typing and editing text, or copy & paste in some rendered HTML code
* from your browser into the editor to see how it is rendered and what you get
* as an output value.
*/
@Component({
tag: 'limel-example-prosemirror-adapter-basic',
shadow: true,
})
export class ProsemirrorAdapterBasicExample {
@Element()
private host: HTMLElement;
@State()
private text: string = '';
private prosemirrorAdapter: HTMLElement;
private handleChange = (
event: …
```
=> feat(text-editor): reinitialise editor on reconnect

src/components.d.ts, src/components/portal/portal.tsx, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx
fix https://github.com/Lundalogik/crm-feature/issues/4169
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): ensure link popover opens in a decent location

src/components/text-editor/text-editor.tsx
Remove the private tag and make it beta!
**How to test**
1. Open the documentation page
2. Go to components
3. Text editor should be there
Windows:
Linux:
macOS:
Mobile:
=> feat(text-editor): make it beta

src/components/input-field/input-field.tsx
This reverts commit e33141ad1c954cb116897f2359700da8b11217f8.
When rendering an input field with `invalid` unset or set to `false`, we would set `this.mdcTextField.valid = true` and ignore the native validation state, but might still render an error icon.
For example, it might look like this:
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): revert synchronisation with invalid property

src/components/text-editor/prosemirror-adapter/prosemirror-adapter.scss, src/components/text-editor/text-editor.scss
fix https://github.com/Lundalogik/crm-feature/issues/4117
Windows:
Linux:
macOS:
Mobile:
=> text-editor: some UI touches

src/components/text-editor/examples/text-editor-allow-resize.tsx, src/components/text-editor/examples/text-editor-size.tsx, src/components/text-editor/text-editor.scss
fixes: https://github.com/Lundalogik/crm-feature/issues/4171
Windows:
Linux:
macOS:
Mobile:
=> feat(text-editor): add a CSS variable to control component's max height

src/components/table/table.scss
The table component dynamically adds inline styles such as `height` to its rows and cells. The height is added in `px`, and is calculated based on the content of the cells. In some scenarios where the cells have no content or hold web-components that load with delay, after the table is rendered, the dynamic inlined `height` styles used to be calculated very strangely, causing the rows and cells to be very short height. This change will prevent these things, by applying a proper default `min-height`.
Windows:
Linux:
macOS:
Mobile:
=> fix(table): prevent rendering rows with very short height

src/components/list/list.scss
A primary component inside a list item can get `order: 2;` or `position: absolute;`. These kinds of styles should not result in keeping a hardcoded left margin in before the text
fix https://github.com/Lundalogik/crm-feature/issues/4163
Windows:
Linux:
macOS:
Mobile:
=> fix(list): improve layout when ordering primary components in items

src/components/input-field/input-field.tsx
Makes activating input field action using keypress work again in browsers that stopped supporting the deprecated keypress event. 
fix: Lundalogik/crm-feature#4182
Windows:
Linux:
macOS:
Mobile:
=> fix(input-field): handle keydown instead of keypress event

src/components/table/table.tsx
fix Lundalogik/crm-feature#4186
Windows:
Linux:
macOS:
Mobile:
=> fix(table): use latest available options on init

src/components/table/table.tsx
Applies the correct sorting if `this.currentSorting` is an empty array
Windows:
Linux:
macOS:
Mobile:
=> fix(table): apply correct sorting

src/components/date-picker/date-picker.tsx
When the date picker is already open, clicking the input field (or tabbing to focus the clear button) would first hide the date picker on mouse down and then show it again on mouse up.
This is fixed by ignoring mousedown events from the input field. We also don't need to listen to keydown events, since we're already hiding the date picker on blur.
Windows:
Linux:
macOS:
Mobile:
=> fix(date-picker): avoid closing before input click

src/components/date-picker/date-picker.tsx, src/components/date-picker/flatpickr-adapter/flatpickr-adapter.tsx, src/components/date-picker/pickers/Picker.ts
The date formatter function used with the date picker was called lots of times, and sometimes directly by flatpickr that passed its extra args `format` and `locale`.
Now we only call the custom formatter to format the value of the date picker, passing only the value argument, and not for formatting aria labels that flatpickr sometimes renders for pickable dates.
Also updates the value of a closed date picker when set programmatically 
fixes: Lundalogik/crm-feature/issues/3182
Windows:
Linux:
macOS:
Mobile:
=> Fix date picker custom formatter called with extra args

src/components/text-editor/prosemirror-adapter/plugins/link-plugin.ts
Fixes Lundalogik/crm-feature#4213
The problem here is that when we select some text, the text may only be part of the text node. However, in the selection handler (ProseMirror view transaction callback) we copy the text from the whole node.
So if you mark your text like `<b>alpha</b> beta gamma`, and you select "gamma", what will be pasted is "beta gamma" because they occupy the same text node.
There is a slight change with how things used to be done. It used to only check for the node in which we find the selected text. But now we recurse over all nodes. This fixes a separate issue where, say, in the previous example, you selected "alpha beta" (note that alpha is in bold), you would only get the text "beta".
We can test manually. The important things are that:
1) When selecting only …
=> fix(text-editor): selected text now used for copying link text 

src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx
The z-index being set on the lime portal rendered from the prosemirror adaptor was incorrect and causing the link menu to be rendered behind other elements. 
Fixes https://github.com/Lundalogik/crm-feature/issues/4215
=> fix(text editor): ensure the link menu is correctly displayed

src/components/text-editor/prosemirror-adapter/menu/types.ts, src/components/text-editor/prosemirror-adapter/plugins/link-plugin.ts
* Allow only browser behaviour on right clicks (open context menu)
* Prevent default on link clicks within the text editor
Fixes https://github.com/Lundalogik/crm-feature/issues/4218
=> Handle clicks within the text editor

src/components/date-picker/flatpickr-adapter/_flatpickr.scss
fix:https://github.com/Lundalogik/lime-elements/issues/1922
https://github.com/user-attachments/assets/40b70660-1303-4105-a5ef-a98bb5080e1d
Windows:
Linux:
macOS:
Mobile:
=> fix(flatpicker-adapter): fix label and number cut-off

src/components/text-editor/text-editor.scss, src/components/text-editor/text-editor.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/3047
limel-elements:
https://github.com/user-attachments/assets/b9908bc7-d7c0-4943-a97f-4c9333ab8845
web-client:
1. link limel-elements to the webclient
2. go to a deal card
3. if text-editor is not there add it in Admin 
4. add some content inside the text editor so it could grow a bit
5. inspect elements
6. add `readonly` state to the limel-text-editor
7. if needed change the max-height to 5rem, so content will be scrollable 
https://github.com/user-attachments/assets/cfafa18e-10f5-4788-9c8d-6b40acabaa54
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): make content scrollable in `readonly`

etc/lime-elements.api.md, src/components/split-button/examples/split-button-loading.tsx, src/components/split-button/split-button.scss, src/components/split-button/split-button.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/2813
https://github.com/user-attachments/assets/61ad8d35-6ac3-4a67-a6f0-7a8043115955
Windows:
Linux:
macOS:
Mobile:
=> feat(split-button): add loading properties

src/components/button/button.scss
fix: https://github.com/Lundalogik/lime-elements/issues/3070
https://github.com/user-attachments/assets/b1094d36-df37-4408-9b03-bd2e4034e7ab
go to `limel-example-button-composite` example 
1. uncheck primary
2. check/uncheck loading state
Windows:
Linux:
macOS:
Mobile:
=> fix(button):  make loading feedback visible

src/components/list/list-renderer.tsx
There is already a `renderText` function. Yes, we had two separate functions, called `rendertext` and `renderText`.
Windows:
Linux:
macOS:
Mobile:
=> refactor(list): rename `rendertext` function for clarity

src/components/text-editor/text-editor.scss, src/components/text-editor/text-editor.tsx
removes these white gradients from readonly
Windows:
Linux:
macOS:
Mobile:
=> refactor(text-editor): reduce code complexity for `readonly` fade-out edge effects

src/components/snackbar/snackbar.tsx
fix Lundalogik/crm-feature#4285
Windows:
Linux:
macOS:
Mobile:
=> fix(snackbar): allow snackbar to be closed if opened with deprecated show method

src/components/dialog/dialog.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(dialog): have border-radius consistent with the header

src/style/internal/shared_input-select-picker.scss
#
Windows:
Linux:
macOS:
Mobile:
=> fix(file-picker): improve UI for readOnly

src/components/text-editor/prosemirror-adapter/prosemirror-adapter.scss, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx, src/components/text-editor/text-editor.scss
Toolbar didn't keep its backdrop blur effect
when editor isn't focused or hovered.
This was due the rendering conflict.
An element which has transparency does
not properly display backgrop effects.
fix https://github.com/Lundalogik/lime-elements/issues/3119
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): always keep toolbar's backdrop blur effect

src/components/snackbar/snackbar.tsx
The snackbar would not open if an HTML element was created and added to the DOM programatically
fix Lundalogik/crm-feature#4341
Windows:
Linux:
macOS:
Mobile:
=> fix(snackbar): open snackbar when created programatically

src/components/spinner/examples/spinner-color.scss, src/components/spinner/spinner.scss
fix: https://github.com/Lundalogik/lime-elements/issues/3140
Windows:
Linux:
macOS:
Mobile:
=> Spinner brandcolors

package-lock.json
-CHANGELOG-
When the markdown component is fed html in which there is a blank line (2 consecutive line breaks) anywhere between the opening bracket and the closing bracket, the components crashes. Update the sub-dependency `hast-util-raw` to avoid this. The parser now switches to text-mode when this happens, which will output the rest of the html after the blank line, up until the closing bracket, as text. So it still will not render the html element correctly, but at least the parser does not crash, and the rest of the content after the element's closing bracket will be rendered correctly.
fix: #3149
Windows:
Linux:
macOS:
Mobile:
=> fix(markdown): do not crash when html tag contains blank line

src/components/file-input/examples/file-input-type-filtering.tsx, src/components/file-input/examples/file-input.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/4353
Windows:
Linux:
macOS:
Mobile:
=> fix(file-input): make sure disabled styling is applied

src/components/form/fields/schema-field.ts, src/components/form/widgets/date-only-picker.ts, src/components/form/widgets/date-picker.ts, src/components/form/widgets/index.ts, src/components/form/widgets/time-picker.ts
This fixes some issues in `limel-form` when using the date picker widget or when using a custom component for 
the string formats `date-time`, `date` or `time`.
The `type` date picker prop is now set depending on the schema format (`date-time` or `date`) in the date widget. This has been broken since c290470676896cc965e2ac3b487fae6783100e6e
Fixes #1489
Fixes #2232
Windows:
Linux:
macOS:
Mobile:
=> Fix date and time formats

src/components/snackbar/snackbar.tsx
fix Lundalogik/crm-feature#4288
Windows:
Linux:
macOS:
Mobile:
=> fix(snackbar): allow the snackbar to be created in its opened state

src/components/table/table.tsx
The element pool should only be released if all the data should be replaced. 
Fixes https://github.com/Lundalogik/crm-feature/issues/4377
=> fix(table): only release element pool if should replace is true

src/components/table/table.tsx
Windows:
Linux:
macOS:
Mobile:
=> fix(table-view): only release element pool if should replace is true

src/components/portal/portal.scss, src/components/portal/portal.tsx
If many portals are rendered on a page there might be a heavy performance hit when all the elements are moved around in the DOM at the same time. We only need to actually move the elements once the portal becomes visible.
Windows:
Linux:
macOS:
Mobile:
=> perf(portal): do DOM manipulation when portal becomes visible

src/components/form/templates/array-field-collapsible-item.ts
Very large forms can becomve very slow since there are a lot of elements that are rendered. Many forms contain collapsible sections, and elements in collapsed sections do not need to be rendered until the section is first opened
Windows:
Linux:
macOS:
Mobile:
=> perf(form): render collapsed children when they become visible

src/components/info-tile/info-tile.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/3171
Windows:
Linux:
macOS:
Mobile:
=> Aria busy info tile

src/components/progress-flow/progress-flow-item/partial-styles/_selected-indicator.scss, src/components/progress-flow/progress-flow-item/progress-flow-item.tsx, src/test-assets/icons/lock.svg
fix: https://github.com/Lundalogik/lime-elements/issues/2037
Windows:
Linux:
macOS:
Mobile:
=> fix(progress-flow): increase lock icon visibility

src/components/button/button.tsx
fix: https://github.com/Lundalogik/lime-elements/issues/3172
Windows:
Linux:
macOS:
Mobile:
=> Aria busy loading button

src/components/icon/icon.scss
fix: https://github.com/Lundalogik/lime-elements/issues/1854
Windows:
Linux:
macOS:
Mobile:
=> fix(icons): icons according to size rhythms

src/components/markdown/markdown-parser.ts
This was broken back in 43e89bfc4e936e4d1c2c300820ac87888d3aa6ec, which was only partially fixed in c452f3076e1c7dbe36539adb83d684c046f86062.
fix: Lundalogik/crm-feature#4348
Windows:
Linux:
macOS:
Mobile:
=> fix(markdown): fix broken default config - allow target attribute on links and more

etc/lime-elements.api.md, src/components/chip-set/chip-set.tsx
In the Chip set and Picker, the autocomplete creates issues. In `limel-picker` (which is a consumer of `limel-chip-set` this behavior is more annoying.
But since the `autocomplete` in the Chip set is set to `'off'` by default, the annoying problem should automatically disappear from Picker.
fix https://github.com/Lundalogik/crm-feature/issues/4386
Windows:
Linux:
macOS:
Mobile:
=> feat(chip-set): add `autocomplete` as a prop for `input` type

src/components/chip/chip.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(chip): keep original image ratio

src/components/popover-surface/popover-surface.scss
fix: https://github.com/Lundalogik/lime-elements/issues/3238
Windows:
Linux:
macOS:
Mobile:
=> fix(popover-surface): have fully visible popover

src/components/split-button/split-button.scss
Windows:
Linux:
macOS:
Mobile:
=> split button styles

etc/lime-elements.api.md, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx, src/components/text-editor/text-editor.tsx
re: #3139
Windows:
Linux:
macOS:
Mobile:
=> chore(text-editor): fix `ae-incompatible-release-tags` warning in api

src/components/dialog/dialog.scss, src/components/dialog/dialog.tsx
By removing MDC's hard-coded `min-height`.
This renders a smaller footer, when the footer only contains elements with `display: none;` visualized below: 👇 
https://github.com/user-attachments/assets/f69475da-945a-44bf-a487-548db0ff07de
This is still not perfect, since the footer has some hardcoded padding too (coming form MDC) which will anyway render it in the UI as a white block.
fix: https://github.com/Lundalogik/lime-elements/issues/1009
fix: https://github.com/Lundalogik/lime-elements/issues/3265
Windows:
Linux:
macOS:
Mobile:
=> fix(dialog): let footer's height be based on its children

src/style/color-palette-extended.css, src/style/mixins.scss, src/style/shadows.scss
The effect is the same in modern browsers.
There will be slightly less code to read for us.
fix https://github.com/Lundalogik/lime-elements/issues/3273
fix https://github.com/Lundalogik/lime-elements/issues/2086
Windows:
Linux:
macOS:
Mobile:
=> make shadows better

src/components/snackbar/snackbar.tsx
I have identified the issue in the `limel-snackbar` component where setting the `timeout` to -1 causes the snackbar to hide immediately. To fix this, I've updated the `handleOpen` method in the `Snackbar` class to treat negative timeout values as persistent (no timeout). Here's a summary of the changes:
1. Modified the `handleOpen` method to check if the timeout is greater than 0 before setting the timeout.
2. Updated the JSDoc comment for the `timeout` property to clarify the behavior with different values.
These changes ensure that setting `timeout` to -1 (or any negative value) will make the snackbar persistent, matching the expected behavior described in the problem statement. 
> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check …
=> Autofix: Snackbar never shown when timeout is -1

src/components/checkbox/checkbox.scss, src/components/dynamic-label/dynamic-label.scss, src/components/dynamic-label/dynamic-label.tsx, src/components/switch/switch.scss
This is important specially because this component is
used to visualize the readonly state of the boolean elements
(checkbox and switch) which don't truncate their text by deafult
Windows:
Linux:
macOS:
Mobile:
=> UI improvements in dynamic-label, checkbox, and switch

etc/lime-elements.api.md, src/components/markdown/markdown-parser.ts, src/components/markdown/markdown.tsx, src/components/text-editor/examples/text-editor-custom-element.tsx, src/components/text-editor/examples/text-editor-custom-triggers.scss, src/components/text-editor/examples/text-editor-custom-triggers.tsx, src/components/text-editor/prosemirror-adapter/plugins/trigger/factory.ts, src/components/text-editor/prosemirror-adapter/plugins/trigger/inserter.ts, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx, src/components/text-editor/text-editor.tsx, src/components/text-editor/text-editor.types.ts, src/components/text-editor/types.ts, src/components/text-editor/utils/markdown-converter.ts, src/components/text-editor/utils/plugin-factory.ts, src/global/shared-types/custom-element.types.ts, src/interface.ts
Adds triggers to be used when detecting a certain string and starting a trigger session. A trigger session begins when the magic string sequence is inserted, for instance an @ and will keep on sending user input back to the consumer until certain stop conditions occur.
fixes: Lundalogik/crm-feature#4430
Co-authored-by: John Traas <john.traas@lime.tech>
Windows:
Linux:
macOS:
Mobile:
=> Trigger plugin

src/components/table/partial-styles/_row-selection.scss
fix https://github.com/Lundalogik/crm-feature/issues/4446
Windows:
Linux:
macOS:
Mobile:
=> fix(table): prevent row selections from ruining the layout

src/components/text-editor/link-menu/editor-link-menu.tsx, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx
The text field in the link popup window will now have a default value of `https://` so the user does not have to enter it manuallt. Additionally, you cannot press "Save" unless the URL is valid
fix: https://github.com/Lundalogik/crm-feature/issues/4349
Windows:
Linux:
macOS:
Mobile:
=> ensure external links are properly normalized with https

src/components/form/templates/array-field-collapsible-item.ts
Sets the initial state `isOpen` of a collapsible item in a form correctly.
State shouldn't be updated in the constructor of a React component using `this.setState`. It should just be assigned an initial value.
fix: #3288
Windows:
Linux:
macOS:
Mobile:
=> fix(form): set collapsible item initial state correctly

src/components/form/templates/grid-layout.ts
The element sometimes seems to be undefined, causing some flaky integration tests in some browsers
Windows:
Linux:
macOS:
Mobile:
=> fix(form): handle undefined element

src/components/input-field/input-field.tsx, src/components/menu-surface/menu-surface.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/4408
Windows:
Linux:
macOS:
Mobile:
=> input-field: do not close completions dropdown when onscreen keyboard opens

src/components/input-field/input-field.tsx, src/components/menu-surface/menu-surface.tsx
Backport of #3294
fix: https://github.com/Lundalogik/crm-feature/issues/4408
Windows:
Linux:
macOS:
Mobile:
=> Backport input field dropdown fix

etc/lime-elements.api.md, src/components/text-editor/text-editor.tsx, src/components/text-editor/types.ts
Fixes https://github.com/Lundalogik/crm-feature/issues/4455
May need separate PR's in both building blocks and lime-crm-components to then import and use the Type definition.
=> Add a Type definition for uiType used in the text-editor

etc/lime-elements.api.md, package-lock.json, package.json, src/components/text-editor/examples/text-editor-with-tables.tsx, src/components/text-editor/prosemirror-adapter/plugins/table-plugin.ts, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx, src/components/text-editor/text-editor.tsx
Windows:
Linux:
macOS:
Mobile:
=> [WIP] prosemirror tables

package-lock.json, package.json
As per this [post here](https://discuss.prosemirror.net/t/heads-up-xss-risk-in-domserializer/6572) we should update to prosemirror-model 1.22.1 as it contains a fix for a vulnerability to xss attacks in the DOMSerialiser.
=> chore(text editor): bump prosemirror-model to 1.22.1

package-lock.json, package.json, src/components/text-editor/examples/text-editor-with-tables.tsx, src/components/text-editor/prosemirror-adapter/plugins/table-plugin.ts, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx, src/components/text-editor/text-editor.tsx
Find the original [PR here](https://github.com/Lundalogik/lime-elements/pull/3243)
=> Add tables plugin to text editor

etc/lime-elements.api.md, src/components/card/card.scss, src/components/card/card.tsx, src/components/card/examples/card-actions.tsx, src/components/card/examples/card-basic.scss, src/components/card/examples/card-basic.tsx, src/components/card/examples/card-clickable.tsx, src/components/card/examples/card-image.tsx, src/components/card/examples/card-nested-component.scss, src/components/card/examples/card-nested-component.tsx, src/components/card/examples/card-orientation.tsx, src/components/card/examples/card-resizable-container.scss, src/components/card/examples/card-slot.tsx, src/components/card/examples/card-styling.scss, src/components/card/examples/card-styling.tsx
Windows:
Linux:
macOS:
Mobile:
=> feat(card): add new component

src/components/text-editor/prosemirror-adapter/plugins/trigger/factory.ts
fix: Lundalogik/crm-feature#4470
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): make sure trigger characters work on Android

src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx, src/components/text-editor/text-editor.spec.tsx, src/components/text-editor/text-editor.tsx
Fixes: https://github.com/Lundalogik/crm-feature/issues/4476
This uses ref forwarding to override the default focus method allowing a consumer to set focus on the prosemirror editor view.
=> Delegate the focus inside the text editor

src/components/markdown/markdown-parser.ts
fix: Lundalogik/crm-feature#4422
Windows:
Linux:
macOS:
Mobile:
=> fix(markdown): better image resizing

etc/lime-elements.api.md, src/components/text-editor/examples/text-editor-custom-triggers.tsx, src/components/text-editor/prosemirror-adapter/plugins/trigger/inserter.ts, src/components/text-editor/text-editor.types.ts
Add's a function to the `inserterFactory` called `stopTrigger` which the consumer can access via the `TextEditor (TriggerFunction)` interface.
Fixes: https://github.com/Lundalogik/crm-feature/issues/4474
=> Add function to inserter to stopTrigger

src/components/card/card.scss, src/components/card/card.tsx, src/components/info-tile/info-tile.scss, src/components/info-tile/info-tile.tsx, src/style/mixins.scss, src/util/3d-tilt-hover-effect.ts
Windows:
Linux:
macOS:
Mobile:
=> 🤩fy card & info-tile

package-lock.json, package.json, src/components/markdown/markdown-parser.ts, src/components/text-editor/utils/html-converter.ts
This fixes a bug introduced by #3318
This is a backport of #3328
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): fix bug where html was interpreted as markdown

src/components/text-editor/prosemirror-adapter/prosemirror-adapter.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): correctly animate the padding property

etc/lime-elements.api.md, src/components/list/list.tsx, src/components/menu-list/menu-list.tsx, src/components/text-editor/examples/text-editor-custom-triggers.tsx
Adds a specific event for interaction in `limel-list`. With the current change event it can be hard to sort out which element was actually interacted with.
If one item is already selected and a new one is clicked then one could see which one is selected to know the interaction. But if the same selected item is clicked it's not possible to know that that element was interacted with since the events come one by one by design.
With the new interaction event it's easy to know which item was either clicked or selected by other means.
Windows:
Linux:
macOS:
Mobile:
=> Clicked item event in list

etc/lime-elements.api.md, src/components/text-editor/examples/text-editor-custom-triggers.tsx, src/components/text-editor/prosemirror-adapter/plugins/trigger/create-html-inserter.spec.ts, src/components/text-editor/prosemirror-adapter/plugins/trigger/create-html-inserter.ts, src/components/text-editor/prosemirror-adapter/plugins/trigger/factory.ts, src/components/text-editor/prosemirror-adapter/plugins/trigger/inserter.ts, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx, src/components/text-editor/text-editor.types.ts
Fixes https://github.com/Lundalogik/limepkg-email/issues/1210
I would be delighted to write some tests, but the overall test coverage for the trigger factory appears to be rather limited.
I presume that mocking ProseMirror is a prerequisite for writing tests for this component, which I am not entirely comfortable with.
Windows:
Linux:
macOS:
Mobile:
=> feat(text-editor): add insertHtml function to properly parse html string

src/components/text-editor/prosemirror-adapter/plugins/trigger/factory.ts
Sends a stopTrigger event when the cursor goes outside the trigger.
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): send stop trigger when outside

src/components/text-editor/text-editor.scss
fix: https://github.com/Lundalogik/crm-feature/issues/4519
https://github.com/user-attachments/assets/4621d83a-f8cc-43b8-8429-ccd444e2a3df
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): don't show placeholder when composer is active

src/components/popover-surface/popover-surface.scss, src/components/popover/examples/popover-basic.scss, src/components/popover/examples/popover-basic.tsx, src/components/popover/examples/popover-styling.scss, src/components/popover/examples/popover-styling.tsx, src/components/popover/popover.scss, src/components/popover/popover.tsx
Windows:
Linux:
macOS:
Mobile:
=> feat(popover): add new CSS variable for controlling surface's `box-shadow`

src/components/spinner/examples/spinner.tsx, src/components/spinner/spinner.tsx
There is lime's logo everywhere the spinner is being used. In a public library, it is better that this specific design is not default.
In Lime's products, there is no point of repeating this logo everywhere in the UI, and a better approach is to
more purposefully set it to `true`, where appropriate in the ui.
Windows:
Linux:
macOS:
Mobile:
=> chore(spinner): do not set `limeBranded` to `true` by default

src/components/text-editor/prosemirror-adapter/prosemirror-adapter.tsx
Makes sure to delegate the focus so that the focus event chain will focus prosemirror.
fixes: Lundalogik/crm-feature#4528
Windows:
Linux:
macOS:
Mobile:
=> fix(prosemirror-adaptor): delegate focus

etc/lime-elements.api.md, src/components/picker/examples/picker-basic.tsx, src/components/picker/examples/picker-composite.tsx, src/components/picker/examples/picker-empty-suggestions.tsx, src/components/picker/examples/picker-icons.tsx, src/components/picker/examples/picker-leading-icon-example.tsx, src/components/picker/examples/picker-multiple.tsx, src/components/picker/examples/picker-static-action.tsx, src/components/picker/examples/picker-value-as-object-with-actions.tsx, src/components/picker/examples/picker-value-as-object.tsx, src/components/picker/picker.tsx
Windows:
Linux:
macOS:
Mobile:
=> limel-picker: add default searcher function for simple client-side filtering

src/components/text-editor/text-editor.scss
Fixes #3390 
| Before fix |  |
|--------|--------|
| Required | ![image](https://github.com/user-attachments/assets/224700ca-588a-428e-bc7c-5ddca1f99495) |
| Non-required | ![image](https://github.com/user-attachments/assets/f7c00510-7d0d-4e8e-bfe6-53b35fe7a0a4) | 
| After fix |  |
|--------|--------|
| Required | ![image](https://github.com/user-attachments/assets/6367b5c4-616b-4e6a-b407-42d5504842ef) |
| Non-required | ![image](https://github.com/user-attachments/assets/d75d9be1-2121-450b-9502-688f28cbbc5f) | 
Windows:
Linux:
macOS:
Mobile:
=> Text Editor: trailing * is added to label even if required=false

etc/lime-elements.api.md, src/components/list/examples/list-pictures.tsx, src/components/list/list-item.types.ts, src/components/list/list-renderer.tsx, src/components/list/list.scss, src/components/list/list.tsx, src/components/picker/examples/picker-pictures.tsx, src/components/picker/picker.tsx
Windows:
Linux:
macOS:
Mobile:
=> add support for displaying pictures in the list items

src/components/table/partial-styles/_row-selection.scss, src/components/table/table.scss
fix https://github.com/Lundalogik/crm-feature/issues/4028
To see this issue, you need to find the right table that makes these random font-sizes. 
1. Clone Dev-Features database, and 
2. Open your local dev on a iPhone, use Browser stack for instance
3. go to History table
4. Make a filter using the _begins with_, and typing `%limebb` in the input field and pressing ENTER.
5. This will filter the table in a way that you see all those cells with gigantic font size.
6. Make sure other tables look fine, specially the ones with custom components in them
Windows:
Linux:
macOS:
Mobile:
=> Table: issues with font size

src/components/text-editor/prosemirror-adapter/prosemirror-adapter.scss, src/components/text-editor/text-editor.scss
fix https://github.com/Lundalogik/lime-elements/issues/3406
Windows:
Linux:
macOS:
Mobile:
=> fix(text-editor): don't animate the `padding` around the content

src/components/markdown/markdown.scss, src/components/markdown/partial-styles/_adjust-for-table-cell.scss, src/components/markdown/partial-styles/_img.scss
fix https://github.com/Lundalogik/crm-feature/issues/4577
Windows:
Linux:
macOS:
Mobile:
=> add helper classes for internal use in limel-markdown

src/components/card/card.scss
If a consumer sets a `height` or `width` on the
card element, the surface of the card should
respect that specified size, and not just rely on
the size or amount of the content inside the card.
fix https://github.com/Lundalogik/crm-feature/issues/4582
Windows:
Linux:
macOS:
Mobile:
=> fix(card): ensure the surface is as big as the card

src/components/header/examples/header-colors.scss, src/components/header/examples/header-colors.tsx, src/components/header/examples/header-narrow.scss, src/components/header/examples/header-narrow.tsx, src/components/header/header.scss, src/components/header/header.tsx
Now the consumer can specify `color` and `backgroundColor` directly on the `icon`. The styles code are however backwards compatible, and still support the old custom CSS props of `--header-icon-color` and `--header-icon-background-color`. In case any consumer has specified the CSS props, they will get the same result as before. But we removed the props from the documentations, since we want the consumers to use the `Icon` interface instead of adding styles.
Windows:
Linux:
macOS:
Mobile:
=> feat(header): properly support the `Icon` interface

src/components/select/select.scss, src/components/select/select.template.tsx
fix: https://github.com/Lundalogik/crm-feature/issues/4462#issuecomment-2604960741
Windows:
Linux:
macOS:
Mobile:
=> fix(select): improve visualisation of the `readOnly` state

src/components/table/partial-styles/_tabulator-footer.scss, src/components/table/partial-styles/tabulator-custom-styles.scss, src/components/table/table.scss
fix https://product.lime-crm.com/client/object/bug/7808?tab=_overview
The summary/aggregation of the column is not shown correctly. The number is being cut, not being readable.A lot of costumers reaching out about this., see example pic
Windows:
Linux:
macOS:
Mobile:
=> refactor(table): use an SCSS variable for the height of aggregations row

src/style/mixins.scss
Some of our mixins have inbuilt transitions.
Sometimes the consumer has to override everything, which will either 
- result in a really poor animation
- or a lot of repeated code
Windows:
Linux:
macOS:
Mobile:
=> chore(mixins): enable passing extra transitionable props to some mixins

src/components/info-tile/info-tile.tsx
The 3D hover glow effect was not correctly being rendered, due to its location in the dom.
https://github.com/user-attachments/assets/9d6f0517-dc7f-4a07-9122-30b156984263
https://github.com/user-attachments/assets/b4ca9430-66d4-47e3-a23d-772c19069401
Windows:
Linux:
macOS:
Mobile:
=> fix(info-tile): render the 3d glow effect with the right intensity

src/style/mixins.scss
Reverts Lundalogik/lime-elements#3430
Since this var is undefined, it breaks all the other transitions caused by this mixin. So changes happen instantly instead. Right now I do not know how to fix this issue. But maybe later I can come up with a solution.
=> Revert "chore(mixins): enable passing extra transitionable props to some mixins"

src/components/markdown/examples/markdown-keys.tsx, src/components/markdown/markdown.scss, src/components/markdown/markdown.tsx, src/components/markdown/partial-styles/_kbd.scss, src/components/text-editor/prosemirror-adapter/prosemirror-adapter.scss
Windows:
Linux:
macOS:
Mobile:
=> fix(markdown): better render the `<kbd>` element
